import { FoodDto } from './food.types';

export const INITIAL_FOOD_CATALOG: Omit<FoodDto, 'createdAt' | 'updatedAt'>[] = [
  {
    "id": "food_chicken_breast_raw",
    "name": "Chicken Breast (Raw, Skinless)",
    "normalizedName": "chicken breast raw skinless",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 120,
    "protein": 26,
    "carbohydrates": 0,
    "fat": 1.8,
    "fiber": 0,
    "sugar": 0,
    "sodium": 65,
    "source": "USDA",
    "sourceId": "fdc_171077",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_chicken_breast_cooked",
    "name": "Chicken Breast (Grilled/Cooked)",
    "normalizedName": "chicken breast grilled cooked",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 165,
    "protein": 31,
    "carbohydrates": 0,
    "fat": 3.6,
    "fiber": 0,
    "sugar": 0,
    "sodium": 74,
    "source": "USDA",
    "sourceId": "fdc_171477",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_chicken_thigh",
    "name": "Chicken Thigh (Skinless, Cooked)",
    "normalizedName": "chicken thigh skinless cooked",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 180,
    "protein": 24.5,
    "carbohydrates": 0,
    "fat": 8.5,
    "fiber": 0,
    "sugar": 0,
    "sodium": 86,
    "source": "USDA",
    "sourceId": "fdc_173629",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_chicken_leg",
    "name": "Chicken Drumstick / Leg (Cooked)",
    "normalizedName": "chicken drumstick leg cooked",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 172,
    "protein": 24,
    "carbohydrates": 0,
    "fat": 8,
    "fiber": 0,
    "sugar": 0,
    "sodium": 89,
    "source": "USDA",
    "sourceId": "fdc_173628",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_turkey_breast",
    "name": "Turkey Breast (Roasted)",
    "normalizedName": "turkey breast roasted",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 135,
    "protein": 30,
    "carbohydrates": 0,
    "fat": 1.5,
    "fiber": 0,
    "sugar": 0,
    "sodium": 55,
    "source": "USDA",
    "sourceId": "fdc_171488",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_egg_whole",
    "name": "Egg (Whole, Large)",
    "normalizedName": "egg whole large",
    "category": "Protein",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 72,
    "protein": 6.3,
    "carbohydrates": 0.4,
    "fat": 4.8,
    "fiber": 0,
    "sugar": 0.2,
    "sodium": 71,
    "source": "USDA",
    "sourceId": "fdc_171287",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_egg_white",
    "name": "Egg Whites (Liquid / Boiled)",
    "normalizedName": "egg whites liquid boiled",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 52,
    "protein": 10.9,
    "carbohydrates": 0.7,
    "fat": 0.2,
    "fiber": 0,
    "sugar": 0.7,
    "sodium": 166,
    "source": "USDA",
    "sourceId": "fdc_172183",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_lean_beef",
    "name": "Lean Beef (90/10, Cooked)",
    "normalizedName": "lean beef 90 10 cooked",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 217,
    "protein": 26.1,
    "carbohydrates": 0,
    "fat": 11.8,
    "fiber": 0,
    "sugar": 0,
    "sodium": 68,
    "source": "USDA",
    "sourceId": "fdc_174032",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_beef_steak",
    "name": "Beef Sirloin Steak (Trimmed, Grilled)",
    "normalizedName": "beef sirloin steak trimmed grilled",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 205,
    "protein": 29,
    "carbohydrates": 0,
    "fat": 9,
    "fiber": 0,
    "sugar": 0,
    "sodium": 58,
    "source": "USDA",
    "sourceId": "fdc_174033",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_lamb_lean",
    "name": "Lean Lamb (Cooked, Trimmed)",
    "normalizedName": "lean lamb cooked trimmed",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 206,
    "protein": 28,
    "carbohydrates": 0,
    "fat": 9.5,
    "fiber": 0,
    "sugar": 0,
    "sodium": 72,
    "source": "USDA",
    "sourceId": "fdc_174050",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_pork_tenderloin",
    "name": "Pork Tenderloin (Roasted, Lean)",
    "normalizedName": "pork tenderloin roasted lean",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 143,
    "protein": 26.2,
    "carbohydrates": 0,
    "fat": 3.5,
    "fiber": 0,
    "sugar": 0,
    "sodium": 53,
    "source": "USDA",
    "sourceId": "fdc_168250",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_tuna_canned",
    "name": "Tuna (Canned in Water, Drained)",
    "normalizedName": "tuna canned in water drained",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 116,
    "protein": 25.5,
    "carbohydrates": 0,
    "fat": 0.8,
    "fiber": 0,
    "sugar": 0,
    "sodium": 338,
    "source": "USDA",
    "sourceId": "fdc_175159",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_salmon_atlantic",
    "name": "Atlantic Salmon (Cooked, Wild/Farmed)",
    "normalizedName": "atlantic salmon cooked wild farmed",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 206,
    "protein": 22.1,
    "carbohydrates": 0,
    "fat": 12.3,
    "fiber": 0,
    "sugar": 0,
    "sodium": 61,
    "source": "USDA",
    "sourceId": "fdc_173686",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_sardines",
    "name": "Sardines (Canned in Tomato / Water)",
    "normalizedName": "sardines canned in tomato water",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 185,
    "protein": 21,
    "carbohydrates": 0.5,
    "fat": 10.5,
    "fiber": 0,
    "sugar": 0,
    "sodium": 400,
    "source": "USDA",
    "sourceId": "fdc_175148",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_mackerel",
    "name": "Mackerel Fish (Grilled/Cooked)",
    "normalizedName": "mackerel fish grilled cooked",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 262,
    "protein": 23.8,
    "carbohydrates": 0,
    "fat": 17.8,
    "fiber": 0,
    "sugar": 0,
    "sodium": 83,
    "source": "USDA",
    "sourceId": "fdc_175150",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_prawns_shrimp",
    "name": "Prawns / Shrimp (Cooked)",
    "normalizedName": "prawns shrimp cooked",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 99,
    "protein": 24,
    "carbohydrates": 0.2,
    "fat": 0.3,
    "fiber": 0,
    "sugar": 0,
    "sodium": 111,
    "source": "USDA",
    "sourceId": "fdc_175180",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_paneer_regular",
    "name": "Paneer (Standard Indian Cottage Cheese)",
    "normalizedName": "paneer standard indian cottage cheese",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 265,
    "protein": 18.3,
    "carbohydrates": 3.4,
    "fat": 20.8,
    "fiber": 0,
    "sugar": 2.5,
    "sodium": 18,
    "source": "USDA",
    "sourceId": "fdc_ind_paneer",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_paneer_lowfat",
    "name": "Low-Fat Paneer",
    "normalizedName": "low fat paneer",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 160,
    "protein": 24,
    "carbohydrates": 4,
    "fat": 5,
    "fiber": 0,
    "sugar": 3,
    "sodium": 25,
    "source": "USDA",
    "sourceId": "fdc_ind_lowfat_paneer",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_tofu_firm",
    "name": "Tofu (Firm)",
    "normalizedName": "tofu firm",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 83,
    "protein": 10,
    "carbohydrates": 2,
    "fat": 4.8,
    "fiber": 1,
    "sugar": 0.5,
    "sodium": 10,
    "source": "USDA",
    "sourceId": "fdc_172449",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_tempeh",
    "name": "Tempeh (Cooked)",
    "normalizedName": "tempeh cooked",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 193,
    "protein": 20.3,
    "carbohydrates": 7.6,
    "fat": 10.8,
    "fiber": 4.5,
    "sugar": 0,
    "sodium": 9,
    "source": "USDA",
    "sourceId": "fdc_174272",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_soy_chunks",
    "name": "Soy Chunks / Mealmaker (Dry)",
    "normalizedName": "soy chunks mealmaker dry",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 345,
    "protein": 52,
    "carbohydrates": 33,
    "fat": 0.5,
    "fiber": 13,
    "sugar": 5,
    "sodium": 15,
    "source": "USDA",
    "sourceId": "fdc_soy_chunks",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_greek_yogurt_plain",
    "name": "Greek Yogurt (Plain, Non-Fat)",
    "normalizedName": "greek yogurt plain non fat",
    "category": "Dairy",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 59,
    "protein": 10.2,
    "carbohydrates": 3.6,
    "fat": 0.4,
    "fiber": 0,
    "sugar": 3.2,
    "sodium": 36,
    "source": "USDA",
    "sourceId": "fdc_170889",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_curd_dahi",
    "name": "Curd / Dahi (Whole Milk)",
    "normalizedName": "curd dahi whole milk",
    "category": "Dairy",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 61,
    "protein": 3.5,
    "carbohydrates": 4.7,
    "fat": 3.3,
    "fiber": 0,
    "sugar": 4.7,
    "sodium": 46,
    "source": "USDA",
    "sourceId": "fdc_170885",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_milk_whole",
    "name": "Whole Milk",
    "normalizedName": "whole milk",
    "category": "Dairy",
    "servingSize": 100,
    "servingUnit": "ml",
    "calories": 61,
    "protein": 3.2,
    "carbohydrates": 4.8,
    "fat": 3.3,
    "fiber": 0,
    "sugar": 5.1,
    "sodium": 43,
    "source": "USDA",
    "sourceId": "fdc_171265",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_milk_toned",
    "name": "Toned Milk / Skim Milk",
    "normalizedName": "toned milk skim milk",
    "category": "Dairy",
    "servingSize": 100,
    "servingUnit": "ml",
    "calories": 42,
    "protein": 3.4,
    "carbohydrates": 5,
    "fat": 1.5,
    "fiber": 0,
    "sugar": 5,
    "sodium": 52,
    "source": "USDA",
    "sourceId": "fdc_171267",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_whey_isolate",
    "name": "Whey Protein Isolate (1 Scoop)",
    "normalizedName": "whey protein isolate 1 scoop",
    "category": "Protein",
    "servingSize": 30,
    "servingUnit": "grams",
    "calories": 110,
    "protein": 25,
    "carbohydrates": 1,
    "fat": 0.5,
    "fiber": 0,
    "sugar": 0.5,
    "sodium": 140,
    "source": "USDA",
    "sourceId": "fdc_whey_iso",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_cottage_cheese",
    "name": "Cottage Cheese (Low-Fat)",
    "normalizedName": "cottage cheese low fat",
    "category": "Dairy",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 84,
    "protein": 11.1,
    "carbohydrates": 4.3,
    "fat": 2.3,
    "fiber": 0,
    "sugar": 3.8,
    "sodium": 364,
    "source": "USDA",
    "sourceId": "fdc_173418",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_rice_white_cooked",
    "name": "White Rice (Cooked)",
    "normalizedName": "white rice cooked",
    "category": "Carbohydrates",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 130,
    "protein": 2.7,
    "carbohydrates": 28.2,
    "fat": 0.3,
    "fiber": 0.4,
    "sugar": 0.1,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_168878",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_rice_white_raw",
    "name": "White Rice (Raw/Uncooked)",
    "normalizedName": "white rice raw uncooked",
    "category": "Carbohydrates",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 365,
    "protein": 7.1,
    "carbohydrates": 80,
    "fat": 0.7,
    "fiber": 1.3,
    "sugar": 0.1,
    "sodium": 5,
    "source": "USDA",
    "sourceId": "fdc_169756",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_rice_brown_cooked",
    "name": "Brown Rice (Cooked)",
    "normalizedName": "brown rice cooked",
    "category": "Carbohydrates",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 123,
    "protein": 2.7,
    "carbohydrates": 25.6,
    "fat": 1,
    "fiber": 1.6,
    "sugar": 0.2,
    "sodium": 4,
    "source": "USDA",
    "sourceId": "fdc_169704",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_rice_red_cooked",
    "name": "Red Rice (Cooked / Matta Rice)",
    "normalizedName": "red rice cooked matta rice",
    "category": "Carbohydrates",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 111,
    "protein": 2.3,
    "carbohydrates": 23.5,
    "fat": 0.8,
    "fiber": 2,
    "sugar": 0.2,
    "sodium": 3,
    "source": "USDA",
    "sourceId": "fdc_red_rice",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_rice_basmati_cooked",
    "name": "Basmati Rice (Cooked)",
    "normalizedName": "basmati rice cooked",
    "category": "Carbohydrates",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 121,
    "protein": 3.5,
    "carbohydrates": 25.2,
    "fat": 0.4,
    "fiber": 0.6,
    "sugar": 0,
    "sodium": 2,
    "source": "USDA",
    "sourceId": "fdc_basmati_rice",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_idli_steamed",
    "name": "Idli (Steamed Rice & Urad Dal Cake)",
    "normalizedName": "idli steamed rice urad dal cake",
    "category": "Indian Foods",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 65,
    "protein": 2,
    "carbohydrates": 13.5,
    "fat": 0.2,
    "fiber": 0.8,
    "sugar": 0.2,
    "sodium": 95,
    "source": "SYSTEM",
    "sourceId": "sys_idli",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_dosa_plain_standard",
    "name": "Plain Dosa",
    "normalizedName": "plain dosa",
    "category": "Indian Foods",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 130,
    "protein": 3,
    "carbohydrates": 18,
    "fat": 5,
    "fiber": 1.2,
    "sugar": 0.3,
    "sodium": 120,
    "source": "SYSTEM",
    "sourceId": "sys_dosa_plain",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_dosa_masala",
    "name": "Masala Dosa (with Potato Filling)",
    "normalizedName": "masala dosa with potato filling",
    "category": "Indian Foods",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 250,
    "protein": 4.8,
    "carbohydrates": 38,
    "fat": 9,
    "fiber": 2.5,
    "sugar": 1,
    "sodium": 240,
    "source": "SYSTEM",
    "sourceId": "sys_masala_dosa",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_dosa_ragi",
    "name": "Ragi Dosa (Finger Millet)",
    "normalizedName": "ragi dosa finger millet",
    "category": "Indian Foods",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 110,
    "protein": 3.2,
    "carbohydrates": 19.5,
    "fat": 2,
    "fiber": 2.8,
    "sugar": 0.2,
    "sodium": 85,
    "source": "SYSTEM",
    "sourceId": "sys_ragi_dosa",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_adai",
    "name": "Adai (High Protein Mixed Lentil Pancake)",
    "normalizedName": "adai high protein mixed lentil pancake",
    "category": "Indian Foods",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 165,
    "protein": 6.5,
    "carbohydrates": 24,
    "fat": 4.5,
    "fiber": 3.5,
    "sugar": 0.4,
    "sodium": 110,
    "source": "SYSTEM",
    "sourceId": "sys_adai",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_pongal_ven",
    "name": "Ven Pongal (Ghee Khichdi Style)",
    "normalizedName": "ven pongal ghee khichdi style",
    "category": "Indian Foods",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 175,
    "protein": 4.2,
    "carbohydrates": 26,
    "fat": 6,
    "fiber": 1.8,
    "sugar": 0.2,
    "sodium": 140,
    "source": "SYSTEM",
    "sourceId": "sys_pongal",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_upma_rava",
    "name": "Rava Upma (Semolina)",
    "normalizedName": "rava upma semolina",
    "category": "Indian Foods",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 135,
    "protein": 3.1,
    "carbohydrates": 22,
    "fat": 3.8,
    "fiber": 1.5,
    "sugar": 0.5,
    "sodium": 130,
    "source": "SYSTEM",
    "sourceId": "sys_upma",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_appam",
    "name": "Appam (Fermented Rice Pancake)",
    "normalizedName": "appam fermented rice pancake",
    "category": "Indian Foods",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 105,
    "protein": 1.8,
    "carbohydrates": 21,
    "fat": 1.5,
    "fiber": 0.8,
    "sugar": 1.5,
    "sodium": 60,
    "source": "SYSTEM",
    "sourceId": "sys_appam",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_idiyappam",
    "name": "Idiyappam / String Hoppers",
    "normalizedName": "idiyappam string hoppers",
    "category": "Indian Foods",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 120,
    "protein": 2.1,
    "carbohydrates": 26.5,
    "fat": 0.3,
    "fiber": 0.7,
    "sugar": 0.1,
    "sodium": 40,
    "source": "SYSTEM",
    "sourceId": "sys_idiyappam",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_puttu",
    "name": "Puttu (Steamed Rice Flour & Coconut)",
    "normalizedName": "puttu steamed rice flour coconut",
    "category": "Indian Foods",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 180,
    "protein": 3.5,
    "carbohydrates": 34,
    "fat": 3,
    "fiber": 2.5,
    "sugar": 1,
    "sodium": 50,
    "source": "SYSTEM",
    "sourceId": "sys_puttu",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_chapati_wheat",
    "name": "Chapati / Whole Wheat Roti",
    "normalizedName": "chapati whole wheat roti",
    "category": "Indian Foods",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 105,
    "protein": 3.5,
    "carbohydrates": 19,
    "fat": 1.5,
    "fiber": 2.8,
    "sugar": 0.3,
    "sodium": 90,
    "source": "SYSTEM",
    "sourceId": "sys_chapati",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_parotta_malabar",
    "name": "Malabar Parotta (Layered Flatbread)",
    "normalizedName": "malabar parotta layered flatbread",
    "category": "Indian Foods",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 260,
    "protein": 5.5,
    "carbohydrates": 39,
    "fat": 9,
    "fiber": 1.5,
    "sugar": 1,
    "sodium": 210,
    "source": "SYSTEM",
    "sourceId": "sys_parotta",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_curd_rice",
    "name": "Curd Rice (Thayir Sadam)",
    "normalizedName": "curd rice thayir sadam",
    "category": "Indian Foods",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 125,
    "protein": 3.2,
    "carbohydrates": 19.5,
    "fat": 3.6,
    "fiber": 0.6,
    "sugar": 2,
    "sodium": 120,
    "source": "SYSTEM",
    "sourceId": "sys_curd_rice",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_lemon_rice",
    "name": "Lemon Rice (Chitranna)",
    "normalizedName": "lemon rice chitranna",
    "category": "Indian Foods",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 155,
    "protein": 2.8,
    "carbohydrates": 25.5,
    "fat": 4.8,
    "fiber": 1.2,
    "sugar": 0.4,
    "sodium": 135,
    "source": "SYSTEM",
    "sourceId": "sys_lemon_rice",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_tomato_rice",
    "name": "Tomato Rice (Thakkali Sadam)",
    "normalizedName": "tomato rice thakkali sadam",
    "category": "Indian Foods",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 148,
    "protein": 2.6,
    "carbohydrates": 24.5,
    "fat": 4.3,
    "fiber": 1.4,
    "sugar": 1.2,
    "sodium": 145,
    "source": "SYSTEM",
    "sourceId": "sys_tomato_rice",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_sambar_south_indian",
    "name": "South Indian Sambar (Lentil & Vegetable Stew)",
    "normalizedName": "south indian sambar lentil vegetable stew",
    "category": "Indian Foods",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 75,
    "protein": 3.5,
    "carbohydrates": 11.5,
    "fat": 1.6,
    "fiber": 2.5,
    "sugar": 2,
    "sodium": 210,
    "source": "SYSTEM",
    "sourceId": "sys_sambar",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_rasam_traditional",
    "name": "Traditional Rasam",
    "normalizedName": "traditional rasam",
    "category": "Indian Foods",
    "servingSize": 100,
    "servingUnit": "ml",
    "calories": 35,
    "protein": 1.2,
    "carbohydrates": 5.5,
    "fat": 0.8,
    "fiber": 0.6,
    "sugar": 1,
    "sodium": 180,
    "source": "SYSTEM",
    "sourceId": "sys_rasam",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_toor_dal_cooked",
    "name": "Toor Dal (Cooked Yellow Pigeon Peas)",
    "normalizedName": "toor dal cooked yellow pigeon peas",
    "category": "Legumes",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 118,
    "protein": 7.2,
    "carbohydrates": 19.8,
    "fat": 0.8,
    "fiber": 4.8,
    "sugar": 1.2,
    "sodium": 8,
    "source": "USDA",
    "sourceId": "fdc_toor_dal",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_moong_dal_cooked",
    "name": "Moong Dal (Cooked Yellow/Green Split)",
    "normalizedName": "moong dal cooked yellow green split",
    "category": "Legumes",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 105,
    "protein": 7,
    "carbohydrates": 18.5,
    "fat": 0.4,
    "fiber": 5.2,
    "sugar": 1,
    "sodium": 6,
    "source": "USDA",
    "sourceId": "fdc_moong_dal",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_masoor_dal_cooked",
    "name": "Masoor Dal (Cooked Red Lentils)",
    "normalizedName": "masoor dal cooked red lentils",
    "category": "Legumes",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 116,
    "protein": 9,
    "carbohydrates": 19.5,
    "fat": 0.4,
    "fiber": 4,
    "sugar": 1.1,
    "sodium": 5,
    "source": "USDA",
    "sourceId": "fdc_172421",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_urad_dal_cooked",
    "name": "Urad Dal (Cooked Black Gram)",
    "normalizedName": "urad dal cooked black gram",
    "category": "Legumes",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 115,
    "protein": 7.5,
    "carbohydrates": 19,
    "fat": 0.6,
    "fiber": 5,
    "sugar": 0.8,
    "sodium": 7,
    "source": "USDA",
    "sourceId": "fdc_urad_dal",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_chana_dal_cooked",
    "name": "Chana Dal (Cooked Bengal Gram)",
    "normalizedName": "chana dal cooked bengal gram",
    "category": "Legumes",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 130,
    "protein": 8,
    "carbohydrates": 22,
    "fat": 1.2,
    "fiber": 6,
    "sugar": 1.5,
    "sodium": 9,
    "source": "USDA",
    "sourceId": "fdc_chana_dal",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_chickpeas_cooked",
    "name": "Chickpeas / Garbanzo / White Chana (Boiled)",
    "normalizedName": "chickpeas garbanzo white chana boiled",
    "category": "Legumes",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 164,
    "protein": 8.9,
    "carbohydrates": 27.4,
    "fat": 2.6,
    "fiber": 7.6,
    "sugar": 4.8,
    "sodium": 7,
    "source": "USDA",
    "sourceId": "fdc_173757",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_rajma_cooked",
    "name": "Rajma / Red Kidney Beans (Boiled)",
    "normalizedName": "rajma red kidney beans boiled",
    "category": "Legumes",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 127,
    "protein": 8.7,
    "carbohydrates": 22.8,
    "fat": 0.5,
    "fiber": 6.4,
    "sugar": 0.3,
    "sodium": 2,
    "source": "USDA",
    "sourceId": "fdc_173744",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_black_beans_cooked",
    "name": "Black Beans (Cooked)",
    "normalizedName": "black beans cooked",
    "category": "Legumes",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 132,
    "protein": 8.9,
    "carbohydrates": 23.7,
    "fat": 0.5,
    "fiber": 8.7,
    "sugar": 0.3,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_173735",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_green_gram_sprouted",
    "name": "Sprouted Green Gram (Moong Sprouts)",
    "normalizedName": "sprouted green gram moong sprouts",
    "category": "Legumes",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 30,
    "protein": 3.1,
    "carbohydrates": 5.9,
    "fat": 0.2,
    "fiber": 1.8,
    "sugar": 4.1,
    "sodium": 6,
    "source": "USDA",
    "sourceId": "fdc_169379",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_peanuts_boiled",
    "name": "Boiled Peanuts",
    "normalizedName": "boiled peanuts",
    "category": "Legumes",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 318,
    "protein": 13.5,
    "carbohydrates": 21.3,
    "fat": 22,
    "fiber": 8.8,
    "sugar": 2.4,
    "sodium": 213,
    "source": "USDA",
    "sourceId": "fdc_170179",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_potato_boiled",
    "name": "Potato (Boiled without skin)",
    "normalizedName": "potato boiled without skin",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 87,
    "protein": 1.9,
    "carbohydrates": 20.1,
    "fat": 0.1,
    "fiber": 1.8,
    "sugar": 0.9,
    "sodium": 4,
    "source": "USDA",
    "sourceId": "fdc_170028",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_sweet_potato_baked",
    "name": "Sweet Potato (Baked / Boiled)",
    "normalizedName": "sweet potato baked boiled",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 90,
    "protein": 2,
    "carbohydrates": 20.7,
    "fat": 0.2,
    "fiber": 3.3,
    "sugar": 6.5,
    "sodium": 36,
    "source": "USDA",
    "sourceId": "fdc_168483",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_carrot_raw",
    "name": "Carrot (Raw/Steamed)",
    "normalizedName": "carrot raw steamed",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 41,
    "protein": 0.9,
    "carbohydrates": 9.6,
    "fat": 0.2,
    "fiber": 2.8,
    "sugar": 4.7,
    "sodium": 69,
    "source": "USDA",
    "sourceId": "fdc_170393",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_green_beans",
    "name": "Green French Beans (Cooked)",
    "normalizedName": "green french beans cooked",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 35,
    "protein": 1.9,
    "carbohydrates": 7.9,
    "fat": 0.3,
    "fiber": 3.2,
    "sugar": 1.9,
    "sodium": 6,
    "source": "USDA",
    "sourceId": "fdc_170404",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_beetroot_boiled",
    "name": "Beetroot (Boiled)",
    "normalizedName": "beetroot boiled",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 44,
    "protein": 1.7,
    "carbohydrates": 10,
    "fat": 0.2,
    "fiber": 2,
    "sugar": 8,
    "sodium": 77,
    "source": "USDA",
    "sourceId": "fdc_169976",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_broccoli_steamed",
    "name": "Broccoli (Steamed/Boiled)",
    "normalizedName": "broccoli steamed boiled",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 35,
    "protein": 2.4,
    "carbohydrates": 7.2,
    "fat": 0.4,
    "fiber": 3.3,
    "sugar": 1.4,
    "sodium": 41,
    "source": "USDA",
    "sourceId": "fdc_170379",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_cauliflower_cooked",
    "name": "Cauliflower (Cooked)",
    "normalizedName": "cauliflower cooked",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 23,
    "protein": 1.8,
    "carbohydrates": 4.1,
    "fat": 0.5,
    "fiber": 2.3,
    "sugar": 2.1,
    "sodium": 15,
    "source": "USDA",
    "sourceId": "fdc_169987",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_spinach_cooked",
    "name": "Spinach / Palak (Cooked)",
    "normalizedName": "spinach palak cooked",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 23,
    "protein": 3,
    "carbohydrates": 3.8,
    "fat": 0.3,
    "fiber": 2.4,
    "sugar": 0.4,
    "sodium": 70,
    "source": "USDA",
    "sourceId": "fdc_169962",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_cabbage_cooked",
    "name": "Cabbage (Cooked/Shredded)",
    "normalizedName": "cabbage cooked shredded",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 23,
    "protein": 1.3,
    "carbohydrates": 5.5,
    "fat": 0.1,
    "fiber": 1.9,
    "sugar": 2.8,
    "sodium": 16,
    "source": "USDA",
    "sourceId": "fdc_169975",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_capsicum_bell_pepper",
    "name": "Capsicum / Bell Pepper (Green/Red)",
    "normalizedName": "capsicum bell pepper green red",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 26,
    "protein": 1,
    "carbohydrates": 6,
    "fat": 0.3,
    "fiber": 2.1,
    "sugar": 4.2,
    "sodium": 4,
    "source": "USDA",
    "sourceId": "fdc_170108",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_tomato_raw",
    "name": "Tomato (Fresh Red)",
    "normalizedName": "tomato fresh red",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 18,
    "protein": 0.9,
    "carbohydrates": 3.9,
    "fat": 0.2,
    "fiber": 1.2,
    "sugar": 2.6,
    "sodium": 5,
    "source": "USDA",
    "sourceId": "fdc_170457",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_cucumber_raw",
    "name": "Cucumber (with Peel)",
    "normalizedName": "cucumber with peel",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 15,
    "protein": 0.7,
    "carbohydrates": 3.6,
    "fat": 0.1,
    "fiber": 0.5,
    "sugar": 1.7,
    "sodium": 2,
    "source": "USDA",
    "sourceId": "fdc_169225",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_onion_raw",
    "name": "Onion (Raw/Cooked)",
    "normalizedName": "onion raw cooked",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 40,
    "protein": 1.1,
    "carbohydrates": 9.3,
    "fat": 0.1,
    "fiber": 1.7,
    "sugar": 4.2,
    "sodium": 4,
    "source": "USDA",
    "sourceId": "fdc_170000",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_brinjal_eggplant",
    "name": "Brinjal / Eggplant (Cooked)",
    "normalizedName": "brinjal eggplant cooked",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 25,
    "protein": 1,
    "carbohydrates": 5.9,
    "fat": 0.2,
    "fiber": 3,
    "sugar": 3.2,
    "sodium": 2,
    "source": "USDA",
    "sourceId": "fdc_169229",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_ladies_finger_okra",
    "name": "Ladies Finger / Okra / Bhindi (Cooked)",
    "normalizedName": "ladies finger okra bhindi cooked",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 33,
    "protein": 1.9,
    "carbohydrates": 7.5,
    "fat": 0.2,
    "fiber": 3.2,
    "sugar": 1.5,
    "sodium": 7,
    "source": "USDA",
    "sourceId": "fdc_169260",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_pumpkin_cooked",
    "name": "Pumpkin (Cooked)",
    "normalizedName": "pumpkin cooked",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 26,
    "protein": 1,
    "carbohydrates": 6.5,
    "fat": 0.1,
    "fiber": 0.5,
    "sugar": 2.8,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_169266",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_bottle_gourd_lauki",
    "name": "Bottle Gourd / Lauki / Sorakaya (Cooked)",
    "normalizedName": "bottle gourd lauki sorakaya cooked",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 14,
    "protein": 0.6,
    "carbohydrates": 3.4,
    "fat": 0.1,
    "fiber": 1.2,
    "sugar": 1.5,
    "sodium": 3,
    "source": "USDA",
    "sourceId": "fdc_bottle_gourd",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_bitter_gourd_karela",
    "name": "Bitter Gourd / Karela (Cooked)",
    "normalizedName": "bitter gourd karela cooked",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 19,
    "protein": 1,
    "carbohydrates": 4.3,
    "fat": 0.2,
    "fiber": 2,
    "sugar": 1.9,
    "sodium": 5,
    "source": "USDA",
    "sourceId": "fdc_bitter_gourd",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_drumstick_moringa",
    "name": "Drumstick Pods / Murungakkai (Boiled)",
    "normalizedName": "drumstick pods murungakkai boiled",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 37,
    "protein": 2.1,
    "carbohydrates": 8.5,
    "fat": 0.2,
    "fiber": 3.2,
    "sugar": 2,
    "sodium": 9,
    "source": "USDA",
    "sourceId": "fdc_drumstick",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_green_peas_boiled",
    "name": "Green Peas (Boiled)",
    "normalizedName": "green peas boiled",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 81,
    "protein": 5.4,
    "carbohydrates": 14.5,
    "fat": 0.4,
    "fiber": 5.7,
    "sugar": 5.7,
    "sodium": 5,
    "source": "USDA",
    "sourceId": "fdc_170419",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_mushrooms_button",
    "name": "White Button Mushrooms (Raw/Cooked)",
    "normalizedName": "white button mushrooms raw cooked",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 22,
    "protein": 3.1,
    "carbohydrates": 3.3,
    "fat": 0.3,
    "fiber": 1,
    "sugar": 2,
    "sodium": 5,
    "source": "USDA",
    "sourceId": "fdc_169251",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_sweet_corn_boiled",
    "name": "Sweet Corn (Boiled Yellow Kernels)",
    "normalizedName": "sweet corn boiled yellow kernels",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 96,
    "protein": 3.4,
    "carbohydrates": 21,
    "fat": 1.5,
    "fiber": 2.4,
    "sugar": 4.5,
    "sodium": 15,
    "source": "USDA",
    "sourceId": "fdc_169999",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_banana_ripe",
    "name": "Banana (Medium Ripe)",
    "normalizedName": "banana medium ripe",
    "category": "Fruits",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 105,
    "protein": 1.3,
    "carbohydrates": 27,
    "fat": 0.3,
    "fiber": 3.1,
    "sugar": 14.4,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_173944",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_apple_fuji",
    "name": "Apple (Medium with Peel)",
    "normalizedName": "apple medium with peel",
    "category": "Fruits",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 95,
    "protein": 0.5,
    "carbohydrates": 25,
    "fat": 0.3,
    "fiber": 4.4,
    "sugar": 19,
    "sodium": 2,
    "source": "USDA",
    "sourceId": "fdc_171688",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_orange_fresh",
    "name": "Orange (Fresh Whole)",
    "normalizedName": "orange fresh whole",
    "category": "Fruits",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 62,
    "protein": 1.2,
    "carbohydrates": 15.4,
    "fat": 0.2,
    "fiber": 3.1,
    "sugar": 12.2,
    "sodium": 0,
    "source": "USDA",
    "sourceId": "fdc_169097",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_grapes_red_green",
    "name": "Grapes (Red / Green Seedless)",
    "normalizedName": "grapes red green seedless",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 69,
    "protein": 0.7,
    "carbohydrates": 18.1,
    "fat": 0.2,
    "fiber": 0.9,
    "sugar": 15.5,
    "sodium": 2,
    "source": "USDA",
    "sourceId": "fdc_174682",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_mango_ripe",
    "name": "Mango (Ripe Slices)",
    "normalizedName": "mango ripe slices",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 60,
    "protein": 0.8,
    "carbohydrates": 15,
    "fat": 0.4,
    "fiber": 1.6,
    "sugar": 13.7,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_169910",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_papaya_cubes",
    "name": "Papaya (Fresh Cubes)",
    "normalizedName": "papaya fresh cubes",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 43,
    "protein": 0.5,
    "carbohydrates": 10.8,
    "fat": 0.3,
    "fiber": 1.7,
    "sugar": 7.8,
    "sodium": 8,
    "source": "USDA",
    "sourceId": "fdc_171726",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_pineapple_fresh",
    "name": "Pineapple (Fresh Chunks)",
    "normalizedName": "pineapple fresh chunks",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 50,
    "protein": 0.5,
    "carbohydrates": 13.1,
    "fat": 0.1,
    "fiber": 1.4,
    "sugar": 9.9,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_169124",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_watermelon_cubes",
    "name": "Watermelon (Diced)",
    "normalizedName": "watermelon diced",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 30,
    "protein": 0.6,
    "carbohydrates": 7.6,
    "fat": 0.2,
    "fiber": 0.4,
    "sugar": 6.2,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_167765",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_muskmelon_cantaloupe",
    "name": "Muskmelon / Cantaloupe",
    "normalizedName": "muskmelon cantaloupe",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 34,
    "protein": 0.8,
    "carbohydrates": 8.2,
    "fat": 0.2,
    "fiber": 0.9,
    "sugar": 7.9,
    "sodium": 16,
    "source": "USDA",
    "sourceId": "fdc_169106",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_guava_fresh",
    "name": "Guava (Fresh Whole)",
    "normalizedName": "guava fresh whole",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 68,
    "protein": 2.6,
    "carbohydrates": 14.3,
    "fat": 1,
    "fiber": 5.4,
    "sugar": 8.9,
    "sodium": 2,
    "source": "USDA",
    "sourceId": "fdc_173044",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_pomegranate_arils",
    "name": "Pomegranate Seeds / Arils",
    "normalizedName": "pomegranate seeds arils",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 83,
    "protein": 1.7,
    "carbohydrates": 18.7,
    "fat": 1.2,
    "fiber": 4,
    "sugar": 13.7,
    "sodium": 3,
    "source": "USDA",
    "sourceId": "fdc_169134",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_kiwi_fruit",
    "name": "Kiwi Fruit (Fresh Green)",
    "normalizedName": "kiwi fruit fresh green",
    "category": "Fruits",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 42,
    "protein": 0.8,
    "carbohydrates": 10.1,
    "fat": 0.4,
    "fiber": 2.1,
    "sugar": 6.2,
    "sodium": 2,
    "source": "USDA",
    "sourceId": "fdc_168153",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_strawberries_fresh",
    "name": "Strawberries (Fresh)",
    "normalizedName": "strawberries fresh",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 32,
    "protein": 0.7,
    "carbohydrates": 7.7,
    "fat": 0.3,
    "fiber": 2,
    "sugar": 4.9,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_167762",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_blueberries_fresh",
    "name": "Blueberries (Fresh)",
    "normalizedName": "blueberries fresh",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 57,
    "protein": 0.7,
    "carbohydrates": 14.5,
    "fat": 0.3,
    "fiber": 2.4,
    "sugar": 10,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_171711",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_dates_medjool",
    "name": "Medjool Dates (Pitted)",
    "normalizedName": "medjool dates pitted",
    "category": "Fruits",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 66,
    "protein": 0.4,
    "carbohydrates": 18,
    "fat": 0,
    "fiber": 1.6,
    "sugar": 16,
    "sodium": 0,
    "source": "USDA",
    "sourceId": "fdc_168191",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_figs_fresh",
    "name": "Figs / Anjeer (Fresh or Dried)",
    "normalizedName": "figs anjeer fresh or dried",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 74,
    "protein": 0.8,
    "carbohydrates": 19.2,
    "fat": 0.3,
    "fiber": 2.9,
    "sugar": 16.3,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_173024",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_coconut_grated",
    "name": "Fresh Coconut Meat (Grated)",
    "normalizedName": "fresh coconut meat grated",
    "category": "Nuts & Seeds",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 354,
    "protein": 3.3,
    "carbohydrates": 15.2,
    "fat": 33.5,
    "fiber": 9,
    "sugar": 6.2,
    "sodium": 20,
    "source": "USDA",
    "sourceId": "fdc_170169",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_avocado_hass",
    "name": "Avocado (Hass, Fresh)",
    "normalizedName": "avocado hass fresh",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 160,
    "protein": 2,
    "carbohydrates": 8.5,
    "fat": 14.7,
    "fiber": 6.7,
    "sugar": 0.7,
    "sodium": 7,
    "source": "USDA",
    "sourceId": "fdc_171705",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_almonds_raw",
    "name": "Almonds (Raw / Roasted)",
    "normalizedName": "almonds raw roasted",
    "category": "Nuts & Seeds",
    "servingSize": 30,
    "servingUnit": "grams",
    "calories": 175,
    "protein": 6.3,
    "carbohydrates": 6.1,
    "fat": 15,
    "fiber": 3.5,
    "sugar": 1.3,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_170567",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_cashews_raw",
    "name": "Cashews (Dry Roasted/Raw)",
    "normalizedName": "cashews dry roasted raw",
    "category": "Nuts & Seeds",
    "servingSize": 30,
    "servingUnit": "grams",
    "calories": 165,
    "protein": 5.2,
    "carbohydrates": 9,
    "fat": 13,
    "fiber": 1,
    "sugar": 1.7,
    "sodium": 4,
    "source": "USDA",
    "sourceId": "fdc_170162",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_walnuts_halves",
    "name": "Walnuts (Raw Halves)",
    "normalizedName": "walnuts raw halves",
    "category": "Nuts & Seeds",
    "servingSize": 30,
    "servingUnit": "grams",
    "calories": 196,
    "protein": 4.6,
    "carbohydrates": 4.1,
    "fat": 19.6,
    "fiber": 2,
    "sugar": 0.8,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_170187",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_pistachios_shelled",
    "name": "Pistachios (Shelled, Roasted)",
    "normalizedName": "pistachios shelled roasted",
    "category": "Nuts & Seeds",
    "servingSize": 30,
    "servingUnit": "grams",
    "calories": 168,
    "protein": 6,
    "carbohydrates": 8.4,
    "fat": 13.5,
    "fiber": 3.1,
    "sugar": 2.3,
    "sodium": 2,
    "source": "USDA",
    "sourceId": "fdc_170184",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_peanut_butter_pure",
    "name": "Natural Peanut Butter (No Sugar Added)",
    "normalizedName": "natural peanut butter no sugar added",
    "category": "Nuts & Seeds",
    "servingSize": 1,
    "servingUnit": "tablespoon",
    "calories": 95,
    "protein": 4,
    "carbohydrates": 3.5,
    "fat": 8,
    "fiber": 1,
    "sugar": 1,
    "sodium": 5,
    "source": "USDA",
    "sourceId": "fdc_172473",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_almond_butter",
    "name": "Almond Butter (Creamy)",
    "normalizedName": "almond butter creamy",
    "category": "Nuts & Seeds",
    "servingSize": 1,
    "servingUnit": "tablespoon",
    "calories": 98,
    "protein": 3.4,
    "carbohydrates": 3,
    "fat": 8.9,
    "fiber": 1.6,
    "sugar": 0.7,
    "sodium": 2,
    "source": "USDA",
    "sourceId": "fdc_173815",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_chia_seeds",
    "name": "Chia Seeds (Raw)",
    "normalizedName": "chia seeds raw",
    "category": "Nuts & Seeds",
    "servingSize": 1,
    "servingUnit": "tablespoon",
    "calories": 60,
    "protein": 2,
    "carbohydrates": 5,
    "fat": 4,
    "fiber": 4.1,
    "sugar": 0,
    "sodium": 2,
    "source": "USDA",
    "sourceId": "fdc_170554",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_flax_seeds_ground",
    "name": "Flax Seeds (Ground / Meal)",
    "normalizedName": "flax seeds ground meal",
    "category": "Nuts & Seeds",
    "servingSize": 1,
    "servingUnit": "tablespoon",
    "calories": 55,
    "protein": 1.9,
    "carbohydrates": 3,
    "fat": 4.3,
    "fiber": 2.8,
    "sugar": 0.2,
    "sodium": 3,
    "source": "USDA",
    "sourceId": "fdc_169414",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_pumpkin_seeds_pepitas",
    "name": "Pumpkin Seeds / Pepitas (Raw/Roasted)",
    "normalizedName": "pumpkin seeds pepitas raw roasted",
    "category": "Nuts & Seeds",
    "servingSize": 30,
    "servingUnit": "grams",
    "calories": 170,
    "protein": 9,
    "carbohydrates": 4.2,
    "fat": 14,
    "fiber": 1.9,
    "sugar": 0.4,
    "sodium": 2,
    "source": "USDA",
    "sourceId": "fdc_170556",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_sunflower_seeds",
    "name": "Sunflower Seed Kernels (Roasted)",
    "normalizedName": "sunflower seed kernels roasted",
    "category": "Nuts & Seeds",
    "servingSize": 30,
    "servingUnit": "grams",
    "calories": 175,
    "protein": 5.8,
    "carbohydrates": 6.5,
    "fat": 15.5,
    "fiber": 3,
    "sugar": 0.8,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_170562",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_sesame_seeds",
    "name": "Sesame Seeds (Whole, Dried)",
    "normalizedName": "sesame seeds whole dried",
    "category": "Nuts & Seeds",
    "servingSize": 1,
    "servingUnit": "tablespoon",
    "calories": 52,
    "protein": 1.6,
    "carbohydrates": 2.1,
    "fat": 4.5,
    "fiber": 1.1,
    "sugar": 0,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_170188",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_oats_rolled",
    "name": "Rolled Oats (Dry)",
    "normalizedName": "rolled oats dry",
    "category": "Grains",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 389,
    "protein": 16.9,
    "carbohydrates": 66.3,
    "fat": 6.9,
    "fiber": 10.6,
    "sugar": 0,
    "sodium": 2,
    "source": "USDA",
    "sourceId": "fdc_173904",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_bread_whole_wheat",
    "name": "Whole Wheat Bread",
    "normalizedName": "whole wheat bread",
    "category": "Grains",
    "servingSize": 1,
    "servingUnit": "slice",
    "calories": 82,
    "protein": 4,
    "carbohydrates": 13.8,
    "fat": 1.1,
    "fiber": 2,
    "sugar": 1.5,
    "sodium": 140,
    "source": "USDA",
    "sourceId": "fdc_172688",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_quinoa_cooked",
    "name": "Quinoa (Cooked)",
    "normalizedName": "quinoa cooked",
    "category": "Grains",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 120,
    "protein": 4.4,
    "carbohydrates": 21.3,
    "fat": 1.9,
    "fiber": 2.8,
    "sugar": 0.9,
    "sodium": 7,
    "source": "USDA",
    "sourceId": "fdc_168874",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_olive_oil",
    "name": "Extra Virgin Olive Oil",
    "normalizedName": "extra virgin olive oil",
    "category": "Oils/Fats",
    "servingSize": 1,
    "servingUnit": "tablespoon",
    "calories": 119,
    "protein": 0,
    "carbohydrates": 0,
    "fat": 13.5,
    "fiber": 0,
    "sugar": 0,
    "sodium": 0,
    "source": "USDA",
    "sourceId": "fdc_171413",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_ghee_clarified_butter",
    "name": "Ghee (Pure Clarified Butter)",
    "normalizedName": "ghee pure clarified butter",
    "category": "Oils/Fats",
    "servingSize": 1,
    "servingUnit": "tablespoon",
    "calories": 112,
    "protein": 0,
    "carbohydrates": 0,
    "fat": 12.7,
    "fiber": 0,
    "sugar": 0,
    "sodium": 0,
    "source": "USDA",
    "sourceId": "fdc_171412",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_whey_concentrate",
    "name": "Whey Protein Concentrate (80%)",
    "normalizedName": "whey protein concentrate 80",
    "category": "Protein",
    "servingSize": 30,
    "servingUnit": "grams",
    "calories": 120,
    "protein": 24,
    "carbohydrates": 2.5,
    "fat": 1.8,
    "fiber": 0,
    "sugar": 1.5,
    "sodium": 130,
    "source": "USDA",
    "sourceId": "fdc_whey_conc",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_casein_protein",
    "name": "Micellar Casein Protein",
    "normalizedName": "micellar casein protein",
    "category": "Protein",
    "servingSize": 30,
    "servingUnit": "grams",
    "calories": 110,
    "protein": 24,
    "carbohydrates": 1.5,
    "fat": 0.8,
    "fiber": 0,
    "sugar": 1,
    "sodium": 150,
    "source": "USDA",
    "sourceId": "fdc_casein",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_chicken_tikka",
    "name": "Chicken Tikka (Tandoori Grilled)",
    "normalizedName": "chicken tikka tandoori grilled",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 170,
    "protein": 28,
    "carbohydrates": 2,
    "fat": 5.5,
    "fiber": 0.5,
    "sugar": 0.8,
    "sodium": 320,
    "source": "SYSTEM",
    "sourceId": "sys_tikka",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_egg_bhurji",
    "name": "Egg Bhurji (Indian Scrambled Eggs with Onion & Spices)",
    "normalizedName": "egg bhurji indian scrambled eggs with onion spices",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 155,
    "protein": 11.5,
    "carbohydrates": 3.5,
    "fat": 10.5,
    "fiber": 0.8,
    "sugar": 1.2,
    "sodium": 260,
    "source": "SYSTEM",
    "sourceId": "sys_egg_bhurji",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_paneer_bhurji",
    "name": "Paneer Bhurji (Spiced Scrambled Paneer)",
    "normalizedName": "paneer bhurji spiced scrambled paneer",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 220,
    "protein": 15,
    "carbohydrates": 5,
    "fat": 16,
    "fiber": 1.2,
    "sugar": 2,
    "sodium": 240,
    "source": "SYSTEM",
    "sourceId": "sys_paneer_bhurji",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_poha",
    "name": "Poha (Flattened Rice with Mustard & Peanuts)",
    "normalizedName": "poha flattened rice with mustard peanuts",
    "category": "Indian Foods",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 160,
    "protein": 3.2,
    "carbohydrates": 27,
    "fat": 4.5,
    "fiber": 1.8,
    "sugar": 1,
    "sodium": 150,
    "source": "SYSTEM",
    "sourceId": "sys_poha",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_besan_chilla",
    "name": "Besan Chilla (Gram Flour Savory Pancake)",
    "normalizedName": "besan chilla gram flour savory pancake",
    "category": "Indian Foods",
    "servingSize": 1,
    "servingUnit": "piece",
    "calories": 140,
    "protein": 6.5,
    "carbohydrates": 18,
    "fat": 4.5,
    "fiber": 3.2,
    "sugar": 1,
    "sodium": 160,
    "source": "SYSTEM",
    "sourceId": "sys_besan_chilla",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_khichdi_moong",
    "name": "Moong Dal Khichdi",
    "normalizedName": "moong dal khichdi",
    "category": "Indian Foods",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 135,
    "protein": 4.5,
    "carbohydrates": 23,
    "fat": 3,
    "fiber": 2.2,
    "sugar": 0.5,
    "sodium": 140,
    "source": "SYSTEM",
    "sourceId": "sys_khichdi",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_sattu_drink",
    "name": "Sattu Drink (Roasted Gram Flour with Spices)",
    "normalizedName": "sattu drink roasted gram flour with spices",
    "category": "Beverages",
    "servingSize": 100,
    "servingUnit": "ml",
    "calories": 82,
    "protein": 5.1,
    "carbohydrates": 12,
    "fat": 1.2,
    "fiber": 3,
    "sugar": 0.5,
    "sodium": 110,
    "source": "SYSTEM",
    "sourceId": "sys_sattu",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_coconut_water",
    "name": "Tender Coconut Water (Fresh)",
    "normalizedName": "tender coconut water fresh",
    "category": "Beverages",
    "servingSize": 100,
    "servingUnit": "ml",
    "calories": 19,
    "protein": 0.7,
    "carbohydrates": 3.7,
    "fat": 0.2,
    "fiber": 1.1,
    "sugar": 2.6,
    "sodium": 105,
    "source": "USDA",
    "sourceId": "fdc_170172",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_almond_milk_unsweetened",
    "name": "Almond Milk (Unsweetened)",
    "normalizedName": "almond milk unsweetened",
    "category": "Dairy",
    "servingSize": 100,
    "servingUnit": "ml",
    "calories": 15,
    "protein": 0.6,
    "carbohydrates": 0.3,
    "fat": 1.2,
    "fiber": 0.2,
    "sugar": 0,
    "sodium": 68,
    "source": "USDA",
    "sourceId": "fdc_174832",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_soy_milk_unsweetened",
    "name": "Soy Milk (Unsweetened)",
    "normalizedName": "soy milk unsweetened",
    "category": "Dairy",
    "servingSize": 100,
    "servingUnit": "ml",
    "calories": 33,
    "protein": 2.8,
    "carbohydrates": 1.8,
    "fat": 1.6,
    "fiber": 0.4,
    "sugar": 0.5,
    "sodium": 40,
    "source": "USDA",
    "sourceId": "fdc_172448",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_chicken_leg_cooked",
    "name": "Chicken Leg / Drumstick (Cooked, Skinless)",
    "normalizedName": "chicken leg drumstick cooked skinless",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 172,
    "protein": 24.2,
    "carbohydrates": 0,
    "fat": 8.4,
    "fiber": 0,
    "sugar": 0,
    "sodium": 84,
    "source": "USDA",
    "sourceId": "fdc_171478",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_cooked_white_rice",
    "name": "Cooked White Rice (Basmati / Sona Masoori)",
    "normalizedName": "cooked white rice basmati sona masoori",
    "category": "Indian Foods",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 130,
    "protein": 2.7,
    "carbohydrates": 28.2,
    "fat": 0.3,
    "fiber": 0.4,
    "sugar": 0.1,
    "sodium": 1,
    "source": "USDA",
    "sourceId": "fdc_168878",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_raw_white_rice",
    "name": "Raw White Rice (Dry Grains)",
    "normalizedName": "raw white rice dry grains",
    "category": "Grains",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 365,
    "protein": 7.1,
    "carbohydrates": 80,
    "fat": 0.7,
    "fiber": 1.3,
    "sugar": 0.1,
    "sodium": 5,
    "source": "USDA",
    "sourceId": "fdc_168877",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_sesame_seeds_white",
    "name": "Sesame Seeds (Whole, Dried)",
    "normalizedName": "sesame seeds whole dried",
    "category": "Nuts & Seeds",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 573,
    "protein": 17.7,
    "carbohydrates": 23.4,
    "fat": 49.7,
    "fiber": 11.8,
    "sugar": 0.3,
    "sodium": 11,
    "source": "USDA",
    "sourceId": "fdc_170151",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_almond_butter_pure",
    "name": "Almond Butter (100% Natural, No Added Sugar)",
    "normalizedName": "almond butter natural no added sugar",
    "category": "Nuts & Seeds",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 614,
    "protein": 21,
    "carbohydrates": 18.8,
    "fat": 55.5,
    "fiber": 10.3,
    "sugar": 4.4,
    "sodium": 7,
    "source": "USDA",
    "sourceId": "fdc_172431",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_chia_seeds_black",
    "name": "Chia Seeds (Raw)",
    "normalizedName": "chia seeds raw",
    "category": "Nuts & Seeds",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 486,
    "protein": 16.5,
    "carbohydrates": 42.1,
    "fat": 30.7,
    "fiber": 34.4,
    "sugar": 0,
    "sodium": 16,
    "source": "USDA",
    "sourceId": "fdc_170554",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_low_fat_paneer",
    "name": "Low-Fat Paneer (Fresh Cottage Cheese)",
    "normalizedName": "low fat paneer fresh cottage cheese",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 162,
    "protein": 25,
    "carbohydrates": 3.5,
    "fat": 5.5,
    "fiber": 0,
    "sugar": 2,
    "sodium": 40,
    "source": "SYSTEM",
    "sourceId": "axg_in_lfp",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_tempeh_cooked",
    "name": "Tempeh (Fermented Soy, Steamed/Cooked)",
    "normalizedName": "tempeh fermented soy steamed cooked",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 192,
    "protein": 20.3,
    "carbohydrates": 7.6,
    "fat": 10.8,
    "fiber": 4.8,
    "sugar": 0,
    "sodium": 9,
    "source": "USDA",
    "sourceId": "fdc_172465",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_soy_chunks_cooked",
    "name": "Soy Chunks / Meal-Maker (Boiled/Cooked)",
    "normalizedName": "soy chunks meal maker boiled cooked",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 145,
    "protein": 25.8,
    "carbohydrates": 9.5,
    "fat": 0.5,
    "fiber": 6.2,
    "sugar": 2.1,
    "sodium": 15,
    "source": "SYSTEM",
    "sourceId": "axg_in_sc",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_mackerel_cooked",
    "name": "Atlantic Mackerel (Cooked, Dry Heat)",
    "normalizedName": "atlantic mackerel cooked dry heat",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 262,
    "protein": 23.9,
    "carbohydrates": 0,
    "fat": 17.8,
    "fiber": 0,
    "sugar": 0,
    "sodium": 83,
    "source": "USDA",
    "sourceId": "fdc_175120",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_sardines_canned",
    "name": "Sardines (Canned in Water, Drained)",
    "normalizedName": "sardines canned in water drained",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 208,
    "protein": 24.6,
    "carbohydrates": 0,
    "fat": 11.5,
    "fiber": 0,
    "sugar": 0,
    "sodium": 505,
    "source": "USDA",
    "sourceId": "fdc_175139",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_prawns_shrimp_cooked",
    "name": "Prawns / Shrimp (Steamed/Boiled)",
    "normalizedName": "prawns shrimp steamed boiled",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 99,
    "protein": 24,
    "carbohydrates": 0.2,
    "fat": 0.3,
    "fiber": 0,
    "sugar": 0,
    "sodium": 111,
    "source": "USDA",
    "sourceId": "fdc_175180",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_lean_beef_sirloin",
    "name": "Lean Beef Top Sirloin (Cooked, Trimmed)",
    "normalizedName": "lean beef top sirloin cooked trimmed",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 183,
    "protein": 30.2,
    "carbohydrates": 0,
    "fat": 6.1,
    "fiber": 0,
    "sugar": 0,
    "sodium": 54,
    "source": "USDA",
    "sourceId": "fdc_170273",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_lamb_mutton_cooked",
    "name": "Lamb / Mutton (Lean Cut, Cooked)",
    "normalizedName": "lamb mutton lean cut cooked",
    "category": "Protein",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 216,
    "protein": 28.3,
    "carbohydrates": 0,
    "fat": 10.6,
    "fiber": 0,
    "sugar": 0,
    "sodium": 68,
    "source": "USDA",
    "sourceId": "fdc_172535",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_plain_dosa",
    "name": "Plain Dosa (Crispy Rice & Lentil Crepe)",
    "normalizedName": "plain dosa crispy rice lentil crepe",
    "category": "Indian Foods",
    "servingSize": 90,
    "servingUnit": "1 piece",
    "calories": 168,
    "protein": 3.9,
    "carbohydrates": 28.4,
    "fat": 4.2,
    "fiber": 1.4,
    "sugar": 0.3,
    "sodium": 180,
    "source": "SYSTEM",
    "sourceId": "axg_in_dosa",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_masala_dosa",
    "name": "Masala Dosa (with Potato Masala Filling)",
    "normalizedName": "masala dosa potato masala filling",
    "category": "Indian Foods",
    "servingSize": 160,
    "servingUnit": "1 piece",
    "calories": 285,
    "protein": 5.6,
    "carbohydrates": 42.8,
    "fat": 10.2,
    "fiber": 3.5,
    "sugar": 1.2,
    "sodium": 320,
    "source": "SYSTEM",
    "sourceId": "axg_in_mdosa",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_ragi_dosa",
    "name": "Ragi Dosa (Finger Millet Dosa)",
    "normalizedName": "ragi dosa finger millet dosa",
    "category": "Indian Foods",
    "servingSize": 90,
    "servingUnit": "1 piece",
    "calories": 145,
    "protein": 4.1,
    "carbohydrates": 27.2,
    "fat": 2.3,
    "fiber": 3.8,
    "sugar": 0.2,
    "sodium": 160,
    "source": "SYSTEM",
    "sourceId": "axg_in_ragidosa",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_adai_dosa",
    "name": "Adai (High Protein Multi-Lentil Dosa)",
    "normalizedName": "adai high protein multi lentil dosa",
    "category": "Indian Foods",
    "servingSize": 100,
    "servingUnit": "1 piece",
    "calories": 185,
    "protein": 7.8,
    "carbohydrates": 28.5,
    "fat": 4.5,
    "fiber": 4.2,
    "sugar": 0.5,
    "sodium": 195,
    "source": "SYSTEM",
    "sourceId": "axg_in_adai",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_ven_pongal",
    "name": "Ven Pongal (Rice & Moong Dal Ghee Porridge)",
    "normalizedName": "ven pongal rice moong dal ghee porridge",
    "category": "Indian Foods",
    "servingSize": 150,
    "servingUnit": "1 cup",
    "calories": 242,
    "protein": 5.8,
    "carbohydrates": 36.2,
    "fat": 8.4,
    "fiber": 2.6,
    "sugar": 0.4,
    "sodium": 260,
    "source": "SYSTEM",
    "sourceId": "axg_in_pongal",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_rava_upma",
    "name": "Upma (Semolina / Rava Vegetable Upma)",
    "normalizedName": "upma semolina rava vegetable upma",
    "category": "Indian Foods",
    "servingSize": 150,
    "servingUnit": "1 cup",
    "calories": 198,
    "protein": 4.8,
    "carbohydrates": 32.5,
    "fat": 5.6,
    "fiber": 2.2,
    "sugar": 1.1,
    "sodium": 280,
    "source": "SYSTEM",
    "sourceId": "axg_in_upma",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_kerala_parotta",
    "name": "Parotta (Malabar Layered Flatbread)",
    "normalizedName": "parotta malabar layered flatbread",
    "category": "Indian Foods",
    "servingSize": 85,
    "servingUnit": "1 piece",
    "calories": 275,
    "protein": 5.8,
    "carbohydrates": 41.5,
    "fat": 9.8,
    "fiber": 1.8,
    "sugar": 1.4,
    "sodium": 290,
    "source": "SYSTEM",
    "sourceId": "axg_in_parotta",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_south_indian_sambar",
    "name": "Sambar (Toor Dal & Mixed Vegetable Stew)",
    "normalizedName": "sambar toor dal mixed vegetable stew",
    "category": "Indian Foods",
    "servingSize": 150,
    "servingUnit": "1 cup",
    "calories": 110,
    "protein": 5.2,
    "carbohydrates": 17.5,
    "fat": 2.1,
    "fiber": 4.2,
    "sugar": 3.2,
    "sodium": 380,
    "source": "SYSTEM",
    "sourceId": "axg_in_sambar",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_sprouted_moong",
    "name": "Sprouted Green Gram / Moong (Raw)",
    "normalizedName": "sprouted green gram moong raw",
    "category": "Legumes",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 30,
    "protein": 3.1,
    "carbohydrates": 5.9,
    "fat": 0.2,
    "fiber": 1.8,
    "sugar": 4.1,
    "sodium": 6,
    "source": "USDA",
    "sourceId": "fdc_172430",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_drumstick_moringa_cooked",
    "name": "Drumstick / Moringa Pods (Cooked)",
    "normalizedName": "drumstick moringa pods cooked",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 37,
    "protein": 2.1,
    "carbohydrates": 8.5,
    "fat": 0.2,
    "fiber": 3.2,
    "sugar": 1.4,
    "sodium": 42,
    "source": "USDA",
    "sourceId": "fdc_170425",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_ladies_finger_bhindi",
    "name": "Ladies Finger / Okra / Bhindi (Cooked)",
    "normalizedName": "ladies finger okra bhindi cooked",
    "category": "Vegetables",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 33,
    "protein": 1.9,
    "carbohydrates": 7.5,
    "fat": 0.2,
    "fiber": 3.2,
    "sugar": 1.5,
    "sodium": 7,
    "source": "USDA",
    "sourceId": "fdc_169260",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_kiwi_fresh",
    "name": "Kiwi Fruit (Fresh Green/Gold)",
    "normalizedName": "kiwi fruit fresh green gold",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 61,
    "protein": 1.1,
    "carbohydrates": 14.7,
    "fat": 0.5,
    "fiber": 3,
    "sugar": 9,
    "sodium": 3,
    "source": "USDA",
    "sourceId": "fdc_168153",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_dried_figs_anjeer",
    "name": "Dried Figs / Anjeer",
    "normalizedName": "dried figs anjeer",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 249,
    "protein": 3.3,
    "carbohydrates": 63.9,
    "fat": 0.9,
    "fiber": 9.8,
    "sugar": 47.9,
    "sodium": 10,
    "source": "USDA",
    "sourceId": "fdc_173943",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  },
  {
    "id": "food_coconut_fresh_meat",
    "name": "Coconut Meat (Raw, Fresh)",
    "normalizedName": "coconut meat raw fresh",
    "category": "Fruits",
    "servingSize": 100,
    "servingUnit": "grams",
    "calories": 354,
    "protein": 3.3,
    "carbohydrates": 15.2,
    "fat": 33.5,
    "fiber": 9,
    "sugar": 6.2,
    "sodium": 20,
    "source": "USDA",
    "sourceId": "fdc_170169",
    "isCustom": false,
    "isPublic": true,
    "isVerified": true,
    "status": "APPROVED"
  }
];
