/**
 * Alpha X AI — Autonomous Proactive Push Notification & Check-in Engine
 *
 * Transitions the AI Coach from strictly reactive chat to proactive, personalized guidance:
 *   1. Morning Readiness Check-in (7:30 AM):
 *      "Leg Day today at 6 PM. Drink your water and hit at least 150g protein."
 *   2. Event-Driven Post-Workout Celebration (Immediate upon session finish):
 *      "You hit a personal volume record on Deadlifts (4,200 kg total). Prioritize recovery sleep tonight."
 *   3. Missed Workout Auto-Regulation (10:30 AM):
 *      "You missed yesterday's scheduled session. Should we swap it to today or make it a rest week?"
 *   4. Evening Accountability Sweep (8:30 PM):
 *      Remaining protein/steps gap and recovery advice before sleep.
 *
 * All messages are generated by Gemini with 100% deterministic fallback templates,
 * dispatched to client devices via OneSignal, and recorded in PostgreSQL for the in-app notification center.
 */

import { prisma } from '../../config/prisma';
import { oneSignalService } from './onesignal.service';
import { env } from '../../config/environment';
import { GoogleGenAI } from '@google/genai';

export interface MorningCheckInContext {
  firstName: string;
  sessionTitle: string;
  isTrainingDay: boolean;
  trainingTime: string;
  targetProteinGrams: number;
  targetWaterLiters: number;
  hasInjury: boolean;
}

export interface PostWorkoutContext {
  firstName: string;
  sessionTitle: string;
  durationMinutes: number;
  totalVolumeKg: number;
  completedSetsCount: number;
  prExerciseName?: string;
  prVolumeKg?: number;
  prWeightKg?: number;
  prType?: string;
}

export interface MissedWorkoutContext {
  firstName: string;
  missedSessionTitle: string;
  daysPerWeek: number;
  consecutiveMisses: number;
}

export interface EveningCheckInContext {
  firstName: string;
  workoutDoneToday: boolean;
  stepsToday: number;
  stepGoal: number;
  stepsRemaining: number;
  proteinLoggedToday: number;
  proteinTargetG: number | null;
  proteinRemainingG: number | null;
  proteinPctComplete: number | null;
  hasInjury: boolean;
}

export class AiNotificationEngine {
  private readonly defaultModel = 'gemini-flash-lite-latest';
  private readonly fallbackModels = ['gemini-2.5-flash', 'gemini-2.0-flash', 'gemini-1.5-flash'];

  /**
   * Helper to execute Gemini generation with robust model fallback and timeout.
   */
  private async callGemini(prompt: string, fallbackText: string): Promise<string> {
    const apiKey = env.GEMINI_API_KEY;
    if (!apiKey) {
      return fallbackText;
    }

    const ai = new GoogleGenAI({ apiKey: apiKey.trim() });
    const modelsToTry = [this.defaultModel, ...this.fallbackModels];

    for (const model of modelsToTry) {
      try {
        const response = await ai.models.generateContent({
          model,
          contents: prompt,
        });
        const text = (response.text || '').trim().replace(/^["']|["']$/g, '');
        if (text.length > 0 && text.length <= 180) {
          return text;
        }
      } catch (err: any) {
        console.warn(`[AI NOTIFICATIONS] Model ${model} failed, trying next...:`, err?.message);
      }
    }

    return fallbackText;
  }

  // =========================================================================
  // 1. MORNING READINESS CHECK-IN (7:30 AM)
  // =========================================================================
  async runMorningCheckInSweep(): Promise<{ sent: number; skipped: number }> {
    console.log('[AI NOTIFICATIONS] Starting Morning Readiness Sweep (7:30 AM)...');
    const today = new Date();
    const todayStr = today.toISOString().split('T')[0];
    const todayWeekday = today.getDay() === 0 ? 7 : today.getDay(); // 1=Mon ... 7=Sun

    const clients = await prisma.user.findMany({
      where: {
        role: 'CLIENT',
        oneSignalPlayerId: { not: null },
        notificationsEnabled: true,
      },
      include: {
        clientProfile: {
          include: {
            dietPlans: { where: { isActive: true }, take: 1 },
            notificationPref: true,
          },
        },
        assignments: {
          where: { active: true },
          include: { session: true },
        },
      },
    });

    let sent = 0;
    let skipped = 0;

    for (const client of clients) {
      try {
        const profile = client.clientProfile;
        if (!profile) { skipped++; continue; }

        // Respect notification preference
        if (profile.notificationPref && !profile.notificationPref.workoutReminders) {
          skipped++;
          continue;
        }

        const firstName = client.name.split(' ')[0] || 'Athlete';
        const diet = profile.dietPlans[0];
        const targetProtein = diet?.protein ? Math.round(diet.protein) : 150;
        const targetWater = diet?.waterTargetLiters ? Number(diet.waterTargetLiters.toFixed(1)) : 3.0;
        const timePref = profile.trainingTimePref || '6 PM';

        // Check if today is a scheduled training day
        const assignment = client.assignments.find((a) => a.session && a.active);
        const sessionTitle = assignment?.session?.title || 'Strength & Conditioning';
        const isTrainingDay = profile.trainingDaysPerWeek ? profile.trainingDaysPerWeek >= 3 : true;

        const context: MorningCheckInContext = {
          firstName,
          sessionTitle,
          isTrainingDay,
          trainingTime: timePref,
          targetProteinGrams: targetProtein,
          targetWaterLiters: targetWater,
          hasInjury: profile.hasCurrentInjury,
        };

        const fallback = isTrainingDay
          ? `${sessionTitle} today at ${timePref}. Drink your water and hit at least ${targetProtein}g protein 💧`
          : `Active recovery day, ${firstName}! Hydrate with ${targetWater}L and aim for ${targetProtein}g protein 🧘`;

        const prompt = `You are the Alpha X Gym AI Coach sending an energizing morning push notification to gym member ${firstName}.
Context for today:
- Scheduled session: "${sessionTitle}"
- Planned training time: ${timePref}
- Target protein: ${targetProtein}g
- Target water: ${targetWater}L
- Injury status: ${profile.hasCurrentInjury ? 'Minor recovery/injury' : 'Fit'}

Write ONE short, punchy message (max 110 characters). Rules:
- Address the client naturally or dive straight into the cue
- Exact tone target: "Leg Day today at 6 PM. Drink your water and hit at least 150g protein."
- Do NOT use hashtags, quotes, or markdown asterisks
- End with one relevant emoji (e.g. 💧, 💪, 🏋️)
Reply with ONLY the notification text.`;

        const message = await this.callGemini(prompt, fallback);

        // Send push via OneSignal
        await oneSignalService.sendToPlayer(client.oneSignalPlayerId!, {
          title: '⚡ Alpha X Morning Briefing',
          body: message,
          data: { type: 'morning_checkin', date: todayStr },
        });

        // Record in in-app notification center
        await prisma.notification.create({
          data: {
            clientProfileId: profile.id,
            clientId: profile.clientId || null,
            title: '⚡ Morning Briefing',
            message,
            type: 'WORKOUT',
            category: 'TRAINING',
            source: 'AI_COACH',
            triggerRule: 'MORNING_READINESS',
            sentStatus: 'SENT',
            metadataJson: JSON.stringify({ sessionTitle, targetProtein, targetWater, timePref }),
          },
        });

        sent++;
      } catch (err: any) {
        console.error(`[AI NOTIFICATIONS] Morning check-in error for ${client.name}:`, err?.message);
        skipped++;
      }
    }

    console.log(`[AI NOTIFICATIONS] Morning sweep complete: ${sent} sent, ${skipped} skipped.`);
    return { sent, skipped };
  }

  // =========================================================================
  // 2. EVENT-DRIVEN POST-WORKOUT CELEBRATION (Triggered on workout completion)
  // =========================================================================
  async sendPostWorkoutCelebration(clientId: string, record: any): Promise<boolean> {
    try {
      const user = await prisma.user.findUnique({
        where: { id: clientId },
        include: {
          clientProfile: {
            include: { notificationPref: true },
          },
        },
      });

      if (!user || !user.notificationsEnabled || !user.oneSignalPlayerId) {
        return false;
      }

      if (user.clientProfile?.notificationPref && !user.clientProfile.notificationPref.workoutReminders) {
        return false;
      }

      const firstName = user.name.split(' ')[0] || 'Athlete';
      const sessionTitle = record.sessionTitle || 'Workout Session';
      const durationMin = Math.round((record.durationSeconds || 2400) / 60);
      const totalVolumeKg = Math.round(record.totalVolume || 0);
      const completedSets = record.completedSetsCount || 0;

      // Extract PR information if present
      let prExerciseName: string | undefined;
      let prVolumeKg: number | undefined;
      let prWeightKg: number | undefined;
      let prType: string | undefined;

      if (record.personalRecords && Array.isArray(record.personalRecords) && record.personalRecords.length > 0) {
        const topPr = record.personalRecords[0];
        prExerciseName = topPr.exerciseName || 'Compound Lift';
        prWeightKg = topPr.weight;
        prVolumeKg = topPr.value;
        prType = topPr.type;
      } else if (record.personalRecordsJson) {
        try {
          const prs = JSON.parse(record.personalRecordsJson);
          if (Array.isArray(prs) && prs.length > 0) {
            prExerciseName = prs[0].exerciseName;
            prWeightKg = prs[0].weight;
            prVolumeKg = prs[0].value;
          }
        } catch (_) {}
      }

      // If no PR was tagged but high volume was moved on a compound movement, highlight it
      if (!prExerciseName && record.exerciseRecords && Array.isArray(record.exerciseRecords) && record.exerciseRecords.length > 0) {
        const firstEx = record.exerciseRecords[0];
        prExerciseName = firstEx.exerciseName || 'Main Lift';
        prVolumeKg = totalVolumeKg;
      }

      const hasPR = Boolean(prExerciseName && totalVolumeKg > 0);
      const fallback = hasPR
        ? `You hit a personal volume record on ${prExerciseName} (${totalVolumeKg.toLocaleString()} kg total). Prioritize recovery sleep tonight 🏆`
        : `Outstanding session! Crushed ${totalVolumeKg.toLocaleString()} kg volume across ${completedSets} sets. Fuel up with 35g protein within the hour 🔥`;

      const prompt = `You are the Alpha X Gym AI Coach sending an immediate post-workout push notification to gym member ${firstName}.
Workout stats just completed:
- Session: "${sessionTitle}" (${durationMin} min, ${completedSets} sets)
- Total volume: ${totalVolumeKg} kg
- Best lift / PR: ${prExerciseName ? `${prExerciseName} (${totalVolumeKg} kg volume)` : 'Standard completion'}

Write ONE short, high-energy notification message (max 115 characters). Rules:
- Congratulate them on the specific volume or PR achieved
- Give one immediate actionable recovery instruction (e.g. sleep, post-workout protein)
- Tone target: "You hit a personal volume record on Deadlifts (4,200 kg total). Prioritize recovery sleep tonight."
- Do NOT use hashtags, quotes, or markdown asterisks
- End with one relevant emoji (🏆, 🥩, 🔥)
Reply with ONLY the notification text.`;

      const message = await this.callGemini(prompt, fallback);

      // Send OneSignal push
      await oneSignalService.sendToPlayer(user.oneSignalPlayerId, {
        title: hasPR ? '🏆 NEW PR ACHIEVED!' : '🔥 WORKOUT CRUSHED!',
        body: message,
        data: { type: 'post_workout', recordId: record.id || '' },
      });

      // Save to database notification center
      if (user.clientProfile?.id) {
        await prisma.notification.create({
          data: {
            clientProfileId: user.clientProfile.id,
            clientId: user.clientProfile.clientId || null,
            title: hasPR ? '🏆 New Personal Record' : '🔥 Workout Completed',
            message,
            type: 'WORKOUT',
            category: 'ACHIEVEMENT',
            source: 'AI_COACH',
            triggerRule: 'WORKOUT_COMPLETED',
            sentStatus: 'SENT',
            metadataJson: JSON.stringify({ sessionTitle, totalVolumeKg, durationMin, prExerciseName }),
          },
        });
      }

      console.log(`[AI NOTIFICATIONS] ✅ Dispatched post-workout celebration to ${user.name}`);
      return true;
    } catch (err: any) {
      console.error('[AI NOTIFICATIONS] Failed to send post-workout celebration:', err?.message);
      return false;
    }
  }

  // =========================================================================
  // 3. MISSED WORKOUT AUTO-REGULATION (10:30 AM)
  // =========================================================================
  async runMissedWorkoutSweep(): Promise<{ sent: number; skipped: number }> {
    console.log('[AI NOTIFICATIONS] Starting Missed Workout Auto-Regulation Sweep (10:30 AM)...');
    const now = new Date();
    const thirtySixHoursAgo = new Date(now.getTime() - 36 * 60 * 60 * 1000);
    const yesterdayStr = new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString().split('T')[0];

    const clients = await prisma.user.findMany({
      where: {
        role: 'CLIENT',
        oneSignalPlayerId: { not: null },
        notificationsEnabled: true,
      },
      include: {
        clientProfile: {
          include: {
            notificationPref: true,
            notifications: {
              where: {
                triggerRule: 'WORKOUT_MISSED',
                createdAt: { gte: thirtySixHoursAgo },
              },
            },
          },
        },
        assignments: {
          where: { active: true },
          include: { session: true },
        },
        workoutRecords: {
          where: { startedAt: { gte: thirtySixHoursAgo }, isCompleted: true },
        },
      },
    });

    let sent = 0;
    let skipped = 0;

    for (const client of clients) {
      try {
        const profile = client.clientProfile;
        if (!profile) { skipped++; continue; }

        // Skip if already notified in last 36 hours
        if (profile.notifications && profile.notifications.length > 0) {
          skipped++;
          continue;
        }

        // If client logged a workout in the last 36 hours, no missed workout
        if (client.workoutRecords && client.workoutRecords.length > 0) {
          skipped++;
          continue;
        }

        // Check if assigned training days include yesterday
        const assignment = client.assignments.find((a) => a.active);
        const sessionTitle = assignment?.session?.title || 'scheduled session';
        const firstName = client.name.split(' ')[0] || 'Athlete';

        const fallback = `You missed yesterday's scheduled session. Should we swap it to today or make it a rest week? 🏋️`;

        const prompt = `You are the Alpha X Gym AI Coach checking in with ${firstName}, who missed yesterday's scheduled workout ("${sessionTitle}").
Write ONE short, empathetic, solution-oriented coaching message (max 115 characters). Rules:
- Zero guilt or judgment, 100% supportive auto-regulation
- Tone target: "You missed yesterday's scheduled session. Should we swap it to today or make it a rest week?"
- Do NOT use hashtags, quotes, or markdown asterisks
- End with one emoji (🏋️, ⚡, 💪)
Reply with ONLY the notification text.`;

        const message = await this.callGemini(prompt, fallback);

        await oneSignalService.sendToPlayer(client.oneSignalPlayerId!, {
          title: 'Alpha X Coach • Training Check-In',
          body: message,
          data: { type: 'missed_workout', date: yesterdayStr },
        });

        await prisma.notification.create({
          data: {
            clientProfileId: profile.id,
            clientId: profile.clientId || null,
            title: 'Training Schedule Check-In',
            message,
            type: 'WORKOUT',
            category: 'COACHING',
            source: 'AI_COACH',
            triggerRule: 'WORKOUT_MISSED',
            sentStatus: 'SENT',
            metadataJson: JSON.stringify({ missedSessionTitle: sessionTitle, date: yesterdayStr }),
          },
        });

        sent++;
      } catch (err: any) {
        console.error(`[AI NOTIFICATIONS] Missed workout sweep error for ${client.name}:`, err?.message);
        skipped++;
      }
    }

    console.log(`[AI NOTIFICATIONS] Missed workout sweep complete: ${sent} sent, ${skipped} skipped.`);
    return { sent, skipped };
  }

  // =========================================================================
  // 4. EVENING ACCOUNTABILITY & NUTRITION GAP (8:30 PM)
  // =========================================================================
  async runEveningCheckInSweep(): Promise<{ sent: number; skipped: number }> {
    console.log('[AI NOTIFICATIONS] Starting Evening Accountability Sweep (8:30 PM)...');
    return this.runDailySweep();
  }

  /**
   * General daily sweep (called in evening or manually by admin).
   */
  async runDailySweep(): Promise<{ sent: number; skipped: number }> {
    const today = new Date();
    const todayStr = today.toISOString().split('T')[0];
    const startOfDay = new Date(`${todayStr}T00:00:00.000Z`);
    const endOfDay = new Date(`${todayStr}T23:59:59.999Z`);

    const clients = await prisma.user.findMany({
      where: {
        role: 'CLIENT',
        oneSignalPlayerId: { not: null },
        notificationsEnabled: true,
      },
      include: {
        clientProfile: {
          include: {
            dietPlans: { where: { isActive: true }, take: 1 },
            notificationPref: true,
          },
        },
      },
    });

    let sent = 0;
    let skipped = 0;

    for (const client of clients) {
      try {
        const profile = client.clientProfile;
        if (!profile) { skipped++; continue; }

        const [workoutCount, foodLogs] = await Promise.all([
          prisma.workoutRecord.count({
            where: { clientId: client.id, isCompleted: true, startedAt: { gte: startOfDay, lte: endOfDay } },
          }),
          prisma.clientFoodLog.findMany({
            where: { clientProfileId: profile.id, dateString: todayStr },
            select: { calories: true, protein: true },
          }),
        ]);

        const firstName = client.name.split(' ')[0] || 'Athlete';
        const proteinLogged = foodLogs.reduce((acc, f) => acc + (f.protein || 0), 0);
        const targetProtein = profile.dietPlans[0]?.protein ? Math.round(profile.dietPlans[0].protein) : 150;
        const proteinGap = Math.max(0, targetProtein - Math.round(proteinLogged));

        // If everything was hit, send praise or rest silently
        if (workoutCount > 0 && proteinGap === 0) {
          skipped++;
          continue;
        }

        const fallback = proteinGap > 15
          ? `Hey ${firstName}! You have ${proteinGap}g protein left today. A quick shake or Greek yogurt will lock in your recovery 🥣`
          : `Great effort today, ${firstName}! Prioritize 8 hours of sleep tonight for maximum muscular recovery 💤`;

        const prompt = `You are the Alpha X Gym AI Coach sending an evening check-in push notification to ${firstName}.
Status:
- Workout done: ${workoutCount > 0}
- Protein: ${Math.round(proteinLogged)}g / ${targetProtein}g (remaining: ${proteinGap}g)

Write ONE short, friendly evening reminder (max 115 characters). Rules:
- Mention the remaining protein gap if > 15g, or praise today's discipline
- Tone target: "You have 30g protein left today. A quick casein shake before bed will lock in your gains 🥣"
- Do NOT use hashtags or markdown asterisks
- End with one emoji (🥣, 🥩, 💤)
Reply with ONLY the notification text.`;

        const message = await this.callGemini(prompt, fallback);

        await oneSignalService.sendToPlayer(client.oneSignalPlayerId!, {
          title: '🌙 Alpha X Evening Check-In',
          body: message,
          data: { type: 'evening_checkin', date: todayStr },
        });

        await prisma.notification.create({
          data: {
            clientProfileId: profile.id,
            clientId: profile.clientId || null,
            title: '🌙 Evening Check-In',
            message,
            type: 'NUTRITION',
            category: 'NUTRITION',
            source: 'AI_COACH',
            triggerRule: proteinGap > 15 ? 'PROTEIN_BELOW_TARGET' : 'EVENING_RECOVERY',
            sentStatus: 'SENT',
            metadataJson: JSON.stringify({ proteinLogged, targetProtein, proteinGap }),
          },
        });

        sent++;
      } catch (err: any) {
        console.error(`[AI NOTIFICATIONS] Evening sweep error for ${client.name}:`, err?.message);
        skipped++;
      }
    }

    return { sent, skipped };
  }
}

export const aiNotificationEngine = new AiNotificationEngine();
