import { FoodDto } from './modules/food/food.types';

export const ADDITIONAL_FOODS: Omit<FoodDto, 'createdAt' | 'updatedAt'>[] = [
  // ==========================================
  // PROTEINS (POULTRY, MEAT, SEAFOOD, PLANT)
  // ==========================================
  {
    id: 'food_chicken_leg_cooked',
    name: 'Chicken Leg / Drumstick (Cooked, Skinless)',
    normalizedName: 'chicken leg drumstick cooked skinless',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 172,
    protein: 24.2,
    carbohydrates: 0.0,
    fat: 8.4,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 84,
    source: 'USDA',
    sourceId: 'fdc_171478',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_cooked_white_rice',
    name: 'Cooked White Rice (Basmati / Sona Masoori)',
    normalizedName: 'cooked white rice basmati sona masoori',
    category: 'Indian Foods',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 130,
    protein: 2.7,
    carbohydrates: 28.2,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    sodium: 1,
    source: 'USDA',
    sourceId: 'fdc_168878',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_raw_white_rice',
    name: 'Raw White Rice (Dry Grains)',
    normalizedName: 'raw white rice dry grains',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 365,
    protein: 7.1,
    carbohydrates: 80.0,
    fat: 0.7,
    fiber: 1.3,
    sugar: 0.1,
    sodium: 5,
    source: 'USDA',
    sourceId: 'fdc_168877',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_strawberries_fresh',
    name: 'Strawberries (Fresh)',
    normalizedName: 'strawberries fresh',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 32,
    protein: 0.7,
    carbohydrates: 7.7,
    fat: 0.3,
    fiber: 2.0,
    sugar: 4.9,
    sodium: 1,
    source: 'USDA',
    sourceId: 'fdc_167762',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_blueberries_fresh',
    name: 'Blueberries (Fresh)',
    normalizedName: 'blueberries fresh',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 57,
    protein: 0.7,
    carbohydrates: 14.5,
    fat: 0.3,
    fiber: 2.4,
    sugar: 9.9,
    sodium: 1,
    source: 'USDA',
    sourceId: 'fdc_171711',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_sunflower_seeds',
    name: 'Sunflower Seeds (Shelled, Roasted)',
    normalizedName: 'sunflower seeds shelled roasted',
    category: 'Nuts & Seeds',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 582,
    protein: 19.3,
    carbohydrates: 24.1,
    fat: 49.8,
    fiber: 11.1,
    sugar: 2.7,
    sodium: 3,
    source: 'USDA',
    sourceId: 'fdc_170562',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_flax_seeds_ground',
    name: 'Flax Seeds (Ground / Meal)',
    normalizedName: 'flax seeds ground meal',
    category: 'Nuts & Seeds',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 534,
    protein: 18.3,
    carbohydrates: 28.9,
    fat: 42.2,
    fiber: 27.3,
    sugar: 1.6,
    sodium: 30,
    source: 'USDA',
    sourceId: 'fdc_169414',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_sesame_seeds_white',
    name: 'Sesame Seeds (Whole, Dried)',
    normalizedName: 'sesame seeds whole dried',
    category: 'Nuts & Seeds',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 573,
    protein: 17.7,
    carbohydrates: 23.4,
    fat: 49.7,
    fiber: 11.8,
    sugar: 0.3,
    sodium: 11,
    source: 'USDA',
    sourceId: 'fdc_170151',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_almond_butter_pure',
    name: 'Almond Butter (100% Natural, No Added Sugar)',
    normalizedName: 'almond butter natural no added sugar',
    category: 'Nuts & Seeds',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 614,
    protein: 21.0,
    carbohydrates: 18.8,
    fat: 55.5,
    fiber: 10.3,
    sugar: 4.4,
    sodium: 7,
    source: 'USDA',
    sourceId: 'fdc_172431',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_chia_seeds_black',
    name: 'Chia Seeds (Raw)',
    normalizedName: 'chia seeds raw',
    category: 'Nuts & Seeds',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 486,
    protein: 16.5,
    carbohydrates: 42.1,
    fat: 30.7,
    fiber: 34.4,
    sugar: 0.0,
    sodium: 16,
    source: 'USDA',
    sourceId: 'fdc_170554',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_low_fat_paneer',
    name: 'Low-Fat Paneer (Fresh Cottage Cheese)',
    normalizedName: 'low fat paneer fresh cottage cheese',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 162,
    protein: 25.0,
    carbohydrates: 3.5,
    fat: 5.5,
    fiber: 0.0,
    sugar: 2.0,
    sodium: 40,
    source: 'SYSTEM',
    sourceId: 'axg_in_lfp',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_tempeh_cooked',
    name: 'Tempeh (Fermented Soy, Steamed/Cooked)',
    normalizedName: 'tempeh fermented soy steamed cooked',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 192,
    protein: 20.3,
    carbohydrates: 7.6,
    fat: 10.8,
    fiber: 4.8,
    sugar: 0.0,
    sodium: 9,
    source: 'USDA',
    sourceId: 'fdc_172465',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_soy_chunks_cooked',
    name: 'Soy Chunks / Meal-Maker (Boiled/Cooked)',
    normalizedName: 'soy chunks meal maker boiled cooked',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 145,
    protein: 25.8,
    carbohydrates: 9.5,
    fat: 0.5,
    fiber: 6.2,
    sugar: 2.1,
    sodium: 15,
    source: 'SYSTEM',
    sourceId: 'axg_in_sc',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_mackerel_cooked',
    name: 'Atlantic Mackerel (Cooked, Dry Heat)',
    normalizedName: 'atlantic mackerel cooked dry heat',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 262,
    protein: 23.9,
    carbohydrates: 0.0,
    fat: 17.8,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 83,
    source: 'USDA',
    sourceId: 'fdc_175120',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_sardines_canned',
    name: 'Sardines (Canned in Water, Drained)',
    normalizedName: 'sardines canned in water drained',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 208,
    protein: 24.6,
    carbohydrates: 0.0,
    fat: 11.5,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 505,
    source: 'USDA',
    sourceId: 'fdc_175139',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_prawns_shrimp_cooked',
    name: 'Prawns / Shrimp (Steamed/Boiled)',
    normalizedName: 'prawns shrimp steamed boiled',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 99,
    protein: 24.0,
    carbohydrates: 0.2,
    fat: 0.3,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 111,
    source: 'USDA',
    sourceId: 'fdc_175180',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_lean_beef_sirloin',
    name: 'Lean Beef Top Sirloin (Cooked, Trimmed)',
    normalizedName: 'lean beef top sirloin cooked trimmed',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 183,
    protein: 30.2,
    carbohydrates: 0.0,
    fat: 6.1,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 54,
    source: 'USDA',
    sourceId: 'fdc_170273',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_lamb_mutton_cooked',
    name: 'Lamb / Mutton (Lean Cut, Cooked)',
    normalizedName: 'lamb mutton lean cut cooked',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 216,
    protein: 28.3,
    carbohydrates: 0.0,
    fat: 10.6,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 68,
    source: 'USDA',
    sourceId: 'fdc_172535',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },

  // ==========================================
  // SOUTH INDIAN FOODS
  // ==========================================
  {
    id: 'food_idli_steamed',
    name: 'Idli (Steamed Rice & Urad Dal Cake)',
    normalizedName: 'idli steamed rice urad dal cake',
    category: 'Indian Foods',
    servingSize: 80,
    servingUnit: '2 pieces',
    calories: 112,
    protein: 3.8,
    carbohydrates: 23.4,
    fat: 0.4,
    fiber: 1.6,
    sugar: 0.2,
    sodium: 145,
    source: 'SYSTEM',
    sourceId: 'axg_in_idli',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_plain_dosa',
    name: 'Plain Dosa (Crispy Rice & Lentil Crepe)',
    normalizedName: 'plain dosa crispy rice lentil crepe',
    category: 'Indian Foods',
    servingSize: 90,
    servingUnit: '1 piece',
    calories: 168,
    protein: 3.9,
    carbohydrates: 28.4,
    fat: 4.2,
    fiber: 1.4,
    sugar: 0.3,
    sodium: 180,
    source: 'SYSTEM',
    sourceId: 'axg_in_dosa',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_masala_dosa',
    name: 'Masala Dosa (with Potato Masala Filling)',
    normalizedName: 'masala dosa potato masala filling',
    category: 'Indian Foods',
    servingSize: 160,
    servingUnit: '1 piece',
    calories: 285,
    protein: 5.6,
    carbohydrates: 42.8,
    fat: 10.2,
    fiber: 3.5,
    sugar: 1.2,
    sodium: 320,
    source: 'SYSTEM',
    sourceId: 'axg_in_mdosa',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_ragi_dosa',
    name: 'Ragi Dosa (Finger Millet Dosa)',
    normalizedName: 'ragi dosa finger millet dosa',
    category: 'Indian Foods',
    servingSize: 90,
    servingUnit: '1 piece',
    calories: 145,
    protein: 4.1,
    carbohydrates: 27.2,
    fat: 2.3,
    fiber: 3.8,
    sugar: 0.2,
    sodium: 160,
    source: 'SYSTEM',
    sourceId: 'axg_in_ragidosa',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_adai_dosa',
    name: 'Adai (High Protein Multi-Lentil Dosa)',
    normalizedName: 'adai high protein multi lentil dosa',
    category: 'Indian Foods',
    servingSize: 100,
    servingUnit: '1 piece',
    calories: 185,
    protein: 7.8,
    carbohydrates: 28.5,
    fat: 4.5,
    fiber: 4.2,
    sugar: 0.5,
    sodium: 195,
    source: 'SYSTEM',
    sourceId: 'axg_in_adai',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_ven_pongal',
    name: 'Ven Pongal (Rice & Moong Dal Ghee Porridge)',
    normalizedName: 'ven pongal rice moong dal ghee porridge',
    category: 'Indian Foods',
    servingSize: 150,
    servingUnit: '1 cup',
    calories: 242,
    protein: 5.8,
    carbohydrates: 36.2,
    fat: 8.4,
    fiber: 2.6,
    sugar: 0.4,
    sodium: 260,
    source: 'SYSTEM',
    sourceId: 'axg_in_pongal',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_rava_upma',
    name: 'Upma (Semolina / Rava Vegetable Upma)',
    normalizedName: 'upma semolina rava vegetable upma',
    category: 'Indian Foods',
    servingSize: 150,
    servingUnit: '1 cup',
    calories: 198,
    protein: 4.8,
    carbohydrates: 32.5,
    fat: 5.6,
    fiber: 2.2,
    sugar: 1.1,
    sodium: 280,
    source: 'SYSTEM',
    sourceId: 'axg_in_upma',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_appam',
    name: 'Appam (Fermented Rice Pancake)',
    normalizedName: 'appam fermented rice pancake',
    category: 'Indian Foods',
    servingSize: 60,
    servingUnit: '1 piece',
    calories: 95,
    protein: 1.8,
    carbohydrates: 19.5,
    fat: 1.0,
    fiber: 0.6,
    sugar: 1.5,
    sodium: 85,
    source: 'SYSTEM',
    sourceId: 'axg_in_appam',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_idiyappam',
    name: 'Idiyappam / String Hoppers (Steamed Rice Noodles)',
    normalizedName: 'idiyappam string hoppers steamed rice noodles',
    category: 'Indian Foods',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 125,
    protein: 2.2,
    carbohydrates: 27.8,
    fat: 0.3,
    fiber: 0.8,
    sugar: 0.1,
    sodium: 70,
    source: 'SYSTEM',
    sourceId: 'axg_in_idiyappam',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_puttu',
    name: 'Puttu (Steamed Rice Flour & Grated Coconut)',
    normalizedName: 'puttu steamed rice flour grated coconut',
    category: 'Indian Foods',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 178,
    protein: 3.2,
    carbohydrates: 34.0,
    fat: 3.2,
    fiber: 2.1,
    sugar: 0.8,
    sodium: 90,
    source: 'SYSTEM',
    sourceId: 'axg_in_puttu',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_kerala_parotta',
    name: 'Parotta (Malabar Layered Flatbread)',
    normalizedName: 'parotta malabar layered flatbread',
    category: 'Indian Foods',
    servingSize: 85,
    servingUnit: '1 piece',
    calories: 275,
    protein: 5.8,
    carbohydrates: 41.5,
    fat: 9.8,
    fiber: 1.8,
    sugar: 1.4,
    sodium: 290,
    source: 'SYSTEM',
    sourceId: 'axg_in_parotta',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_curd_rice',
    name: 'Curd Rice / Thayir Sadam',
    normalizedName: 'curd rice thayir sadam',
    category: 'Indian Foods',
    servingSize: 200,
    servingUnit: '1 bowl',
    calories: 220,
    protein: 6.8,
    carbohydrates: 36.5,
    fat: 5.2,
    fiber: 1.0,
    sugar: 3.5,
    sodium: 280,
    source: 'SYSTEM',
    sourceId: 'axg_in_curdrice',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_lemon_rice',
    name: 'Lemon Rice / Chitranna',
    normalizedName: 'lemon rice chitranna',
    category: 'Indian Foods',
    servingSize: 150,
    servingUnit: '1 cup',
    calories: 235,
    protein: 4.2,
    carbohydrates: 40.5,
    fat: 6.5,
    fiber: 1.6,
    sugar: 0.8,
    sodium: 310,
    source: 'SYSTEM',
    sourceId: 'axg_in_lemonrice',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_tomato_rice',
    name: 'Tomato Rice / Thakkali Sadam',
    normalizedName: 'tomato rice thakkali sadam',
    category: 'Indian Foods',
    servingSize: 150,
    servingUnit: '1 cup',
    calories: 225,
    protein: 4.0,
    carbohydrates: 39.0,
    fat: 5.8,
    fiber: 2.1,
    sugar: 2.4,
    sodium: 320,
    source: 'SYSTEM',
    sourceId: 'axg_in_tomatorice',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_south_indian_sambar',
    name: 'Sambar (Toor Dal & Mixed Vegetable Stew)',
    normalizedName: 'sambar toor dal mixed vegetable stew',
    category: 'Indian Foods',
    servingSize: 150,
    servingUnit: '1 cup',
    calories: 110,
    protein: 5.2,
    carbohydrates: 17.5,
    fat: 2.1,
    fiber: 4.2,
    sugar: 3.2,
    sodium: 380,
    source: 'SYSTEM',
    sourceId: 'axg_in_sambar',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_rasam_traditional',
    name: 'Rasam (Tamarind, Tomato & Pepper Broth)',
    normalizedName: 'rasam tamarind tomato pepper broth',
    category: 'Indian Foods',
    servingSize: 150,
    servingUnit: '1 cup',
    calories: 45,
    protein: 1.5,
    carbohydrates: 7.5,
    fat: 1.0,
    fiber: 1.2,
    sugar: 2.0,
    sodium: 340,
    source: 'SYSTEM',
    sourceId: 'axg_in_rasam',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },

  // ==========================================
  // DALS & LEGUMES
  // ==========================================
  {
    id: 'food_toor_dal_cooked',
    name: 'Toor Dal / Pigeon Pea (Boiled/Cooked)',
    normalizedName: 'toor dal pigeon pea boiled cooked',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 128,
    protein: 8.6,
    carbohydrates: 22.0,
    fat: 0.6,
    fiber: 6.8,
    sugar: 1.2,
    sodium: 15,
    source: 'USDA',
    sourceId: 'fdc_172428',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_moong_dal_cooked',
    name: 'Moong Dal / Yellow Split Lentil (Cooked)',
    normalizedName: 'moong dal yellow split lentil cooked',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 116,
    protein: 8.1,
    carbohydrates: 19.8,
    fat: 0.5,
    fiber: 5.5,
    sugar: 1.0,
    sodium: 12,
    source: 'USDA',
    sourceId: 'fdc_172432',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_masoor_dal_cooked',
    name: 'Masoor Dal / Red Lentil (Cooked)',
    normalizedName: 'masoor dal red lentil cooked',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 114,
    protein: 9.0,
    carbohydrates: 19.5,
    fat: 0.4,
    fiber: 7.9,
    sugar: 1.8,
    sodium: 10,
    source: 'USDA',
    sourceId: 'fdc_172429',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_urad_dal_cooked',
    name: 'Urad Dal / Black Gram Split (Cooked)',
    normalizedName: 'urad dal black gram split cooked',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 120,
    protein: 8.8,
    carbohydrates: 20.2,
    fat: 0.5,
    fiber: 6.2,
    sugar: 1.1,
    sodium: 14,
    source: 'SYSTEM',
    sourceId: 'axg_in_udal',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_chana_dal_cooked',
    name: 'Chana Dal / Split Bengal Gram (Cooked)',
    normalizedName: 'chana dal split bengal gram cooked',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 130,
    protein: 8.5,
    carbohydrates: 21.5,
    fat: 1.2,
    fiber: 7.2,
    sugar: 1.4,
    sodium: 18,
    source: 'SYSTEM',
    sourceId: 'axg_in_cdal',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_rajma_cooked',
    name: 'Rajma / Red Kidney Beans (Boiled/Cooked)',
    normalizedName: 'rajma red kidney beans boiled cooked',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 127,
    protein: 8.7,
    carbohydrates: 22.8,
    fat: 0.5,
    fiber: 6.4,
    sugar: 0.3,
    sodium: 12,
    source: 'USDA',
    sourceId: 'fdc_173735',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_sprouted_moong',
    name: 'Sprouted Green Gram / Moong (Raw)',
    normalizedName: 'sprouted green gram moong raw',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 30,
    protein: 3.1,
    carbohydrates: 5.9,
    fat: 0.2,
    fiber: 1.8,
    sugar: 4.1,
    sodium: 6,
    source: 'USDA',
    sourceId: 'fdc_172430',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },

  // ==========================================
  // VEGETABLES
  // ==========================================
  {
    id: 'food_drumstick_moringa_cooked',
    name: 'Drumstick / Moringa Pods (Cooked)',
    normalizedName: 'drumstick moringa pods cooked',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 37,
    protein: 2.1,
    carbohydrates: 8.5,
    fat: 0.2,
    fiber: 3.2,
    sugar: 1.4,
    sodium: 42,
    source: 'USDA',
    sourceId: 'fdc_170425',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_bottle_gourd_lauki',
    name: 'Bottle Gourd / Lauki (Boiled/Cooked)',
    normalizedName: 'bottle gourd lauki boiled cooked',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 14,
    protein: 0.6,
    carbohydrates: 3.4,
    fat: 0.1,
    fiber: 1.2,
    sugar: 1.8,
    sodium: 8,
    source: 'SYSTEM',
    sourceId: 'axg_in_lauki',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_bitter_gourd_karela',
    name: 'Bitter Gourd / Karela (Cooked)',
    normalizedName: 'bitter gourd karela cooked',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 19,
    protein: 1.0,
    carbohydrates: 4.3,
    fat: 0.2,
    fiber: 2.0,
    sugar: 0.6,
    sodium: 6,
    source: 'SYSTEM',
    sourceId: 'axg_in_karela',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_ladies_finger_bhindi',
    name: 'Ladies Finger / Okra / Bhindi (Cooked)',
    normalizedName: 'ladies finger okra bhindi cooked',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 33,
    protein: 1.9,
    carbohydrates: 7.5,
    fat: 0.2,
    fiber: 3.2,
    sugar: 1.5,
    sodium: 7,
    source: 'USDA',
    sourceId: 'fdc_169260',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_brinjal_eggplant',
    name: 'Brinjal / Eggplant / Baingan (Cooked)',
    normalizedName: 'brinjal eggplant baingan cooked',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 25,
    protein: 1.0,
    carbohydrates: 5.9,
    fat: 0.2,
    fiber: 3.0,
    sugar: 3.2,
    sodium: 2,
    source: 'USDA',
    sourceId: 'fdc_169229',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_pumpkin_cooked',
    name: 'Pumpkin / Kaddu (Boiled/Steamed)',
    normalizedName: 'pumpkin kaddu boiled steamed',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 26,
    protein: 1.0,
    carbohydrates: 6.5,
    fat: 0.1,
    fiber: 1.1,
    sugar: 2.8,
    sodium: 1,
    source: 'USDA',
    sourceId: 'fdc_168449',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },

  // ==========================================
  // FRUITS
  // ==========================================
  {
    id: 'food_muskmelon_cantaloupe',
    name: 'Muskmelon / Cantaloupe (Fresh Diced)',
    normalizedName: 'muskmelon cantaloupe fresh diced',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 34,
    protein: 0.8,
    carbohydrates: 8.2,
    fat: 0.2,
    fiber: 0.9,
    sugar: 7.9,
    sodium: 16,
    source: 'USDA',
    sourceId: 'fdc_169092',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_guava_fresh',
    name: 'Guava (Fresh White/Pink)',
    normalizedName: 'guava fresh white pink',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 68,
    protein: 2.6,
    carbohydrates: 14.3,
    fat: 1.0,
    fiber: 5.4,
    sugar: 8.9,
    sodium: 2,
    source: 'USDA',
    sourceId: 'fdc_173944',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_pomegranate_arils',
    name: 'Pomegranate (Fresh Seeds / Arils)',
    normalizedName: 'pomegranate fresh seeds arils',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 83,
    protein: 1.7,
    carbohydrates: 18.7,
    fat: 1.2,
    fiber: 4.0,
    sugar: 13.7,
    sodium: 3,
    source: 'USDA',
    sourceId: 'fdc_169134',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_kiwi_fresh',
    name: 'Kiwi Fruit (Fresh Green/Gold)',
    normalizedName: 'kiwi fruit fresh green gold',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 61,
    protein: 1.1,
    carbohydrates: 14.7,
    fat: 0.5,
    fiber: 3.0,
    sugar: 9.0,
    sodium: 3,
    source: 'USDA',
    sourceId: 'fdc_168153',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_dates_medjool',
    name: 'Dates (Medjool, Pitted)',
    normalizedName: 'dates medjool pitted',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 277,
    protein: 1.8,
    carbohydrates: 75.0,
    fat: 0.2,
    fiber: 6.7,
    sugar: 66.5,
    sodium: 1,
    source: 'USDA',
    sourceId: 'fdc_168191',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_dried_figs_anjeer',
    name: 'Dried Figs / Anjeer',
    normalizedName: 'dried figs anjeer',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 249,
    protein: 3.3,
    carbohydrates: 63.9,
    fat: 0.9,
    fiber: 9.8,
    sugar: 47.9,
    sodium: 10,
    source: 'USDA',
    sourceId: 'fdc_173943',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
  {
    id: 'food_coconut_fresh_meat',
    name: 'Coconut Meat (Raw, Fresh)',
    normalizedName: 'coconut meat raw fresh',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    calories: 354,
    protein: 3.3,
    carbohydrates: 15.2,
    fat: 33.5,
    fiber: 9.0,
    sugar: 6.2,
    sodium: 20,
    source: 'USDA',
    sourceId: 'fdc_170169',
    isCustom: false,
    isPublic: true,
    isVerified: true,
    status: 'APPROVED',
  },
];
