export interface ExerciseItem {
  id: string;
  name: string;
  category: string;
  subCategory: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  equipment: string;
  movementPattern: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  exerciseType: string;
  description: string;
  setupInstructions: string[];
  executionSteps: string[];
  coachingCues: string[];
  commonMistakes: string[];
  defaultTrainerNote: string;
  tags: string[];
}

export const ADDITIONAL_EXERCISES: ExerciseItem[] = [
  // ==========================================
  // CHEST
  // ==========================================
  {
    id: 'ex_smith_bench_press',
    name: 'Smith Machine Bench Press',
    category: 'Chest',
    subCategory: 'Mid Chest',
    primaryMuscles: ['MuscleGroup.midChest'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.triceps'],
    equipment: 'Smith Machine',
    movementPattern: 'Horizontal Push',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Fixed-track barbell bench press on the Smith machine allowing safe overload and high fatigue training without stabilization failure.',
    setupInstructions: ['Position flat bench centered under Smith bar.', 'Set bar height so elbows have slight bend when gripping.', 'Lie flat with eyes aligned under the bar, retract scapulae.'],
    executionSteps: ['Unrack bar with a slight wrist twist.', 'Lower bar under control to mid-sternum.', 'Drive straight up without completely hyperextending elbows.'],
    coachingCues: ['Keep shoulder blades pinched together.', 'Control the 3-second descent.', 'Squeeze pecs at top.'],
    commonMistakes: ['Bouncing bar off chest.', 'Lifting hips off the bench.'],
    defaultTrainerNote: 'Excellent for hypertrophy drop sets and training to muscular failure safely.',
    tags: ['Chest', 'Smith Machine', 'Hypertrophy', 'Push'],
  },
  {
    id: 'ex_ring_pushup',
    name: 'Ring Push-Up',
    category: 'Chest',
    subCategory: 'Mid Chest',
    primaryMuscles: ['MuscleGroup.midChest'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.triceps', 'MuscleGroup.coreAbs'],
    equipment: 'TRX',
    movementPattern: 'Horizontal Push',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Push-up performed on gymnastic rings or suspension straps, requiring immense shoulder stabilization and allowing natural wrist rotation.',
    setupInstructions: ['Hang rings 4 to 6 inches off floor.', 'Grip rings with neutral palms, brace core and glutes into solid plank.'],
    executionSteps: ['Descend until thumbs touch chest, allowing rings to drift slightly outward.', 'Push back up while turning palms toward each other at top for peak contraction.'],
    coachingCues: ['Fight ring oscillation.', 'Keep core braced like a stone.', 'Turn palms in at top.'],
    commonMistakes: ['Sagging lower back.', 'Letting rings pull shoulders into internal rotation.'],
    defaultTrainerNote: 'Elite stabilizer exercise that recruits maximum motor units in the chest.',
    tags: ['Chest', 'Gymnastics', 'Calisthenics', 'TRX'],
  },
  {
    id: 'ex_weighted_pushup',
    name: 'Weighted Push-Up',
    category: 'Chest',
    subCategory: 'Mid Chest',
    primaryMuscles: ['MuscleGroup.midChest'],
    secondaryMuscles: ['MuscleGroup.triceps', 'MuscleGroup.frontDelts', 'MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Horizontal Push',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Standard push-up overloaded with a weight plate or weighted vest over the upper back for strength and muscle mass progression.',
    setupInstructions: ['Place bumper plate across mid/upper back or fasten weighted vest.', 'Set hands shoulder-width apart, brace core.'],
    executionSteps: ['Lower chest until 1 inch off the floor.', 'Press forcefully through palms back to lockout.'],
    coachingCues: ['Elbows at 45 degrees.', 'Maintain plank rigidity under load.'],
    commonMistakes: ['Letting weight plate slide toward neck.', 'Hyperextending lumbar spine.'],
    defaultTrainerNote: 'Horizontal push overload without requiring a barbell bench station.',
    tags: ['Chest', 'Weighted', 'Push-Up', 'Strength'],
  },
  {
    id: 'ex_low_to_high_cable_fly',
    name: 'Standing Low-to-High Cable Fly',
    category: 'Chest',
    subCategory: 'Upper Chest',
    primaryMuscles: ['MuscleGroup.upperChest'],
    secondaryMuscles: ['MuscleGroup.frontDelts'],
    equipment: 'Cable',
    movementPattern: 'Incline Push',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Cable fly executed from lowest pulley setting bringing hands upward and together to align with the clavicular pec fibers.',
    setupInstructions: ['Attach D-handles to lowest cable pulleys.', 'Stand staggered in center of cable crossover station, palms facing forward and up.'],
    executionSteps: ['Sweep arms upward in an arc toward eye level.', 'Squeeze upper pecs hard for 1 second at top.', 'Lower with controlled eccentric arc.'],
    coachingCues: ['Lead with elbows.', 'Focus on scooping upward.', 'Keep chest puffed up.'],
    commonMistakes: ['Swinging torso backward.', 'Using only front deltoids.'],
    defaultTrainerNote: 'Peak upper pec isolator. Pair with heavy incline presses.',
    tags: ['Chest', 'Cables', 'Upper Chest', 'Hypertrophy'],
  },
  {
    id: 'ex_high_to_low_cable_fly',
    name: 'Standing High-to-Low Cable Fly',
    category: 'Chest',
    subCategory: 'Lower Chest',
    primaryMuscles: ['MuscleGroup.lowerChest'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.triceps'],
    equipment: 'Cable',
    movementPattern: 'Decline Push',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Cable fly anchored high and brought downward toward hips, targeting the sternocostal and abdominal heads of the pectoralis major.',
    setupInstructions: ['Set pulleys above head height.', 'Step forward with split stance, torso leaning slightly forward.'],
    executionSteps: ['Bring hands downward and forward in a hug-like arc until knuckles meet below waist level.', 'Pause for squeeze.', 'Return along same arc.'],
    coachingCues: ['Think of hugging a big tree trunk.', 'Keep slight bend in elbows.'],
    commonMistakes: ['Pressing instead of flying.', 'Shrugging shoulders.'],
    defaultTrainerNote: 'Isolates the lower pectoral outline without shoulder discomfort of decline benching.',
    tags: ['Chest', 'Cables', 'Lower Chest', 'Isolation'],
  },

  // ==========================================
  // BACK
  // ==========================================
  {
    id: 'ex_neutral_pullup',
    name: 'Neutral-Grip Pull-Up',
    category: 'Back',
    subCategory: 'Upper Back / Lats',
    primaryMuscles: ['MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.rhomboids', 'MuscleGroup.forearms'],
    equipment: 'Bodyweight',
    movementPattern: 'Vertical Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Pull-up performed with parallel handles (palms facing each other), offering the strongest mechanical leverage and kindest shoulder positioning.',
    setupInstructions: ['Grip parallel handles on pull-up tower with thumbs wrapped.', 'Hang at full arm extension, depress scapulae.'],
    executionSteps: ['Drive elbows down toward waist to pull chest up toward handles.', 'Pause with chin clearing handles.', 'Lower with 3-second control to dead hang.'],
    coachingCues: ['Pull elbows down into back pockets.', 'Keep ribcage clamped down.'],
    commonMistakes: ['Kicking legs or kipping.', 'Half reps cutting out bottom stretch.'],
    defaultTrainerNote: 'Safest pull-up variation for athletes with shoulder impingement history.',
    tags: ['Back', 'Pull-Up', 'Bodyweight', 'Lats'],
  },
  {
    id: 'ex_wide_lat_pulldown',
    name: 'Wide-Grip Lat Pulldown',
    category: 'Back',
    subCategory: 'Upper Lats',
    primaryMuscles: ['MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.teresMajor', 'MuscleGroup.biceps', 'MuscleGroup.rhomboids'],
    equipment: 'Cable',
    movementPattern: 'Vertical Pull',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Lat pulldown with grip 6 to 8 inches outside shoulder width to maximize frontal-plane adduction and upper lat sweep.',
    setupInstructions: ['Adjust thigh pad snug against knees.', 'Grip curved lat bar outside shoulders with pronated grip.', 'Sit with torso tall, slight 10-degree back lean.'],
    executionSteps: ['Depress shoulder blades and pull bar smoothly to upper chest.', 'Squeeze lats firmly.', 'Control weight stack back to full overhead stretch.'],
    coachingCues: ['Lead with elbows.', 'Do not lean back into a horizontal row.'],
    commonMistakes: ['Yanking with body momentum.', 'Pulling bar behind neck.'],
    defaultTrainerNote: 'Focus on full lat stretch at top without releasing shoulder blade depression.',
    tags: ['Back', 'Cables', 'Lats', 'Hypertrophy'],
  },
  {
    id: 'ex_close_grip_lat_pulldown',
    name: 'Close-Grip Lat Pulldown',
    category: 'Back',
    subCategory: 'Mid Back / Lats',
    primaryMuscles: ['MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.rhomboids'],
    equipment: 'Cable',
    movementPattern: 'Vertical Pull',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Lat pulldown using a V-bar or neutral close grip attachment to allow deeper shoulder extension and lower lat activation.',
    setupInstructions: ['Attach V-bar handle to pulldown cable.', 'Sit upright with thighs securely pinned under pads.'],
    executionSteps: ['Pull V-bar down toward upper sternum.', 'Drive elbows down and back.', 'Slowly return to full stretch overhead.'],
    coachingCues: ['Arch mid-chest up to meet the handle.', 'Squeeze mid-back.'],
    commonMistakes: ['Excessive backward leaning beyond 20 degrees.'],
    defaultTrainerNote: 'Great builder for mid-back thickness and lower lat origin.',
    tags: ['Back', 'Pulldown', 'Cables', 'V-Bar'],
  },
  {
    id: 'ex_single_arm_lat_pulldown',
    name: 'Single-Arm Lat Pulldown',
    category: 'Back',
    subCategory: 'Lats',
    primaryMuscles: ['MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.coreAbs'],
    equipment: 'Cable',
    movementPattern: 'Vertical Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral cable lat pulldown allowing the line of pull to perfectly track the user\'s natural lat muscle fibers.',
    setupInstructions: ['Attach single D-handle to high cable.', 'Sit sideways or kneel facing cable with arm in full overhead stretch.'],
    executionSteps: ['Drive elbow vertically down to side of hip.', 'Slight lateral crunch into the contracting lat at bottom.', 'Control release upward.'],
    coachingCues: ['Elbow pinned tight to ribs at bottom.', 'Feel individual lat fiber stretch.'],
    commonMistakes: ['Rotating torso away from pulley.'],
    defaultTrainerNote: 'Gold standard unilateral movement to fix lat imbalances.',
    tags: ['Back', 'Unilateral', 'Lats', 'Cables'],
  },
  {
    id: 'ex_single_arm_cable_row',
    name: 'Single-Arm Cable Row',
    category: 'Back',
    subCategory: 'Mid Back / Lats',
    primaryMuscles: ['MuscleGroup.lats', 'MuscleGroup.rhomboids'],
    secondaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.coreAbs'],
    equipment: 'Cable',
    movementPattern: 'Horizontal Pull',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Seated or standing unilateral horizontal row with continuous tension across the entire contraction arc.',
    setupInstructions: ['Set cable pulley at mid-torso height with single handle.', 'Sit with knees slightly flexed, chest tall.'],
    executionSteps: ['Allow shoulder blade to protract for full stretch.', 'Retract scapula and drive elbow straight back past torso.', 'Pause for 1 second before extending.'],
    coachingCues: ['Initiate with shoulder blade, finish with elbow.', 'Resist torso twisting.'],
    commonMistakes: ['Using momentum from lower back.'],
    defaultTrainerNote: 'Builds core anti-rotational stability while targeting the lat.',
    tags: ['Back', 'Cables', 'Row', 'Unilateral'],
  },
  {
    id: 'ex_seal_row',
    name: 'Seal Row',
    category: 'Back',
    subCategory: 'Upper Back',
    primaryMuscles: ['MuscleGroup.rhomboids', 'MuscleGroup.traps', 'MuscleGroup.rearDelts'],
    secondaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.lats'],
    equipment: 'Barbell',
    movementPattern: 'Horizontal Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Prone row performed lying flat on an elevated bench with legs unsupported, completely eliminating lower back momentum and cheating.',
    setupInstructions: ['Lie face down on a flat elevated bench.', 'Grip barbell or dumbbells beneath bench with overhand grip.'],
    executionSteps: ['Pull bar straight up until it lightly touches underside of bench.', 'Squeeze shoulder blades tightly together.', 'Lower under control without swinging.'],
    coachingCues: ['Pinch shoulder blades hard at top.', 'Keep neck neutral.'],
    commonMistakes: ['Banging bar into bench with jerking hips.'],
    defaultTrainerNote: 'The purest upper back isolation row without spinal erector fatigue.',
    tags: ['Back', 'Barbell', 'Upper Back', 'Seal Row'],
  },
  {
    id: 'ex_barbell_pullover',
    name: 'Barbell Pullover',
    category: 'Back',
    subCategory: 'Lats & Teres',
    primaryMuscles: ['MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.triceps', 'MuscleGroup.upperChest', 'MuscleGroup.serratus'],
    equipment: 'Barbell',
    movementPattern: 'Vertical Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Barbell arc extension across bench creating a deep stretch along the lateral ribcage and lat insertion.',
    setupInstructions: ['Lie flat on bench holding barbell shoulder-width above chest with slight elbow bend.'],
    executionSteps: ['Lower barbell backward overhead in an arc toward floor until feeling deep lat stretch.', 'Pull bar back over face to vertical position using lats.'],
    coachingCues: ['Keep elbows locked in slight flexion.', 'Pull with armpits.'],
    commonMistakes: ['Turning movement into a triceps skull crusher.'],
    defaultTrainerNote: 'Classic bodybuilding lat widener and ribcage expander.',
    tags: ['Back', 'Barbell', 'Pullover', 'Lats'],
  },

  // ==========================================
  // SHOULDERS
  // ==========================================
  {
    id: 'ex_seated_db_press',
    name: 'Seated Dumbbell Shoulder Press',
    category: 'Shoulders',
    subCategory: 'Anterior & Lateral Delts',
    primaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.sideDelts'],
    secondaryMuscles: ['MuscleGroup.triceps', 'MuscleGroup.traps'],
    equipment: 'Dumbbell',
    movementPattern: 'Vertical Push',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Dumbbell overhead press seated on an upright bench with 80 to 85-degree back support, maximizing deltoid load.',
    setupInstructions: ['Sit with back firm against bench angled at ~85 degrees.', 'Kick dumbbells up to shoulder level with elbows angled 30 degrees in scapular plane.'],
    executionSteps: ['Press dumbbells upward in slight inward arc overhead.', 'Stop just shy of clicking weights at top.', 'Lower smoothly down until dumbbells reach ear level.'],
    coachingCues: ['Press in scapular plane.', 'Keep feet grounded firmly.'],
    commonMistakes: ['Arching lower back heavily away from bench.'],
    defaultTrainerNote: 'Foundational shoulder builder with excellent joint freedom.',
    tags: ['Shoulders', 'Dumbbell', 'Overhead Press', 'Compound'],
  },
  {
    id: 'ex_lean_away_lateral_raise',
    name: 'Lean-Away Cable Lateral Raise',
    category: 'Shoulders',
    subCategory: 'Lateral Deltoids',
    primaryMuscles: ['MuscleGroup.sideDelts'],
    secondaryMuscles: ['MuscleGroup.traps'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Single-arm cable lateral raise performed leaning away from the cable tower to optimize the deltoid resistance curve at the bottom.',
    setupInstructions: ['Hold upright pole of cable tower with non-working hand and lean torso outward 20-30 degrees.', 'Hold low cable handle behind or in front of hips.'],
    executionSteps: ['Raise arm laterally up to shoulder height.', 'Pause for 1 second peak contraction.', 'Lower with strict 3-second tempo.'],
    coachingCues: ['Pour water with pinky slightly higher than thumb.', 'Do not use trap shrug.'],
    commonMistakes: ['Using swinging body English.'],
    defaultTrainerNote: 'Maintains constant muscle tension where dumbbells offer zero load at the bottom.',
    tags: ['Shoulders', 'Cables', 'Lateral Raise', 'Side Delts'],
  },
  {
    id: 'ex_single_arm_lateral_raise',
    name: 'Single-Arm Dumbbell Lateral Raise',
    category: 'Shoulders',
    subCategory: 'Lateral Deltoids',
    primaryMuscles: ['MuscleGroup.sideDelts'],
    secondaryMuscles: ['MuscleGroup.traps'],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral dumbbell lateral raise holding onto a stable upright with the free hand for maximal mind-muscle focus.',
    setupInstructions: ['Hold pole or rack with one hand, hold dumbbell in active hand at side.'],
    executionSteps: ['Raise dumbbell outward until arm reaches parallel with floor.', 'Hold for half second.', 'Lower under strict eccentric control.'],
    coachingCues: ['Reach outward toward side walls rather than just lifting up.'],
    commonMistakes: ['Swinging torso.'],
    defaultTrainerNote: 'Removes balance requirements so side delts get 100% of stimulus.',
    tags: ['Shoulders', 'Dumbbell', 'Lateral Raise', 'Unilateral'],
  },
  {
    id: 'ex_cable_front_raise',
    name: 'Cable Front Raise',
    category: 'Shoulders',
    subCategory: 'Anterior Deltoids',
    primaryMuscles: ['MuscleGroup.frontDelts'],
    secondaryMuscles: ['MuscleGroup.upperChest', 'MuscleGroup.traps'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Overhand cable front raise facing away from a low pulley with cable passing between legs.',
    setupInstructions: ['Straddle low cable with rope or straight bar attachment, facing away from pulley.'],
    executionSteps: ['Raise hands forward and up to eye level with straight arms.', 'Pause for squeeze at top.', 'Lower smoothly down.'],
    coachingCues: ['Do not lean back as weight rises.', 'Keep core braced.'],
    commonMistakes: ['Swinging hips to generate momentum.'],
    defaultTrainerNote: 'Consistent resistance at bottom of movement.',
    tags: ['Shoulders', 'Cables', 'Front Delts', 'Isolation'],
  },
  {
    id: 'ex_plate_front_raise',
    name: 'Plate Front Raise',
    category: 'Shoulders',
    subCategory: 'Anterior Deltoids',
    primaryMuscles: ['MuscleGroup.frontDelts'],
    secondaryMuscles: ['MuscleGroup.upperChest', 'MuscleGroup.traps'],
    equipment: 'Other',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Gripping a weight plate at 9 and 3 o\'clock and raising in front of torso to eye level.',
    setupInstructions: ['Stand tall gripping 10-20kg bumper plate on both sides at hip level.'],
    executionSteps: ['Raise plate straight up in front to eye level without tilting head.', 'Pause briefly at apex.', 'Lower with steady control.'],
    coachingCues: ['Look through the center hole at the top of repetition.'],
    commonMistakes: ['Rocking backwards.'],
    defaultTrainerNote: 'Great shoulder burnout finisher.',
    tags: ['Shoulders', 'Plate', 'Burnout', 'Front Delts'],
  },
  {
    id: 'ex_cable_reverse_fly',
    name: 'Cable Reverse Fly',
    category: 'Shoulders',
    subCategory: 'Posterior Deltoids',
    primaryMuscles: ['MuscleGroup.rearDelts'],
    secondaryMuscles: ['MuscleGroup.rhomboids', 'MuscleGroup.traps'],
    equipment: 'Cable',
    movementPattern: 'Horizontal Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Crossing cables without attachments at chest level, sweeping arms horizontally backward to isolate the rear deltoids.',
    setupInstructions: ['Set pulleys at chest height.', 'Grab left cable with right hand, right cable with left hand (cables crossed).', 'Stand centered with arms crossed in front.'],
    executionSteps: ['Pull arms outward and back horizontally in wide arc.', 'Squeeze rear delts at peak.', 'Return under control.'],
    coachingCues: ['Lead with elbows and backs of hands.', 'Do not pinch scapulae together aggressively; focus on rear delts.'],
    commonMistakes: ['Bending elbows into a triceps press.'],
    defaultTrainerNote: 'Essential for fixing rounded forward shoulder posture.',
    tags: ['Shoulders', 'Cables', 'Rear Delts', 'Postural'],
  },
  {
    id: 'ex_rear_delt_row',
    name: 'Rear Delt Row',
    category: 'Shoulders',
    subCategory: 'Posterior Deltoids',
    primaryMuscles: ['MuscleGroup.rearDelts'],
    secondaryMuscles: ['MuscleGroup.rhomboids', 'MuscleGroup.traps'],
    equipment: 'Dumbbell',
    movementPattern: 'Horizontal Pull',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Chest-supported or bent-over dumbbell row with elbows flared out at 90 degrees to load the posterior shoulder.',
    setupInstructions: ['Lie face down on incline bench set to 30 degrees.', 'Hold dumbbells with palms facing feet.'],
    executionSteps: ['Row dumbbells up while driving elbows out wide at 90 degrees to torso.', 'Squeeze rear deltoids at top.', 'Lower with control.'],
    coachingCues: ['Elbows high and wide.', 'Pull with the back of shoulders.'],
    commonMistakes: ['Tucking elbows into lats.'],
    defaultTrainerNote: 'Allows heavier rear delt loading than flyes.',
    tags: ['Shoulders', 'Dumbbell', 'Rear Delts', 'Row'],
  },
  {
    id: 'ex_cable_y_raise',
    name: 'Cable Y-Raise',
    category: 'Shoulders',
    subCategory: 'Lower Traps & Deltoids',
    primaryMuscles: ['MuscleGroup.sideDelts', 'MuscleGroup.rearDelts'],
    secondaryMuscles: ['MuscleGroup.traps'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Cable raise in a 45-degree diagonal Y-pattern aligning with the lower trapezius and lateral deltoid plane.',
    setupInstructions: ['Set low pulleys, cross cables.', 'Hold handles in front of hips.'],
    executionSteps: ['Raise arms up and outward diagonally overhead to form a Y shape.', 'Hold for 1 second.', 'Lower along same path.'],
    coachingCues: ['Make a Y with your arms.', 'Control the lowering.'],
    commonMistakes: ['Shrugging upper traps.'],
    defaultTrainerNote: 'Exceptional for overhead stability and shoulder health.',
    tags: ['Shoulders', 'Cables', 'Y-Raise', 'Prehab'],
  },
  {
    id: 'ex_db_y_raise',
    name: 'Dumbbell Incline Y-Raise',
    category: 'Shoulders',
    subCategory: 'Lower Traps',
    primaryMuscles: ['MuscleGroup.sideDelts', 'MuscleGroup.rearDelts'],
    secondaryMuscles: ['MuscleGroup.traps'],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Prone on incline bench, raising light dumbbells in a 30 to 45-degree diagonal Y angle.',
    setupInstructions: ['Lie prone on incline bench set to 45 degrees, light dumbbells in hand.'],
    executionSteps: ['Raise arms up diagonally forming a Y with thumbs pointed up.', 'Squeeze mid/lower back and shoulders at top.'],
    coachingCues: ['Thumbs to the sky.', 'Keep arms straight.'],
    commonMistakes: ['Using weights that are too heavy.'],
    defaultTrainerNote: 'High value prehab exercise for athletes who bench press frequently.',
    tags: ['Shoulders', 'Dumbbell', 'Lower Trap', 'Mobility'],
  },
  {
    id: 'ex_cuban_press',
    name: 'Cuban Press',
    category: 'Shoulders',
    subCategory: 'Rotator Cuff',
    primaryMuscles: ['MuscleGroup.rotatorCuff', 'MuscleGroup.rearDelts'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.traps'],
    equipment: 'Dumbbell',
    movementPattern: 'Compound',
    difficulty: 'Advanced',
    exerciseType: 'Mobility',
    description: 'Multi-phase shoulder exercise combining an upright row, external rotation, and overhead press.',
    setupInstructions: ['Stand tall holding light dumbbells with overhand grip at thighs.'],
    executionSteps: ['Upright row until upper arms are parallel to floor.', 'Externally rotate forearms up until vertical.', 'Press overhead to full extension, then reverse all 3 phases.'],
    coachingCues: ['Fluid transitions between row, rotation, and press.', 'Keep weight light.'],
    commonMistakes: ['Jerking through the rotation phase.'],
    defaultTrainerNote: 'Classic Olympic weightlifting movement for iron-clad rotator cuffs.',
    tags: ['Shoulders', 'Rotator Cuff', 'Mobility', 'Prehab'],
  },

  // ==========================================
  // BICEPS
  // ==========================================
  {
    id: 'ex_alternating_db_curl',
    name: 'Standing Alternating Dumbbell Curl',
    category: 'Biceps',
    subCategory: 'Biceps Brachii',
    primaryMuscles: ['MuscleGroup.biceps'],
    secondaryMuscles: ['MuscleGroup.forearms', 'MuscleGroup.brachialis'],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Dumbbell curl alternating left and right arms with full supination from neutral grip at bottom to palm-up at top.',
    setupInstructions: ['Stand with feet hip-width, dumbbells held at sides with palms facing inward.'],
    executionSteps: ['Curl one arm while rotating palm outward into full supination.', 'Squeeze bicep at peak height.', 'Lower under control while initiating curl with opposite arm.'],
    coachingCues: ['Turn pinky upward at top of contraction.', 'Keep elbow stationary at side.'],
    commonMistakes: ['Swinging torso or pitching elbows forward.'],
    defaultTrainerNote: 'Allows maximal concentration on bicep supination per side.',
    tags: ['Biceps', 'Dumbbell', 'Supination', 'Arms'],
  },
  {
    id: 'ex_cross_body_hammer_curl',
    name: 'Cross-Body Hammer Curl',
    category: 'Biceps',
    subCategory: 'Brachialis',
    primaryMuscles: ['MuscleGroup.brachialis', 'MuscleGroup.forearms'],
    secondaryMuscles: ['MuscleGroup.biceps'],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Dumbbell hammer curl curling across the chest toward opposite shoulder to emphasize the brachialis muscle.',
    setupInstructions: ['Stand tall holding dumbbells with neutral palms.'],
    executionSteps: ['Curl dumbbell across torso toward opposite collarbone.', 'Squeeze brachialis at peak.', 'Lower back to side and repeat on opposite arm.'],
    coachingCues: ['Keep wrist rigid and neutral.', 'Drive dumbbell across front of chest.'],
    commonMistakes: ['Flaring elbow outward.'],
    defaultTrainerNote: 'Pushes the bicep peak upward by thickening the underlying brachialis.',
    tags: ['Biceps', 'Hammer', 'Brachialis', 'Forearms'],
  },
  {
    id: 'ex_machine_preacher_curl',
    name: 'Machine Preacher Curl',
    category: 'Biceps',
    subCategory: 'Short Head',
    primaryMuscles: ['MuscleGroup.biceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Machine',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Preacher curl machine locking upper arms against angled pad, providing peak resistance throughout the curl arc.',
    setupInstructions: ['Adjust seat so armpits sit comfortably on top of preacher pad.', 'Grip handles with underhand grip.'],
    executionSteps: ['Curl handles toward face, flexing biceps fully.', 'Hold 1 second at top.', 'Lower slowly until arms are near full extension.'],
    coachingCues: ['Keep triceps glued to pad.', 'Do not hyperextend elbows at bottom.'],
    commonMistakes: ['Lifting hips off seat to leverage weight.'],
    defaultTrainerNote: 'Safe way to train strict bicep failure without wrist strain.',
    tags: ['Biceps', 'Machine', 'Preacher', 'Isolation'],
  },
  {
    id: 'ex_bayesian_cable_curl',
    name: 'Bayesian Cable Curl',
    category: 'Biceps',
    subCategory: 'Long Head',
    primaryMuscles: ['MuscleGroup.biceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Cable curl performed facing away from low pulley with arms extended behind torso, training the long head in maximum stretch.',
    setupInstructions: ['Attach D-handles to low pulleys.', 'Step 2 to 3 feet forward with staggered stance, arms extending behind body.'],
    executionSteps: ['Curl handles forward while keeping elbows pinned slightly behind torso.', 'Squeeze biceps hard at top.', 'Return to full stretch behind body.'],
    coachingCues: ['Maintain elbow position behind torso throughout.', 'Enjoy the deep stretch.'],
    commonMistakes: ['Swinging elbows forward during curl.'],
    defaultTrainerNote: 'Science-backed stretch-mediated hypertrophy movement for biceps.',
    tags: ['Biceps', 'Cables', 'Long Head', 'Stretch'],
  },
  {
    id: 'ex_drag_curl',
    name: 'Drag Curl',
    category: 'Biceps',
    subCategory: 'Long Head',
    primaryMuscles: ['MuscleGroup.biceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Barbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Barbell curl where elbows drive back and bar literally drags up the torso, removing front delt involvement completely.',
    setupInstructions: ['Stand tall holding barbell at thighs with shoulder-width underhand grip.'],
    executionSteps: ['Pull elbows straight backward as you curl bar up hugging the front of your torso.', 'Squeeze biceps peak at mid-chest level.', 'Lower dragging back down.'],
    coachingCues: ['Keep bar in contact with shirt throughout.', 'Elbows go behind body.'],
    commonMistakes: ['Flaring elbows wide.'],
    defaultTrainerNote: 'Eliminates front delt compensation entirely for 100% bicep focus.',
    tags: ['Biceps', 'Barbell', 'Drag Curl', 'Isolation'],
  },
  {
    id: 'ex_cable_hammer_curl',
    name: 'Standing Cable Rope Hammer Curl',
    category: 'Biceps',
    subCategory: 'Brachioradialis',
    primaryMuscles: ['MuscleGroup.brachioradialis', 'MuscleGroup.biceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Hammer curl using rope attachment on low pulley, maintaining continuous tension on forearms and outer biceps.',
    setupInstructions: ['Attach rope to low pulley.', 'Stand upright gripping rope ends with neutral palms, elbows tucked.'],
    executionSteps: ['Curl rope ends up toward shoulders.', 'Spread rope apart at top for peak contraction.', 'Lower with steady tempo.'],
    coachingCues: ['Spread rope ends at top of curl.', 'Keep upper arms motionless.'],
    commonMistakes: ['Using back momentum.'],
    defaultTrainerNote: 'Constant tension builds substantial forearm and arm thickness.',
    tags: ['Biceps', 'Cables', 'Hammer', 'Rope'],
  },
  {
    id: 'ex_high_cable_curl',
    name: 'High Cable Hercules Curl',
    category: 'Biceps',
    subCategory: 'Short Head',
    primaryMuscles: ['MuscleGroup.biceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Double biceps curl standing in center of cable crossover with pulleys set high, striking the classic bodybuilding front double-biceps pose.',
    setupInstructions: ['Set pulleys at or slightly above head height with D-handles.', 'Stand in dead center, arms outstretched in T-shape holding handles.'],
    executionSteps: ['Curl hands inward toward ears while keeping upper arms parallel to floor.', 'Squeeze biceps peak contraction.', 'Return arms to straight T-position.'],
    coachingCues: ['Keep elbows high and still.', 'Flex like on stage.'],
    commonMistakes: ['Dropping elbows toward waist.'],
    defaultTrainerNote: 'Unmatched peak contraction for the inner bicep head.',
    tags: ['Biceps', 'Cables', 'Hercules', 'Peak'],
  },

  // ==========================================
  // TRICEPS
  // ==========================================
  {
    id: 'ex_straight_bar_pushdown',
    name: 'Straight-Bar Cable Pushdown',
    category: 'Triceps',
    subCategory: 'Lateral Head',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Triceps pushdown using rigid straight bar, allowing maximal loading of the triceps lateral and medial heads.',
    setupInstructions: ['Attach straight bar to high pulley.', 'Grip overhand 6 inches apart, tuck elbows to ribs.'],
    executionSteps: ['Push bar straight down until arms are fully locked.', 'Squeeze triceps for 1 second.', 'Control bar up to 90 degrees elbow flexion.'],
    coachingCues: ['Elbows glued to side of ribcage.', 'Snap down and lock out.'],
    commonMistakes: ['Letting elbows drift forward and backward.'],
    defaultTrainerNote: 'Heaviest cable tricep movement for building raw lockout strength.',
    tags: ['Triceps', 'Cables', 'Pushdown', 'Isolation'],
  },
  {
    id: 'ex_reverse_grip_pushdown',
    name: 'Reverse-Grip Cable Pushdown',
    category: 'Triceps',
    subCategory: 'Medial Head',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Cable pushdown using an underhand (supinated) grip to emphasize the medial head of the triceps.',
    setupInstructions: ['Attach straight or EZ-bar to high cable.', 'Grip with underhand (palms up) grip shoulder-width apart, elbows tucked.'],
    executionSteps: ['Extend elbows straight down to full lockout.', 'Squeeze triceps firmly.', 'Slowly return to chest level.'],
    coachingCues: ['Drive through palms.', 'Keep wrists neutral.'],
    commonMistakes: ['Allowing wrists to bend backward.'],
    defaultTrainerNote: 'Crucial for comprehensive elbow joint integrity and medial tricep mass.',
    tags: ['Triceps', 'Cables', 'Reverse Grip', 'Medial Head'],
  },
  {
    id: 'ex_single_arm_pushdown',
    name: 'Single-Arm Cable Triceps Pushdown',
    category: 'Triceps',
    subCategory: 'Lateral & Medial Heads',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral cable pushdown eliminating bilateral strength imbalances and allowing natural wrist path.',
    setupInstructions: ['Attach single D-handle to high cable.', 'Grip handle with one hand, elbow pinned at side.'],
    executionSteps: ['Extend arm straight down to full lockout.', 'Pause for 1 second squeeze.', 'Control eccentric return.'],
    coachingCues: ['Keep shoulder down and stationary.', 'Lock elbow fully.'],
    commonMistakes: ['Using bodyweight lean to press down.'],
    defaultTrainerNote: 'Great for evening out arm measurements.',
    tags: ['Triceps', 'Cables', 'Unilateral', 'Pushdown'],
  },
  {
    id: 'ex_rope_overhead_extension',
    name: 'Rope Overhead Cable Extension',
    category: 'Triceps',
    subCategory: 'Long Head',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.coreAbs'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Overhead triceps extension facing away from high or mid cable, placing the long head under deep stretch.',
    setupInstructions: ['Attach rope to high or chest-height cable.', 'Face away from pulley, stagger stance, lean torso forward 30 degrees.'],
    executionSteps: ['Extend arms forward and overhead until elbows lock out.', 'Flare rope ends apart at full lockout.', 'Allow rope to bend back behind head under control.'],
    coachingCues: ['Keep upper arms stationary next to ears.', 'Split the rope at lockout.'],
    commonMistakes: ['Flaring elbows excessively wide.'],
    defaultTrainerNote: 'The triceps long head makes up 60% of triceps volume; overhead work is essential.',
    tags: ['Triceps', 'Cables', 'Overhead', 'Long Head'],
  },
  {
    id: 'ex_db_skull_crusher',
    name: 'Dumbbell Skull Crusher',
    category: 'Triceps',
    subCategory: 'Medial & Long Heads',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Lying triceps extension using dumbbells with neutral grip, saving elbow connective tissue compared to straight barbell.',
    setupInstructions: ['Lie flat on bench holding dumbbells with neutral palms above chest.'],
    executionSteps: ['Bend elbows lowering dumbbells to beside temples/ears.', 'Press dumbbells back up using triceps extension.'],
    coachingCues: ['Keep elbows pointed toward ceiling.', 'Do not move upper arm forward and back.'],
    commonMistakes: ['Letting elbows flare wide.'],
    defaultTrainerNote: 'Much friendlier on the triceps tendon than straight bar skull crushers.',
    tags: ['Triceps', 'Dumbbell', 'Skull Crusher', 'Lying'],
  },
  {
    id: 'ex_cross_body_cable_ext',
    name: 'Cross-Body Cable Triceps Extension',
    category: 'Triceps',
    subCategory: 'Lateral Head',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Cross-body tricep extension performed holding opposite cable rubber ball directly, aligning with the triceps line of pull without wrist torque.',
    setupInstructions: ['Set dual high pulleys without handles.', 'Grab right cable with left hand, left cable with right hand.', 'Stand upright with cables crossed in front.'],
    executionSteps: ['Extend both arms downward and outward at a 45-degree angle.', 'Squeeze triceps at full extension.', 'Return with control.'],
    coachingCues: ['Drive knuckles down and away.', 'Feel the outer tricep horseshoe.'],
    commonMistakes: ['Leaning forward aggressively.'],
    defaultTrainerNote: 'Modern biomechanics favorite for complete lateral head isolation.',
    tags: ['Triceps', 'Cables', 'Cross-Body', 'Biomechanics'],
  },
  {
    id: 'ex_tate_press',
    name: 'Tate Press',
    category: 'Triceps',
    subCategory: 'Medial & Lateral Heads',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.midChest'],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Powerlifting bench tricep press invented by Dave Tate, flaring elbows wide and rotating dumbbells out from chest.',
    setupInstructions: ['Lie on flat bench with dumbbells touching on chest, elbows flared out wide.'],
    executionSteps: ['Extend arms by pivoting forearms outward until arms lock.', 'Squeeze triceps at top.', 'Lower bells back to touch chest.'],
    coachingCues: ['Elbows stay flared.', 'Pivot around the elbow joint.'],
    commonMistakes: ['Turning into a standard bench press.'],
    defaultTrainerNote: 'Crucial for bench press lockout power.',
    tags: ['Triceps', 'Dumbbell', 'Powerlifting', 'Lockout'],
  },
  {
    id: 'ex_cable_kickback',
    name: 'Cable Triceps Kickback',
    category: 'Triceps',
    subCategory: 'Long Head',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.rearDelts'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Triceps kickback using low or mid pulley, keeping tension on the triceps even at full stretch unlike dumbbells.',
    setupInstructions: ['Set cable pulley at hip height.', 'Hinge forward at hips, upper arm pinned parallel to torso.'],
    executionSteps: ['Extend forearm straight back until arm is fully locked.', 'Squeeze triceps peak for 1 full second.', 'Lower under control to 90 degrees.'],
    coachingCues: ['Keep upper arm glued to ribs.', 'Lock out hard.'],
    commonMistakes: ['Dropping elbow between reps.'],
    defaultTrainerNote: 'Continuous cable tension makes kickbacks truly effective.',
    tags: ['Triceps', 'Cables', 'Kickback', 'Peak'],
  },

  // ==========================================
  // QUADS
  // ==========================================
  {
    id: 'ex_horizontal_leg_press',
    name: 'Horizontal Seated Leg Press',
    category: 'Quadriceps',
    subCategory: 'Quads',
    primaryMuscles: ['MuscleGroup.quads'],
    secondaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.hamstrings'],
    equipment: 'Machine',
    movementPattern: 'Squat',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Seated horizontal sled machine press with constant back support, sparing the lumbar spine.',
    setupInstructions: ['Adjust seat distance so knees are flexed 90 degrees with feet shoulder-width on footplate.'],
    executionSteps: ['Press through mid-foot and heels to slide seat backward.', 'Stop just before knees lock.', 'Return smoothly under control.'],
    coachingCues: ['Keep lower back flat against backrest.', 'Drive through full foot.'],
    commonMistakes: ['Allowing pelvis to tuck under (butt wink) at bottom.'],
    defaultTrainerNote: 'Safest leg press variant for older adults and rehabilitation clients.',
    tags: ['Quads', 'Machine', 'Leg Press', 'Rehab'],
  },
  {
    id: 'ex_single_leg_press',
    name: 'Single-Leg Press',
    category: 'Quadriceps',
    subCategory: 'Quads & Glutes',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.hamstrings'],
    equipment: 'Machine',
    movementPattern: 'Squat',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral leg press highlighting strength discrepancies and allowing deep hip flexion per side.',
    setupInstructions: ['Sit in 45-degree or horizontal leg press.', 'Place one foot centered on plate, other foot resting on floor or support.'],
    executionSteps: ['Release sled and descend until working knee reaches 90-degree flexion.', 'Drive forcefully through heel and midfoot back up.'],
    coachingCues: ['Track knee inline with second toe.', 'Do not let knee collapse inward.'],
    commonMistakes: ['Lifting hip of non-working leg off pad.'],
    defaultTrainerNote: 'Identifies and eliminates quad strength discrepancies.',
    tags: ['Quads', 'Unilateral', 'Leg Press', 'Strength'],
  },
  {
    id: 'ex_safety_bar_squat',
    name: 'Safety Bar Squat (SSB)',
    category: 'Quadriceps',
    subCategory: 'Quads & Upper Back',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.upperBack'],
    secondaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.coreAbs'],
    equipment: 'Barbell',
    movementPattern: 'Squat',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Squat using a specialty padded yoke bar with front handles, sparing shoulders and forcing upright torso posture.',
    setupInstructions: ['Rest SSB yoke comfortably on traps with handles pointing forward.', 'Hold handles lightly, set feet shoulder-width.'],
    executionSteps: ['Descend into squat while bracing upper back against the forward camber.', 'Reach parallel, then drive up through mid-foot.'],
    coachingCues: ['Fight the bar pulling your chest forward.', 'Stay upright.'],
    commonMistakes: ['Pulling down on handles instead of holding them naturally.'],
    defaultTrainerNote: 'Superior squat for athletes with shoulder mobility restrictions.',
    tags: ['Quads', 'Barbell', 'Specialty Bar', 'Squat'],
  },
  {
    id: 'ex_pause_squat',
    name: 'Pause Squat',
    category: 'Quadriceps',
    subCategory: 'Quads & Glutes',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.coreAbs', 'MuscleGroup.lowerBack'],
    equipment: 'Barbell',
    movementPattern: 'Squat',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Barbell squat holding a dead-stop pause in the hole for 2 to 3 seconds, dissipating stretch reflex.',
    setupInstructions: ['Set up standard barbell back or front squat stance.'],
    executionSteps: ['Descend to bottom of squat with full control.', 'Hold completely motionless in the hole for 2 full seconds.', 'Explode upward without bouncing.'],
    coachingCues: ['Stay tight during the pause.', 'Do not relax core at bottom.'],
    commonMistakes: ['Bouncing out of the pause.', 'Exhaling while paused in hole.'],
    defaultTrainerNote: 'Builds phenomenal starting strength and cleans up sticking points.',
    tags: ['Quads', 'Barbell', 'Pause', 'Powerlifting'],
  },

  // ==========================================
  // HAMSTRINGS
  // ==========================================
  {
    id: 'ex_standing_leg_curl',
    name: 'Standing Leg Curl',
    category: 'Hamstrings',
    subCategory: 'Hamstrings',
    primaryMuscles: ['MuscleGroup.hamstrings'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Machine',
    movementPattern: 'Hinge',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral standing hamstring curl machine isolating knee flexion with hip slightly extended.',
    setupInstructions: ['Adjust roller pad to rest on back of lower calf.', 'Place torso against support pad.'],
    executionSteps: ['Curl heel toward glute through full range of motion.', 'Hold 1 second contraction.', 'Lower slowly.'],
    coachingCues: ['Keep hips pressed against pad.', 'Point toes up.'],
    commonMistakes: ['Arching lower back to heave weight.'],
    defaultTrainerNote: 'Isolates each hamstring individually without lower back strain.',
    tags: ['Hamstrings', 'Machine', 'Unilateral', 'Curl'],
  },
  {
    id: 'ex_nordic_hamstring_curl',
    name: 'Nordic Hamstring Curl',
    category: 'Hamstrings',
    subCategory: 'Hamstrings Eccentric',
    primaryMuscles: ['MuscleGroup.hamstrings'],
    secondaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.calves'],
    equipment: 'Bodyweight',
    movementPattern: 'Hinge',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Kneeling eccentric hamstring curl lowering torso toward floor against ankle anchor, scientifically proven to prevent hamstring tears.',
    setupInstructions: ['Kneel on padded surface with ankles locked down under heavy bar or partner.', 'Keep torso in rigid line from knees to head.'],
    executionSteps: ['Lower torso forward as slowly as possible using hamstrings to resist gravity.', 'Catch yourself with hands on floor when unable to hold.', 'Push lightly off floor to reset.'],
    coachingCues: ['Do not bend at hips.', 'Resist with everything you have on descent.'],
    commonMistakes: ['Bending at hips (piking).'],
    defaultTrainerNote: 'The single most effective exercise for sprint injury prevention.',
    tags: ['Hamstrings', 'Bodyweight', 'Nordic', 'Injury Prevention'],
  },
  {
    id: 'ex_stability_ball_leg_curl',
    name: 'Stability Ball Leg Curl',
    category: 'Hamstrings',
    subCategory: 'Hamstrings & Glutes',
    primaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.coreAbs'],
    equipment: 'Other',
    movementPattern: 'Hinge',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Supine hip bridge on Swiss ball curling heels into glutes while maintaining hip extension.',
    setupInstructions: ['Lie flat on back with heels dug into top of Swiss ball, arms out at sides for balance.'],
    executionSteps: ['Bridge hips up until body forms straight line from shoulders to heels.', 'Roll ball toward glutes by bending knees and driving hips higher.', 'Extend legs back out under control.'],
    coachingCues: ['Keep hips high throughout.', 'Squeeze hamstrings at peak curl.'],
    commonMistakes: ['Dropping hips toward floor during curl.'],
    defaultTrainerNote: 'Combines hip extension with knee flexion for complete hamstring activation.',
    tags: ['Hamstrings', 'Stability Ball', 'Bridge', 'Core'],
  },
  {
    id: 'ex_slider_leg_curl',
    name: 'Slider Leg Curl',
    category: 'Hamstrings',
    subCategory: 'Hamstrings',
    primaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Bodyweight',
    movementPattern: 'Hinge',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Floor leg curl using furniture sliders or towels on smooth floor, delivering intense eccentric hamstring tension.',
    setupInstructions: ['Lie supine with heels on sliders on hardwood or turf.'],
    executionSteps: ['Bridge hips up and pull heels toward glutes along floor.', 'Extend legs back out slowly over 3 seconds.'],
    coachingCues: ['Bridge high, pull heels tight.'],
    commonMistakes: ['Letting hips sag.'],
    defaultTrainerNote: 'Great travel or home training hamstring builder.',
    tags: ['Hamstrings', 'Sliders', 'Bodyweight', 'Eccentric'],
  },

  // ==========================================
  // GLUTES
  // ==========================================
  {
    id: 'ex_db_hip_thrust',
    name: 'Bench Dumbbell Hip Thrust',
    category: 'Glutes',
    subCategory: 'Gluteus Maximus',
    primaryMuscles: ['MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.coreAbs'],
    equipment: 'Dumbbell',
    movementPattern: 'Hinge',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Hip thrust with upper back against bench and dumbbell resting across hips, easy to set up for hypertrophy reps.',
    setupInstructions: ['Upper back across bench, feet flat on floor hip-width apart.', 'Hold heavy dumbbell securely across pelvis.'],
    executionSteps: ['Drive through heels to bridge hips up until thighs and torso align horizontally.', 'Squeeze glutes hard at top for 2 seconds.', 'Lower hips toward floor.'],
    coachingCues: ['Keep chin tucked looking forward.', 'Full lockout squeeze.'],
    commonMistakes: ['Arching lower back instead of pivoting hips.'],
    defaultTrainerNote: 'Quick setup alternative to loading barbell hip thrusts.',
    tags: ['Glutes', 'Dumbbell', 'Hip Thrust', 'Hypertrophy'],
  },
  {
    id: 'ex_machine_hip_thrust',
    name: 'Machine Hip Thrust',
    category: 'Glutes',
    subCategory: 'Gluteus Maximus',
    primaryMuscles: ['MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.hamstrings'],
    equipment: 'Machine',
    movementPattern: 'Hinge',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Dedicated plate-loaded hip thrust machine with padded waist belt, allowing safe heavy loading without hip discomfort.',
    setupInstructions: ['Strap padded belt securely across pelvis.', 'Adjust footplate angle so shins are vertical at peak extension.'],
    executionSteps: ['Drive hips upward against belt to full lockout.', 'Pause for 1 second peak contraction.', 'Lower with steady control.'],
    coachingCues: ['Drive through heels.', 'Do not let knees collapse inward.'],
    commonMistakes: ['Cutting range of motion short.'],
    defaultTrainerNote: 'Superior comfort allows training to true muscular failure safely.',
    tags: ['Glutes', 'Machine', 'Hip Thrust', 'Isolation'],
  },
  {
    id: 'ex_banded_hip_abduction',
    name: 'Banded Seated Hip Abduction',
    category: 'Glutes',
    subCategory: 'Gluteus Medius',
    primaryMuscles: ['MuscleGroup.gluteMedius'],
    secondaryMuscles: ['MuscleGroup.glutes'],
    equipment: 'Resistance Band',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Seated hip abduction against looped mini-band just above knees, activating the upper glute shelf.',
    setupInstructions: ['Sit on edge of bench with mini-band wrapped around thighs above knees, feet flat on floor.'],
    executionSteps: ['Push knees outward as far as possible against band resistance.', 'Pause for 1 second.', 'Control return inward.'],
    coachingCues: ['Feel the burn in side of glutes.', 'Keep feet planted.'],
    commonMistakes: ['Letting band snap knees together.'],
    defaultTrainerNote: 'High repetition pump finisher for glute medius hypertrophy.',
    tags: ['Glutes', 'Bands', 'Abduction', 'Glute Medius'],
  },

  // ==========================================
  // CALVES / LOWER LEG
  // ==========================================
  {
    id: 'ex_leg_press_calf_raise',
    name: 'Leg Press Calf Raise',
    category: 'Calves',
    subCategory: 'Gastrocnemius',
    primaryMuscles: ['MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.tibialis'],
    equipment: 'Machine',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Calf extension with balls of feet on bottom edge of leg press platform with knees nearly straight.',
    setupInstructions: ['Sit in leg press, place balls of feet on bottom rim of plate with heels hanging off.', 'Extend sled to straight legs.'],
    executionSteps: ['Press toes forward into full plantarflexion.', 'Pause 1 second.', 'Lower heels into deep calf stretch for 2 seconds.'],
    coachingCues: ['Pause in the deep stretch.', 'Do not bounce.'],
    commonMistakes: ['Bending and extending knees into a mini leg press.'],
    defaultTrainerNote: 'Allows intense calf overload without spinal compression.',
    tags: ['Calves', 'Leg Press', 'Gastrocnemius', 'Isolation'],
  },
  {
    id: 'ex_smith_calf_raise',
    name: 'Smith Machine Standing Calf Raise',
    category: 'Calves',
    subCategory: 'Gastrocnemius',
    primaryMuscles: ['MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.tibialis'],
    equipment: 'Smith Machine',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Standing on calf block under Smith bar, driving through toes for strict calf extension.',
    setupInstructions: ['Place calf block under Smith bar.', 'Step onto block balls of feet, bar across upper traps.'],
    executionSteps: ['Lower heels deeply below block height.', 'Drive up onto tiptoes.', 'Hold peak for 1 second.'],
    coachingCues: ['Deep stretch at bottom.', 'High peak on toes.'],
    commonMistakes: ['Fast bouncy reps.'],
    defaultTrainerNote: 'Smith machine provides balance so 100% effort goes to the calves.',
    tags: ['Calves', 'Smith Machine', 'Standing', 'Hypertrophy'],
  },
  {
    id: 'ex_band_tibialis_raise',
    name: 'Band Tibialis Anterior Raise',
    category: 'Calves',
    subCategory: 'Tibialis Anterior',
    primaryMuscles: ['MuscleGroup.tibialis'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Resistance Band',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Mobility',
    description: 'Seated dorsiflexion pulling toes toward shin against resistance band, strengthening the front of the lower leg.',
    setupInstructions: ['Sit with leg extended, anchor band around post and loop other end over top of foot.'],
    executionSteps: ['Flex foot pulling toes backward toward shin as hard as possible.', 'Hold 1 second.', 'Slowly release forward.'],
    coachingCues: ['Pull toes to kneecap.', 'Feel the burn on front shin.'],
    commonMistakes: ['Moving knee instead of ankle.'],
    defaultTrainerNote: 'Proven to eliminate shin splints and improve deceleration.',
    tags: ['Calves', 'Tibialis', 'Prehab', 'Shin Splints'],
  },
  {
    id: 'ex_toe_raise',
    name: 'Standing Wall Toe Raise',
    category: 'Calves',
    subCategory: 'Tibialis Anterior',
    primaryMuscles: ['MuscleGroup.tibialis'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Bodyweight',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Mobility',
    description: 'Standing with back against wall and heels on ground, elevating toes to train anterior tibialis with bodyweight.',
    setupInstructions: ['Stand with heels 1 to 2 feet out from wall, buttocks and upper back leaning against wall.'],
    executionSteps: ['Lift toes and balls of feet as high toward shins as possible while pivoting on heels.', 'Hold for 1 second.', 'Lower.'],
    coachingCues: ['Lift toes high.', 'Pivot purely on heels.'],
    commonMistakes: ['Bending knees.'],
    defaultTrainerNote: 'Simple, effective daily knee-bulletproofing exercise.',
    tags: ['Calves', 'Tibialis', 'Bodyweight', 'Knees Over Toes'],
  },

  // ==========================================
  // ABS / CORE
  // ==========================================
  {
    id: 'ex_captains_chair_knee_raise',
    name: "Captain's Chair Knee Raise",
    category: 'Core',
    subCategory: 'Lower Abs',
    primaryMuscles: ['MuscleGroup.lowerAbs'],
    secondaryMuscles: ['MuscleGroup.hipFlexors', 'MuscleGroup.obliques'],
    equipment: 'Bodyweight',
    movementPattern: 'Anti-Extension',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Knee raise on padded dip/chair tower supporting body on forearms, isolating lower abdominal flexion.',
    setupInstructions: ['Step onto tower with forearms flat on pads, back pressed against backrest, legs hanging.'],
    executionSteps: ['Brace core and raise knees up smoothly toward chest until thighs are above parallel.', 'Tilt pelvis up slightly at top.', 'Lower legs under control.'],
    coachingCues: ['Roll pelvis upward at top of rep.', 'Do not swing legs.'],
    commonMistakes: ['Using momentum.', 'Arching lower back away from pad.'],
    defaultTrainerNote: 'Great bridge before advancing to hanging bar leg raises.',
    tags: ['Core', 'Abs', 'Tower', 'Lower Abs'],
  },
  {
    id: 'ex_cable_lift',
    name: 'Cable Diagonal Lift',
    category: 'Core',
    subCategory: 'Rotational Core',
    primaryMuscles: ['MuscleGroup.obliques', 'MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.shoulders'],
    equipment: 'Cable',
    movementPattern: 'Rotation',
    difficulty: 'Intermediate',
    exerciseType: 'Functional',
    description: 'Diagonal low-to-high core rotation lifting cable handle across torso from knee to opposite shoulder.',
    setupInstructions: ['Set cable pulley to lowest position.', 'Stand perpendicular to cable, grip handle with both hands.'],
    executionSteps: ['Rotate torso and lift arms diagonally across body up past opposite shoulder.', 'Pivot back foot smoothly.', 'Control return to starting position.'],
    coachingCues: ['Power comes from hips and core rotation.', 'Arms remain mostly straight.'],
    commonMistakes: ['Pulling purely with arms.'],
    defaultTrainerNote: 'Directly transfers to rotational athletic power in golf, baseball, and martial arts.',
    tags: ['Core', 'Rotation', 'Cables', 'Athletic'],
  },

  // ==========================================
  // FUNCTIONAL & CARRIES
  // ==========================================
  {
    id: 'ex_front_rack_carry',
    name: 'Front Rack Kettlebell Carry',
    category: 'Functional',
    subCategory: 'Loaded Carry',
    primaryMuscles: ['MuscleGroup.coreAbs', 'MuscleGroup.upperBack'],
    secondaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.shoulders', 'MuscleGroup.glutes'],
    equipment: 'Kettlebell',
    movementPattern: 'Carry',
    difficulty: 'Intermediate',
    exerciseType: 'Functional',
    description: 'Loaded carry holding kettlebells in tight front rack position, challenging thoracic extension and anterior core breathing under load.',
    setupInstructions: ['Clean two kettlebells into front rack position, elbows tucked tight to ribs, wrists straight.'],
    executionSteps: ['Walk forward with smooth, heel-to-toe strides.', 'Maintain proud chest and diaphragmatic breathing.', 'Walk prescribed distance.'],
    coachingCues: ['Do not let bells pull chest down.', 'Stand tall like a soldier.'],
    commonMistakes: ['Hyperextending lumbar spine to counter balance weight.'],
    defaultTrainerNote: 'Exceptional test of breathing under load and postural endurance.',
    tags: ['Functional', 'Kettlebell', 'Carry', 'Core'],
  },
  {
    id: 'ex_overhead_carry',
    name: 'Overhead Dumbbell/KB Carry',
    category: 'Functional',
    subCategory: 'Loaded Carry',
    primaryMuscles: ['MuscleGroup.shoulders', 'MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.traps', 'MuscleGroup.triceps'],
    equipment: 'Kettlebell',
    movementPattern: 'Carry',
    difficulty: 'Advanced',
    exerciseType: 'Functional',
    description: 'Walking with weight pressed in absolute lockout overhead, demanding supreme shoulder stability and ribcage control.',
    setupInstructions: ['Press dumbbell or kettlebell to locked overhead position.', 'Ribcage pulled down, arm close to ear.'],
    executionSteps: ['Walk forward with steady, measured steps.', 'Maintain vertical arm alignment.', 'Switch arms upon completing distance.'],
    coachingCues: ['Push up into the weight.', 'Clamp core down so ribs don\'t flare.'],
    commonMistakes: ['Bending elbow or letting weight drift forward.'],
    defaultTrainerNote: 'Elite shoulder capsule stabilizer and core anti-lateral flexion drill.',
    tags: ['Functional', 'Overhead', 'Carry', 'Stability'],
  },
  {
    id: 'ex_med_ball_throw',
    name: 'Medicine Ball Rotational Throw',
    category: 'Functional',
    subCategory: 'Rotational Power',
    primaryMuscles: ['MuscleGroup.obliques', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.coreAbs', 'MuscleGroup.shoulders'],
    equipment: 'Medicine Ball',
    movementPattern: 'Rotation',
    difficulty: 'Intermediate',
    exerciseType: 'Power',
    description: 'Explosive rotational throw slamming a medicine ball against a solid concrete or masonry wall.',
    setupInstructions: ['Stand sideways 3 to 4 feet away from solid wall holding medicine ball at back hip.'],
    executionSteps: ['Initiate power by rotating rear hip forcefully forward.', 'Follow through and launch ball against wall.', 'Catch on rebound and immediately load next rep.'],
    coachingCues: ['Throw comes from the back hip, not the arms.', 'Explode like batting a baseball.'],
    commonMistakes: ['Throwing purely with arm muscles.'],
    defaultTrainerNote: 'Builds true athletic rotational kinetic chain velocity.',
    tags: ['Functional', 'Medicine Ball', 'Power', 'Rotational'],
  },

  // ==========================================
  // CALISTHENICS PROGRESSIONS
  // ==========================================
  {
    id: 'ex_human_flag_progression',
    name: 'Human Flag Progression',
    category: 'Calisthenics',
    subCategory: 'Static Hold',
    primaryMuscles: ['MuscleGroup.obliques', 'MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.shoulders', 'MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Anti-Rotation',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Gymnastic progression suspending torso horizontally off vertical pole: bottom arm pushes, top arm pulls.',
    setupInstructions: ['Grip vertical pole with bottom hand low in push grip, top hand high in pull grip.'],
    executionSteps: ['Kick up into vertical tuck flag.', 'Extend legs gradually as isometric strength develops.', 'Hold for time.'],
    coachingCues: ['Bottom arm locks and pushes floor away, top arm pulls hard.', 'Lock side body.'],
    commonMistakes: ['Bending bottom elbow.'],
    defaultTrainerNote: 'Ultimate demonstration of lateral core and shoulder push-pull strength.',
    tags: ['Calisthenics', 'Human Flag', 'Advanced', 'Gymnastics'],
  },
  {
    id: 'ex_front_lever_progression',
    name: 'Front Lever Progression',
    category: 'Calisthenics',
    subCategory: 'Straight-Arm Pull',
    primaryMuscles: ['MuscleGroup.lats', 'MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.rearDelts', 'MuscleGroup.rhomboids'],
    equipment: 'Bodyweight',
    movementPattern: 'Vertical Pull',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Straight-arm static hold suspending body horizontally face-up beneath pull-up bar, progressing from tuck to full lever.',
    setupInstructions: ['Grip pull-up bar with overhand grip.', 'Pull down with straight arms into inverted tuck.'],
    executionSteps: ['Extend legs out into advance tuck or straddle.', 'Maintain horizontal line from shoulders to ankles.', 'Hold for 5 to 10 seconds.'],
    coachingCues: ['Pull bar down to hips with straight arms.', 'Hollow body hollow chest.'],
    commonMistakes: ['Bending elbows.', 'Dropping hips below shoulder line.'],
    defaultTrainerNote: 'Elite straight-arm lat strength and anterior core tension.',
    tags: ['Calisthenics', 'Front Lever', 'Gymnastics', 'Strength'],
  },
  {
    id: 'ex_back_lever_progression',
    name: 'Back Lever Progression',
    category: 'Calisthenics',
    subCategory: 'Straight-Arm Hold',
    primaryMuscles: ['MuscleGroup.lowerBack', 'MuscleGroup.biceps'],
    secondaryMuscles: ['MuscleGroup.rearDelts', 'MuscleGroup.glutes'],
    equipment: 'Bodyweight',
    movementPattern: 'Isometric',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Straight-arm hold suspending body horizontally face-down beneath rings or bar.',
    setupInstructions: ['Skin the cat on rings or bar into inverted hang.'],
    executionSteps: ['Lower body with straight arms until horizontal with floor.', 'Hold position with glutes clenched.'],
    coachingCues: ['Lock elbows fully, brace biceps and chest.', 'Squeeze legs together.'],
    commonMistakes: ['Dropping hips too low.'],
    defaultTrainerNote: 'Demands conditioned bicep distal tendons and strong posterior chain.',
    tags: ['Calisthenics', 'Back Lever', 'Gymnastics', 'Advanced'],
  },
  {
    id: 'ex_planche_progression',
    name: 'Planche Progression',
    category: 'Calisthenics',
    subCategory: 'Straight-Arm Push',
    primaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.upperChest'],
    secondaryMuscles: ['MuscleGroup.coreAbs', 'MuscleGroup.biceps'],
    equipment: 'Bodyweight',
    movementPattern: 'Horizontal Push',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Elite calisthenics static hold supporting entire body horizontally on hands with feet off ground without equipment support.',
    setupInstructions: ['Place hands on floor or parallettes, turn hands slightly outward.'],
    executionSteps: ['Lean shoulders far in front of wrists in protracted scapular hollow.', 'Lift feet off floor into tuck planche.', 'Hold for time.'],
    coachingCues: ['Push floor away to protract shoulder blades.', 'Lock elbows completely straight.'],
    commonMistakes: ['Bending elbows.', 'Retracting shoulder blades.'],
    defaultTrainerNote: 'Pinnacle of bodyweight straight-arm pushing power.',
    tags: ['Calisthenics', 'Planche', 'Gymnastics', 'Advanced'],
  },

  // ==========================================
  // BOXING & CONDITIONING
  // ==========================================
  {
    id: 'ex_boxing_jab',
    name: 'Boxing Jab Drill',
    category: 'Conditioning',
    subCategory: 'Boxing',
    primaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.triceps', 'MuscleGroup.calves'],
    equipment: 'Bodyweight',
    movementPattern: 'Conditioning',
    difficulty: 'Beginner',
    exerciseType: 'Endurance',
    description: 'Lead straight punch executing sharp extension with forward step and full wrist rotation.',
    setupInstructions: ['Assume boxing stance, hands protecting chin, elbows tucked.'],
    executionSteps: ['Extend lead fist straight toward target while stepping lead foot forward 2 inches.', 'Rotate palm down at impact, snap back instantly to chin.'],
    coachingCues: ['Snap it out like a whip.', 'Guard opposite cheek with rear glove.'],
    commonMistakes: ['Dropping hand before punching.', 'Overreaching.'],
    defaultTrainerNote: 'The most important offensive and defensive tool in boxing.',
    tags: ['Boxing', 'Jab', 'Conditioning', 'Speed'],
  },
  {
    id: 'ex_boxing_cross',
    name: 'Boxing Cross Drill (Rear Hand)',
    category: 'Conditioning',
    subCategory: 'Boxing',
    primaryMuscles: ['MuscleGroup.obliques', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.shoulders', 'MuscleGroup.triceps'],
    equipment: 'Bodyweight',
    movementPattern: 'Conditioning',
    difficulty: 'Beginner',
    exerciseType: 'Power',
    description: 'Power punch from the rear hand driven by hip rotation and rear foot pivot.',
    setupInstructions: ['From boxing stance, transfer weight slightly to rear foot.'],
    executionSteps: ['Pivot rear ball of foot forward, rotate hips and drive rear fist straight down centerline.', 'Snap back to guard instantly.'],
    coachingCues: ['Power comes from squashing the bug with your back foot.', 'Keep lead hand glued to cheek.'],
    commonMistakes: ['Leaning head forward over front knee.'],
    defaultTrainerNote: 'Primary knockout power punch.',
    tags: ['Boxing', 'Cross', 'Power', 'Conditioning'],
  },
  {
    id: 'ex_boxing_hook',
    name: 'Boxing Lead & Rear Hook Drills',
    category: 'Conditioning',
    subCategory: 'Boxing',
    primaryMuscles: ['MuscleGroup.obliques', 'MuscleGroup.midChest'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.glutes'],
    equipment: 'Bodyweight',
    movementPattern: 'Conditioning',
    difficulty: 'Intermediate',
    exerciseType: 'Power',
    description: 'Horizontal punch delivered at 90-degree elbow bend rotating the lead or rear hip aggressively.',
    setupInstructions: ['Boxing stance, hands high at cheekbones.'],
    executionSteps: ['Pivot lead foot 90 degrees, turning hip and shoulder as a single unit.', 'Swing hook horizontally with elbow level with fist.', 'Snap back.'],
    coachingCues: ['Turn your heel, hip, and shoulder together.', 'Keep elbow at 90 degrees.'],
    commonMistakes: ['Winding up arm backwards before punching.'],
    defaultTrainerNote: 'Develops rotational torque and midsection power.',
    tags: ['Boxing', 'Hook', 'Power', 'Conditioning'],
  },
  {
    id: 'ex_boxing_uppercut',
    name: 'Boxing Uppercut Drill',
    category: 'Conditioning',
    subCategory: 'Boxing',
    primaryMuscles: ['MuscleGroup.legs', 'MuscleGroup.biceps'],
    secondaryMuscles: ['MuscleGroup.coreAbs', 'MuscleGroup.frontDelts'],
    equipment: 'Bodyweight',
    movementPattern: 'Conditioning',
    difficulty: 'Intermediate',
    exerciseType: 'Power',
    description: 'Vertical ascending punch initiated by dropping hips slightly and driving upward into target chin.',
    setupInstructions: ['Boxing stance, slight knee dip toward punching side.'],
    executionSteps: ['Drive up through legs and hips, turning palm upward in short compact vertical arc.', 'Snap back to cheek.'],
    coachingCues: ['Short and compact; do not drop hand to hip.'],
    commonMistakes: ['Looping hand down too low.'],
    defaultTrainerNote: 'Exceptional quad and core drive punch.',
    tags: ['Boxing', 'Uppercut', 'Power', 'Conditioning'],
  },
  {
    id: 'ex_boxing_combination_drills',
    name: 'Boxing Combination 1-2-3-2 Drills',
    category: 'Conditioning',
    subCategory: 'Boxing',
    primaryMuscles: ['MuscleGroup.coreAbs', 'MuscleGroup.shoulders'],
    secondaryMuscles: ['MuscleGroup.legs', 'MuscleGroup.calves'],
    equipment: 'Bodyweight',
    movementPattern: 'Conditioning',
    difficulty: 'Intermediate',
    exerciseType: 'Endurance',
    description: 'Fluid boxing sequence: Jab (1) - Cross (2) - Lead Hook (3) - Cross (2) with continuous head movement.',
    setupInstructions: ['Boxers bounce on balls of feet, gloves high.'],
    executionSteps: ['Fire 1-2-3-2 combination with rhythm.', 'Slip or roll after sequence.', 'Reset stance.'],
    coachingCues: ['Breathe with each punch: tss-tss-tss-tss.'],
    commonMistakes: ['Holding breath.'],
    defaultTrainerNote: 'Combines anaerobic conditioning with motor skill acquisition.',
    tags: ['Boxing', 'Combinations', 'HIIT', 'Cardio'],
  },
  {
    id: 'ex_boxing_footwork_drills',
    name: 'Boxing Footwork & Pivot Drills',
    category: 'Conditioning',
    subCategory: 'Footwork',
    primaryMuscles: ['MuscleGroup.calves', 'MuscleGroup.quads'],
    secondaryMuscles: ['MuscleGroup.glutes'],
    equipment: 'Bodyweight',
    movementPattern: 'Conditioning',
    difficulty: 'Beginner',
    exerciseType: 'Cardio',
    description: 'Step-and-slide movement drill in all 4 directions maintaining consistent shoulder-width base without crossing feet.',
    setupInstructions: ['Stance check: knees soft, weight 50/50 on balls of feet.'],
    executionSteps: ['Step lead foot first when moving forward/left; step rear foot first when moving back/right.', 'Practice 45 and 90-degree pivots.'],
    coachingCues: ['Never cross your feet.', 'Stay light on your toes.'],
    commonMistakes: ['Dragging back foot or narrowing stance.'],
    defaultTrainerNote: 'Footwork separates elite strikers from novices.',
    tags: ['Boxing', 'Footwork', 'Agility', 'Conditioning'],
  },
  {
    id: 'ex_agility_ladder_drills',
    name: 'Agility Ladder Footwork Drills',
    category: 'Conditioning',
    subCategory: 'Agility',
    primaryMuscles: ['MuscleGroup.calves', 'MuscleGroup.quads'],
    secondaryMuscles: ['MuscleGroup.tibialis'],
    equipment: 'Other',
    movementPattern: 'Conditioning',
    difficulty: 'Intermediate',
    exerciseType: 'Cardio',
    description: 'Fast-feet ladder patterns (Ickey Shuffle, in-in-out-out, lateral hops) training ground contact time and CNS speed.',
    setupInstructions: ['Lay 15-foot agility ladder flat on floor.'],
    executionSteps: ['Execute rapid foot strikes through each rung.', 'Pump arms synchronously with foot speed.'],
    coachingCues: ['Stay on balls of feet.', 'Quick ground reaction.'],
    commonMistakes: ['Looking down at feet instead of ahead.'],
    defaultTrainerNote: 'Sharpens neuromuscular firing and quickness.',
    tags: ['Agility', 'Conditioning', 'Ladder', 'Speed'],
  },
  {
    id: 'ex_hill_sprints',
    name: 'Hill Sprints',
    category: 'Conditioning',
    subCategory: 'Sprints',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.glutes', 'MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Conditioning',
    difficulty: 'Advanced',
    exerciseType: 'Power',
    description: 'Maximal effort sprint up a 10 to 15-degree incline hill, reducing hamstring hamstring tear risk while building explosive power.',
    setupInstructions: ['Find steep incline (30 to 50 meters).', 'Perform thorough dynamic warm-up.'],
    executionSteps: ['Sprint 100% effort up hill with powerful arm drive and high knee drive.', 'Walk down slowly for complete recovery between sprints.'],
    coachingCues: ['Drive knees forward.', 'Pump arms aggressively.'],
    commonMistakes: ['Running down the hill (damages knees).'],
    defaultTrainerNote: 'The single best natural conditioning and power tool on earth.',
    tags: ['Conditioning', 'Sprints', 'Hill', 'Anaerobic'],
  },

  // ==========================================
  // MOBILITY & WARM-UP & COOL-DOWN
  // ==========================================
  {
    id: 'ex_hip_cars',
    name: 'Hip CARs (Controlled Articular Rotations)',
    category: 'Mobility',
    subCategory: 'Hip Joint Health',
    primaryMuscles: ['MuscleGroup.gluteMedius', 'MuscleGroup.hipFlexors'],
    secondaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Mobility',
    difficulty: 'Beginner',
    exerciseType: 'Mobility',
    description: 'Full active joint rotations taking the hip through maximum pain-free internal and external rotation on hands and knees.',
    setupInstructions: ['Quadruped position on hands and knees, brace core.'],
    executionSteps: ['Bring knee to chest, abduct out to side (fire hydrant), rotate heel up into external rotation and kick back.', 'Reverse path smoothly.'],
    coachingCues: ['Move only the hip joint; keep lower back flat.', 'Draw the largest circle possible with your knee.'],
    commonMistakes: ['Twisting spine or shifting weight excessively to side.'],
    defaultTrainerNote: 'Maintains hip longevity and lubricates synovial fluid.',
    tags: ['Mobility', 'Hip CARs', 'Hips', 'Joints'],
  },
  {
    id: 'ex_ankle_cars',
    name: 'Ankle CARs (Controlled Articular Rotations)',
    category: 'Mobility',
    subCategory: 'Ankle Mobility',
    primaryMuscles: ['MuscleGroup.tibialis', 'MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.feet'],
    equipment: 'Bodyweight',
    movementPattern: 'Mobility',
    difficulty: 'Beginner',
    exerciseType: 'Mobility',
    description: 'Maximal circular active rotations of the talocrural ankle joint while holding shin still.',
    setupInstructions: ['Seated on floor, grasp shin with both hands to block knee movement.'],
    executionSteps: ['Slowly trace the biggest possible circle with the big toe through full dorsiflexion, eversion, plantarflexion, and inversion.'],
    coachingCues: ['Make the circle slow and active.', 'Shin stays locked.'],
    commonMistakes: ['Moving the entire lower leg.'],
    defaultTrainerNote: 'Restores ankle dorsiflexion for deep squat depth.',
    tags: ['Mobility', 'Ankle CARs', 'Ankle', 'Squat Depth'],
  },
  {
    id: 'ex_scapular_cars',
    name: 'Scapular CARs',
    category: 'Mobility',
    subCategory: 'Scapulothoracic',
    primaryMuscles: ['MuscleGroup.rhomboids', 'MuscleGroup.traps'],
    secondaryMuscles: ['MuscleGroup.serratus'],
    equipment: 'Bodyweight',
    movementPattern: 'Mobility',
    difficulty: 'Beginner',
    exerciseType: 'Mobility',
    description: 'Controlled rolling of the shoulder blades through elevation, retraction, depression, and protraction with arms locked at sides.',
    setupInstructions: ['Stand tall with arms pinned to sides, core braced.'],
    executionSteps: ['Shrug shoulders up (elevation), pinch back (retraction), slide down into back pockets (depression), push forward (protraction).', 'Reverse direction.'],
    coachingCues: ['Keep elbows locked straight.', 'Isolate pure scapular glide.'],
    commonMistakes: ['Bending elbows to help shrug.'],
    defaultTrainerNote: 'Crucial warmup before benching, overhead pressing, or pull-ups.',
    tags: ['Mobility', 'Scapula', 'Shoulders', 'Warm-up'],
  },
  {
    id: 'ex_leg_swings',
    name: 'Dynamic Leg Swings (Front-to-Back & Lateral)',
    category: 'Warm-up',
    subCategory: 'Dynamic Warm-up',
    primaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.hipFlexors'],
    secondaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.adductors'],
    equipment: 'Bodyweight',
    movementPattern: 'Warm-up',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Rhythmic pendulum leg swings holding a wall, dynamically warming hamstrings, hip flexors, adductors, and abductors.',
    setupInstructions: ['Stand sideways to wall, hold wall with one hand for balance.'],
    executionSteps: ['Swing inside leg forward and back smoothly, gradually increasing amplitude for 15 reps.', 'Face wall and swing leg laterally across body.'],
    coachingCues: ['Torso stays tall.', 'Let momentum gently increase range.'],
    commonMistakes: ['Aggressively forcing range past comfort.'],
    defaultTrainerNote: 'Essential pre-squat and pre-sprint hip opener.',
    tags: ['Warm-up', 'Dynamic', 'Hips', 'Leg Swings'],
  },
  {
    id: 'ex_arm_circles',
    name: 'Dynamic Arm Circles',
    category: 'Warm-up',
    subCategory: 'Shoulder Warm-up',
    primaryMuscles: ['MuscleGroup.shoulders', 'MuscleGroup.rotatorCuff'],
    secondaryMuscles: ['MuscleGroup.upperChest', 'MuscleGroup.upperBack'],
    equipment: 'Bodyweight',
    movementPattern: 'Warm-up',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Progressive small-to-large circular arm rotations warming the glenohumeral joint and synovial capsule.',
    setupInstructions: ['Stand tall with arms extended out to sides at shoulder height.'],
    executionSteps: ['Make small circles forward for 15 seconds, expand to medium, then full windmill circles.', 'Reverse direction backward.'],
    coachingCues: ['Keep shoulders away from ears.', 'Gradually increase size of circle.'],
    commonMistakes: ['Rushing with rigid stiff arms.'],
    defaultTrainerNote: 'Basic but mandatory upper body warm-up movement.',
    tags: ['Warm-up', 'Shoulders', 'Dynamic', 'Upper Body'],
  },
  {
    id: 'ex_high_knees',
    name: 'High Knees Drill',
    category: 'Warm-up',
    subCategory: 'Cardiovascular Warm-up',
    primaryMuscles: ['MuscleGroup.hipFlexors', 'MuscleGroup.quads'],
    secondaryMuscles: ['MuscleGroup.calves', 'MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Warm-up',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Running in place with rapid cadence driving knees up to hip level, raising heart rate and warming connective tissue.',
    setupInstructions: ['Stand tall with feet hip-width on balls of feet.'],
    executionSteps: ['Drive right knee up to hip level while pumping left arm.', 'Switch rapidly in running rhythm for 30 to 45 seconds.'],
    coachingCues: ['Stay light and springy on balls of feet.', 'Knees to hip level.'],
    commonMistakes: ['Leaning backwards.'],
    defaultTrainerNote: 'Elevates core body temperature quickly.',
    tags: ['Warm-up', 'High Knees', 'Cardio', 'Athletic'],
  },
  {
    id: 'ex_butt_kicks',
    name: 'Butt Kicks Drill',
    category: 'Warm-up',
    subCategory: 'Cardiovascular Warm-up',
    primaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.quads'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Bodyweight',
    movementPattern: 'Warm-up',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Rapid cadence jogging in place kicking heels up to strike glutes, dynamically stretching the quadriceps.',
    setupInstructions: ['Stand upright, arms in running posture.'],
    executionSteps: ['Jog in place flexing knees so heels tap buttocks with quick turnover.'],
    coachingCues: ['Keep thighs vertical.', 'Quick rhythmic turnover.'],
    commonMistakes: ['Bending at waist.'],
    defaultTrainerNote: 'Prepares quads and knee joints for sprinting and squatting.',
    tags: ['Warm-up', 'Dynamic', 'Quads', 'Cardio'],
  },
  {
    id: 'ex_hamstring_sweep',
    name: 'Dynamic Hamstring Sweep',
    category: 'Warm-up',
    subCategory: 'Hamstring Flexibility',
    primaryMuscles: ['MuscleGroup.hamstrings'],
    secondaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.lowerBack'],
    equipment: 'Bodyweight',
    movementPattern: 'Warm-up',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Walking hinge reaching hands down in a scooping motion over an extended front heel.',
    setupInstructions: ['Take a step forward, place heel on floor with front leg straight and toes pulled up.'],
    executionSteps: ['Hinge at hips, sweep both hands down past shin in a scooping motion toward toes.', 'Step forward with opposite leg and repeat.'],
    coachingCues: ['Feel dynamic stretch along back of front thigh.', 'Keep spine long.'],
    commonMistakes: ['Rounding back without hip hinge.'],
    defaultTrainerNote: 'The gold standard dynamic hamstring preparation drill for athletes.',
    tags: ['Warm-up', 'Dynamic', 'Hamstrings', 'Flexibility'],
  },
  {
    id: 'ex_kneeling_hip_flexor_stretch',
    name: 'Kneeling Hip Flexor Stretch',
    category: 'Flexibility',
    subCategory: 'Hip Flexors',
    primaryMuscles: ['MuscleGroup.hipFlexors', 'MuscleGroup.quads'],
    secondaryMuscles: ['MuscleGroup.glutes'],
    equipment: 'Bodyweight',
    movementPattern: 'Flexibility',
    difficulty: 'Beginner',
    exerciseType: 'Cool-down',
    description: 'Half-kneeling static stretch tucking pelvis to release the psoas and rectus femoris tightness from heavy leg work and sitting.',
    setupInstructions: ['Half-kneeling posture with rear knee on mat, front knee at 90 degrees.'],
    executionSteps: ['Tuck pelvis into posterior pelvic tilt (squeeze rear glute).', 'Gently shift weight forward until feeling deep stretch in front of rear hip.', 'Hold 30 to 45 seconds per side with deep breathing.'],
    coachingCues: ['Squeeze the back glute to turn off the hip flexor.', 'Do not arch lower back.'],
    commonMistakes: ['Hyperextending lumbar spine.'],
    defaultTrainerNote: 'Relieves lower back compression after squats and deadlifts.',
    tags: ['Flexibility', 'Cool-down', 'Hip Flexors', 'Postural'],
  },
  {
    id: 'ex_chest_wall_stretch',
    name: 'Chest & Biceps Doorway Stretch',
    category: 'Cool-down',
    subCategory: 'Pectoral Flexibility',
    primaryMuscles: ['MuscleGroup.midChest', 'MuscleGroup.frontDelts'],
    secondaryMuscles: ['MuscleGroup.biceps'],
    equipment: 'Bodyweight',
    movementPattern: 'Cool-down',
    difficulty: 'Beginner',
    exerciseType: 'Cool-down',
    description: 'Standing in a doorway or against a power rack post with forearm resting against jamb, stepping forward to stretch chest and anterior shoulder.',
    setupInstructions: ['Stand in doorway, place forearm and elbow flat against doorframe at 90 degrees.'],
    executionSteps: ['Step forward with one leg and rotate chest gently away from frame until comfortable stretch is felt across pecs.', 'Hold 30 to 45 seconds.'],
    coachingCues: ['Keep shoulder relaxed down away from ear.', 'Breathe into the chest wall.'],
    commonMistakes: ['Shrugging shoulder upward.'],
    defaultTrainerNote: 'Ideal post-workout static stretch to open up tight anterior shoulders.',
    tags: ['Cool-down', 'Flexibility', 'Chest', 'Postural'],
  },
];
