import * as fs from 'fs';
import * as path from 'path';

export interface ExerciseEntry {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  equipment: string;
  movementPattern: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  exerciseType: string;
  description: string;
  setupInstructions: string[];
  executionSteps: string[];
  coachingCues: string[];
  commonMistakes: string[];
  defaultTrainerNote: string;
  tags: string[];
}

export const ALL_NEW_EXERCISES: ExerciseEntry[] = [
  // CHEST
  {
    id: 'ex_wide_pushup',
    name: 'Wide-Grip Push-Up',
    category: 'Chest',
    subcategory: 'Mid Chest',
    primaryMuscles: ['MuscleGroup.midChest'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.triceps', 'MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Horizontal Push',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Push-up variation with hand placement wider than shoulder-width to place greater horizontal adduction stretch and load across the pectoralis major.',
    setupInstructions: ['Assume high plank position with hands positioned 6 to 8 inches outside shoulder width.', 'Turn fingers slightly outward to protect the wrist joints.', 'Brace core and squeeze glutes to establish a rigid plank from head to heels.'],
    executionSteps: ['Lower chest toward floor by flexing elbows outward at a 45 to 60-degree angle to the torso.', 'Descend until chest is roughly an inch off the floor.', 'Press through the palms to return to full lockout while maintaining body alignment.'],
    coachingCues: ['Flare elbows no more than 60 degrees.', 'Do not allow hips to sag.', 'Feel the horizontal chest squeeze at lockout.'],
    commonMistakes: ['Flaring elbows out at 90 degrees risking shoulder impingement.', 'Hyperextending lumbar spine.', 'Shortening range of motion.'],
    defaultTrainerNote: 'Great chest finisher. Focus on a controlled 3-second eccentric stretch.',
    tags: ['Chest', 'Push-Up', 'Bodyweight', 'Pectorals'],
  },
  {
    id: 'ex_deficit_pushup',
    name: 'Deficit Push-Up',
    category: 'Chest',
    subcategory: 'Lower Chest',
    primaryMuscles: ['MuscleGroup.midChest', 'MuscleGroup.lowerChest'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.triceps'],
    equipment: 'Bodyweight',
    movementPattern: 'Horizontal Push',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Elevating hands on bumper plates, blocks, or parallettes to allow the chest to descend below hand level, producing maximum passive stretch under load.',
    setupInstructions: ['Place two sturdy blocks or bumper plates slightly wider than shoulder width.', 'Place hands firmly on elevated surfaces in plank posture.', 'Keep spine neutral and glutes clenched.'],
    executionSteps: ['Lower body with control, allowing chest to sink below the elevation of the hands.', 'Pause for 1 second in the deep stretch position without resting.', 'Drive powerfully back up to standard lockout.'],
    coachingCues: ['Sink into the stretch under control.', 'Retract scapulae deeply at the bottom.', 'Drive through palms.'],
    commonMistakes: ['Dropping head rather than lowering chest.', 'Bouncing out of the stretched position.', 'Sagging hips.'],
    defaultTrainerNote: 'Unlocks deeper chest hypertrophy. Keep shoulders packed down away from ears.',
    tags: ['Chest', 'Deficit', 'Bodyweight', 'Hypertrophy'],
  },
  {
    id: 'ex_ring_pushup',
    name: 'Ring Push-Up',
    category: 'Chest',
    subcategory: 'Mid Chest',
    primaryMuscles: ['MuscleGroup.midChest'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.triceps', 'MuscleGroup.coreAbs'],
    equipment: 'TRX',
    movementPattern: 'Horizontal Push',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Gymnastic ring push-up requiring immense shoulder and rotator cuff stabilization while allowing full convergence of hands at the top for peak contraction.',
    setupInstructions: ['Hang gymnastic rings 3 to 6 inches above floor level.', 'Grip rings firmly and step back into a plank position.', 'Turn rings slightly outward (supinated) at top for stabilization.'],
    executionSteps: ['Lower chest between the rings while maintaining steady forearm control.', 'Reach bottom position with hands near armpits.', 'Press upward and turn rings slightly outward at peak lockout while squeezing pectorals.'],
    coachingCues: ['Control ring wobble by squeezing ring handles tightly.', 'Converge hands together at the top.', 'Keep core rock solid.'],
    commonMistakes: ['Letting rings flare outwards unsafely.', 'Sagging lower back.', 'Rushing repetitions.'],
    defaultTrainerNote: 'Elite stabilizer recruitment. Keep ring straps perpendicular to floor.',
    tags: ['Calisthenics', 'Rings', 'Chest', 'Core'],
  },
  {
    id: 'ex_weighted_pushup',
    name: 'Weighted Push-Up',
    category: 'Chest',
    subcategory: 'Mid Chest',
    primaryMuscles: ['MuscleGroup.midChest'],
    secondaryMuscles: ['MuscleGroup.triceps', 'MuscleGroup.frontDelts'],
    equipment: 'Other',
    movementPattern: 'Horizontal Push',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Standard push-up overloaded using weight plates on the upper back or a weighted vest to progress horizontal pressing strength beyond bodyweight.',
    setupInstructions: ['Place weight vest on or have training partner center a weight plate directly over mid/upper back.', 'Assume rigid push-up posture with hands slightly outside shoulders.'],
    executionSteps: ['Lower chest toward floor under strict control over 2 to 3 seconds.', 'Touch chest lightly to ground without unloading tension.', 'Drive through floor to return to full arm extension.'],
    coachingCues: ['Maintain hollow body tension.', 'Keep plate steady on upper thoracic spine.'],
    commonMistakes: ['Plate sliding onto lumbar spine.', 'Shortening depth due to load.'],
    defaultTrainerNote: 'Bench press alternative with superior scapular freedom.',
    tags: ['Chest', 'Weighted', 'Strength', 'Push-Up'],
  },
  {
    id: 'ex_smith_flat_bench',
    name: 'Smith Machine Flat Bench Press',
    category: 'Chest',
    subcategory: 'Mid Chest',
    primaryMuscles: ['MuscleGroup.midChest'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.triceps'],
    equipment: 'Smith Machine',
    movementPattern: 'Horizontal Push',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Fixed-track horizontal press enabling strict pectoral isolation with zero requirement to balance the bar, allowing safe training close to failure.',
    setupInstructions: ['Position flat bench centered directly underneath the Smith bar.', 'Lie with mid-sternum aligned with the bar path.', 'Set safety pins 1 inch below chest level.'],
    executionSteps: ['Rotate wrists to unrack the bar.', 'Lower bar smoothly to touch mid-chest lightly.', 'Press bar vertically upward until arms are extended without locking elbows hard.'],
    coachingCues: ['Drive heels into floor.', 'Pull shoulder blades into bench.', 'Focus mind-muscle connection on mid chest.'],
    commonMistakes: ['Bouncing the bar off the ribcage.', 'Setting bench off-center from the track.'],
    defaultTrainerNote: 'Ideal for hypertrophy and drop-sets without needing a human spotter.',
    tags: ['Chest', 'Smith Machine', 'Hypertrophy'],
  },
  {
    id: 'ex_landmine_press_standing',
    name: 'Standing Landmine Press',
    category: 'Chest',
    subcategory: 'Upper Chest',
    primaryMuscles: ['MuscleGroup.upperChest', 'MuscleGroup.frontDelts'],
    secondaryMuscles: ['MuscleGroup.triceps', 'MuscleGroup.coreAbs'],
    equipment: 'Barbell',
    movementPattern: 'Incline Push',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Angled pressing movement that follows an arc, providing upper chest and anterior deltoid stimulation that is exceptionally joint-friendly for the shoulder.',
    setupInstructions: ['Insert one end of barbell into a landmine pivot or corner.', 'Stand with feet staggered or hip-width apart holding the sleeve end at upper chest level.'],
    executionSteps: ['Press the barbell up and forward along its natural diagonal arc.', 'Reach full extension while reaching forward slightly through the serratus.', 'Lower under control back to chest level.'],
    coachingCues: ['Press up and out at roughly 45 degrees.', 'Keep core braced to avoid leaning backward.'],
    commonMistakes: ['Hyperextending lumbar spine.', 'Dropping bar too quickly.'],
    defaultTrainerNote: 'Outstanding for athletes with shoulder impingement from traditional overhead pressing.',
    tags: ['Chest', 'Shoulders', 'Landmine', 'Functional'],
  },

  // BACK
  {
    id: 'ex_neutral_lat_pulldown',
    name: 'Neutral-Grip Lat Pulldown',
    category: 'Back',
    subcategory: 'Lats',
    primaryMuscles: ['MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.rhomboids'],
    equipment: 'Cable',
    movementPattern: 'Vertical Pull',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Lat pulldown using a parallel/neutral grip attachment, placing shoulders in optimal plane for latissimus dorsi mechanical advantage and reduced wrist strain.',
    setupInstructions: ['Attach V-bar or neutral grip attachment to high pulley.', 'Adjust thigh pad so legs are locked firmly in place.', 'Grip handles with palms facing each other.'],
    executionSteps: ['Lean back slightly (10 to 15 degrees) with chest lifted.', 'Drive elbows down and back toward your hip pockets.', 'Pull until attachment reaches upper chest, squeezing lats.', 'Extend arms smoothly back to full overhead stretch.'],
    coachingCues: ['Lead with the elbows, not hands.', 'Chest high, lats spread wide at top.'],
    commonMistakes: ['Excessive swinging of torso.', 'Pulling too low down onto belly.'],
    defaultTrainerNote: 'Fantastic for lat width. Pause 1 second at full contraction.',
    tags: ['Back', 'Lats', 'Cable', 'Neutral Grip'],
  },
  {
    id: 'ex_single_arm_cable_row',
    name: 'Single-Arm Cable Row',
    category: 'Back',
    subcategory: 'Lats',
    primaryMuscles: ['MuscleGroup.lats', 'MuscleGroup.rhomboids'],
    secondaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.coreAbs'],
    equipment: 'Cable',
    movementPattern: 'Horizontal Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral cable row allowing full rotational freedom of the wrist and maximum range of motion to stretch and contract the lats individually.',
    setupInstructions: ['Set cable pulley at mid-torso height with a single D-handle.', 'Step back into athletic stance or sit with feet braced.'],
    executionSteps: ['Allow arm to extend forward to feel a full lat stretch around ribcage.', 'Drive elbow backward close to your side while rotating palm from neutral to supinated.', 'Squeeze lat fully at the back, avoiding torso over-rotation.'],
    coachingCues: ['Drive elbow past ribcage.', 'Keep torso steady with minimal twisting.'],
    commonMistakes: ['Rotating torso excessively to heave the weight.', 'Shrugging shoulder up to ear.'],
    defaultTrainerNote: 'Fixes left/right strength imbalances and enhances mind-muscle connection.',
    tags: ['Back', 'Unilateral', 'Lats', 'Cable'],
  },
  {
    id: 'ex_seal_row',
    name: 'Seal Row',
    category: 'Back',
    subcategory: 'Upper Back',
    primaryMuscles: ['MuscleGroup.rhomboids', 'MuscleGroup.traps', 'MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.rearDelts'],
    equipment: 'Barbell',
    movementPattern: 'Horizontal Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Prone row performed lying flat on an elevated bench, completely eliminating lower back momentum and isolating the mid-back musculature.',
    setupInstructions: ['Lie face down on an elevated horizontal bench with barbell underneath.', 'Grip bar with double overhand grip slightly wider than shoulders.'],
    executionSteps: ['Pull barbell vertically up until it contacts the underside of the bench.', 'Retract shoulder blades and hold peak contraction for 1 second.', 'Lower bar under strict control until arms are fully elongated.'],
    coachingCues: ['Keep chest pinned to bench throughout.', 'Squeeze mid-back as if pinching a pencil.'],
    commonMistakes: ['Lifting chest off bench.', 'Jerking the neck upward.'],
    defaultTrainerNote: 'Pure upper back hypertrophy with zero lumbar spinal strain.',
    tags: ['Back', 'Upper Back', 'Barbell', 'Seal Row'],
  },
  {
    id: 'ex_rack_pull',
    name: 'Rack Pull',
    category: 'Back',
    subcategory: 'Traps',
    primaryMuscles: ['MuscleGroup.traps', 'MuscleGroup.lowerBack'],
    secondaryMuscles: ['MuscleGroup.lats', 'MuscleGroup.glutes', 'MuscleGroup.forearms'],
    equipment: 'Barbell',
    movementPattern: 'Hip Hinge',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Partial deadlift initiated with barbell elevated on power rack pins just below knee height, overloading the upper back, traps, and hip lockout.',
    setupInstructions: ['Set rack safety pins so barbell rests just below kneecaps.', 'Step up to bar with hip-width stance, grip bar overhand or hook grip.'],
    executionSteps: ['Hinge at hips, brace core, pull slack out of bar.', 'Drive hips forward and extend spine to pull bar to full erect lockout.', 'Squeeze glutes and upper back, then lower with control to rack pins.'],
    coachingCues: ['Pack lats tight against ribs.', 'Drive hips into the bar at lockout.'],
    commonMistakes: ['Hyperextending lumbar spine at top.', 'Bouncing violently off the pins.'],
    defaultTrainerNote: 'Builds dense upper back and trap thickness with huge overload capability.',
    tags: ['Back', 'Traps', 'Deadlift', 'Strength'],
  },
  {
    id: 'ex_dumbbell_pullover',
    name: 'Dumbbell Pullover',
    category: 'Back',
    subcategory: 'Lats',
    primaryMuscles: ['MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.upperChest', 'MuscleGroup.triceps'],
    equipment: 'Dumbbell',
    movementPattern: 'Vertical Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Classic exercise performed lying across or along a flat bench, stretching the lats and serratus anterior through a long overhead arc.',
    setupInstructions: ['Lie perpendicular across a flat bench with upper back supported.', 'Hold dumbbell cupped between both palms directly over chest.'],
    executionSteps: ['Keeping a slight bend in elbows, lower dumbbell in an arc back behind your head.', 'Descend until feeling a deep stretch across the lats and ribcage.', 'Contract lats to pull dumbbell back over chest.'],
    coachingCues: ['Keep hips slightly dipped to anchor the stretch.', 'Maintain consistent elbow angle.'],
    commonMistakes: ['Bending elbows into a triceps extension.', 'Excessive arching of lower back.'],
    defaultTrainerNote: 'Incredible lat stretch and ribcage expansion movement.',
    tags: ['Back', 'Lats', 'Dumbbell', 'Pullover'],
  },
  {
    id: 'ex_barbell_pullover',
    name: 'Barbell Pullover',
    category: 'Back',
    subcategory: 'Lats',
    primaryMuscles: ['MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.upperChest', 'MuscleGroup.triceps'],
    equipment: 'Barbell',
    movementPattern: 'Vertical Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Long-arc lat pullovers utilizing an EZ or straight barbell to provide strict bilateral tension through full overhead extension.',
    setupInstructions: ['Lie supine along a flat bench holding barbell with shoulder-width overhand grip above chest.'],
    executionSteps: ['Lower barbell backward behind head in a controlled arc, feeling deep lat stretch.', 'Reverse movement by engaging lats to bring barbell back upright.'],
    coachingCues: ['Keep elbows slightly bent and fixed in position.', 'Inhale on the stretch, exhale on the pull.'],
    commonMistakes: ['Dropping bar too low past shoulder mobility limit.'],
    defaultTrainerNote: 'Use moderate weight and focus on maximum stretch tension.',
    tags: ['Back', 'Lats', 'Barbell', 'Pullover'],
  },

  // SHOULDERS
  {
    id: 'ex_smith_shoulder_press',
    name: 'Smith Machine Shoulder Press',
    category: 'Shoulders',
    subcategory: 'Front Delts',
    primaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.sideDelts'],
    secondaryMuscles: ['MuscleGroup.triceps', 'MuscleGroup.traps'],
    equipment: 'Smith Machine',
    movementPattern: 'Vertical Push',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Seated overhead press within the guided path of the Smith machine, maximizing deltoid overload without balance requirements.',
    setupInstructions: ['Set upright bench (75–80 degrees) centered under Smith bar.', 'Sit with back flat against pad, grip bar slightly wider than shoulders.'],
    executionSteps: ['Unrack bar, lower smoothly to chin/upper collarbone level.', 'Press bar vertically overhead until elbows are nearly extended.'],
    coachingCues: ['Keep wrists stacked over elbows.', 'Avoid fully locking out elbows to keep deltoid tension constant.'],
    commonMistakes: ['Arching lower back off the pad.', 'Pressing with elbows flared too far back.'],
    defaultTrainerNote: 'Excellent for safe shoulder hypertrophy and high-rep finisher sets.',
    tags: ['Shoulders', 'Delts', 'Smith Machine', 'Press'],
  },
  {
    id: 'ex_machine_lateral_raise',
    name: 'Machine Lateral Raise',
    category: 'Shoulders',
    subcategory: 'Side Delts',
    primaryMuscles: ['MuscleGroup.sideDelts'],
    secondaryMuscles: ['MuscleGroup.traps'],
    equipment: 'Machine',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Seated shoulder abduction machine providing constant resistance curve throughout the range of motion for lateral deltoid growth.',
    setupInstructions: ['Adjust seat height so shoulder joints align with machine pivot axes.', 'Place outer elbows against padded lever arms.'],
    executionSteps: ['Drive elbows up and outward until upper arms are parallel to the floor.', 'Pause for 1 second at top.', 'Lower under control for 2 to 3 seconds.'],
    coachingCues: ['Lead with elbows, keep hands relaxed.', 'Keep shoulders down away from ears.'],
    commonMistakes: ['Shrugging traps to raise arms.', 'Setting seat too low or high.'],
    defaultTrainerNote: 'Superior continuous tension compared to standard dumbbells at the bottom.',
    tags: ['Shoulders', 'Side Delts', 'Machine', 'Isolation'],
  },
  {
    id: 'ex_cable_front_raise',
    name: 'Cable Front Raise',
    category: 'Shoulders',
    subcategory: 'Front Delts',
    primaryMuscles: ['MuscleGroup.frontDelts'],
    secondaryMuscles: ['MuscleGroup.upperChest'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Low-pulley anterior deltoid raise ensuring continuous tension from starting stretch to top horizontal contraction.',
    setupInstructions: ['Set low pulley with straight bar or single handle.', 'Stand facing away with cable passing between legs.'],
    executionSteps: ['Raise arms forward in an arc until parallel with floor.', 'Hold peak contraction briefly.', 'Lower smoothly to thighs.'],
    coachingCues: ['Keep torso rigid without swinging.', 'Knuckles facing ceiling.'],
    commonMistakes: ['Using momentum from hips.'],
    defaultTrainerNote: 'Great for anterior deltoid isolation.',
    tags: ['Shoulders', 'Front Delts', 'Cable'],
  },
  {
    id: 'ex_dumbbell_y_raise',
    name: 'Dumbbell Y-Raise',
    category: 'Shoulders',
    subcategory: 'Side Delts',
    primaryMuscles: ['MuscleGroup.sideDelts', 'MuscleGroup.traps'],
    secondaryMuscles: ['MuscleGroup.rearDelts'],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Raise dumbbells in a 30-degree forward angled Y-shape along the scapular plane, optimally targeting side delts and lower traps.',
    setupInstructions: ['Lie chest-down on 30–45 degree incline bench holding light dumbbells with thumbs pointing up.'],
    executionSteps: ['Raise dumbbells outward and upward at roughly 45-degree angle in a Y-formation.', 'Squeeze lower traps and lateral delts at top.', 'Lower with strict control.'],
    coachingCues: ['Thumbs pointing toward ceiling.', 'Think reaching long into the corners.'],
    commonMistakes: ['Using excessively heavy weights.', 'Bending arms into a row.'],
    defaultTrainerNote: 'Essential for shoulder health and 3D deltoid development.',
    tags: ['Shoulders', 'Y-Raise', 'Scapular', 'Dumbbell'],
  },
  {
    id: 'ex_cuban_press',
    name: 'Cuban Press',
    category: 'Shoulders',
    subcategory: 'Rear Delts',
    primaryMuscles: ['MuscleGroup.rearDelts', 'MuscleGroup.shoulders'],
    secondaryMuscles: ['MuscleGroup.traps', 'MuscleGroup.triceps'],
    equipment: 'Dumbbell',
    movementPattern: 'Rotational Push',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Combined upright row, external shoulder rotation, and overhead press building bulletproof rotator cuff and shoulder girdle resilience.',
    setupInstructions: ['Stand upright holding light dumbbells at thighs.'],
    executionSteps: ['Perform upright row until upper arms are parallel to floor.', 'Rotate forearms upward 90 degrees while keeping elbows pinned in place.', 'Press dumbbells overhead to full extension.', 'Reverse the sequence precisely back to start.'],
    coachingCues: ['Keep weights light.', 'Smooth rotation without elbow dropping.'],
    commonMistakes: ['Lifting heavy and jerking during external rotation.'],
    defaultTrainerNote: 'Unmatched prehab exercise for overhead athletes and lifters.',
    tags: ['Shoulders', 'Rotator Cuff', 'Cuban Press', 'Prehab'],
  },
  {
    id: 'ex_external_rotation_cable',
    name: 'Cable Shoulder External Rotation',
    category: 'Shoulders',
    subcategory: 'Rotator Cuff',
    primaryMuscles: ['MuscleGroup.rearDelts'],
    secondaryMuscles: ['MuscleGroup.traps'],
    equipment: 'Cable',
    movementPattern: 'Rotation',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Isolating infraspinatus and teres minor to balance internal rotators and stabilize the humeral head.',
    setupInstructions: ['Set cable pulley at elbow height.', 'Stand sideways to pulley holding handle with outer hand, elbow pinned at 90 degrees with a towel roll under armpit.'],
    executionSteps: ['Rotate forearm outward away from body while keeping elbow glued to your side.', 'Squeeze rotator cuff at full outward rotation.', 'Slowly return to start.'],
    coachingCues: ['Do not let elbow drift away from ribs.', 'Controlled 2-second eccentric.'],
    commonMistakes: ['Twisting torso instead of rotating shoulder.'],
    defaultTrainerNote: 'Crucial rotator cuff prehab for heavy benchers.',
    tags: ['Shoulders', 'Rotator Cuff', 'Prehab', 'Mobility'],
  },
  {
    id: 'ex_internal_rotation_cable',
    name: 'Cable Shoulder Internal Rotation',
    category: 'Shoulders',
    subcategory: 'Rotator Cuff',
    primaryMuscles: ['MuscleGroup.frontDelts'],
    secondaryMuscles: ['MuscleGroup.midChest'],
    equipment: 'Cable',
    movementPattern: 'Rotation',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Isolating the subscapularis muscle to maintain balanced rotator cuff tension and shoulder joint integrity.',
    setupInstructions: ['Set cable pulley at elbow height.', 'Stand sideways with inner arm holding handle, elbow bent 90 degrees.'],
    executionSteps: ['Rotate forearm inward across abdomen while keeping elbow pinned to side.', 'Hold 1 second then return under control.'],
    coachingCues: ['Keep wrist straight and elbow tucked.'],
    commonMistakes: ['Jerking weight across with body lean.'],
    defaultTrainerNote: 'Complements external rotations for complete shoulder stability.',
    tags: ['Shoulders', 'Rotator Cuff', 'Prehab'],
  },
  {
    id: 'ex_rear_delt_row',
    name: 'Dumbbell Rear Delt Row',
    category: 'Shoulders',
    subcategory: 'Rear Delts',
    primaryMuscles: ['MuscleGroup.rearDelts'],
    secondaryMuscles: ['MuscleGroup.traps', 'MuscleGroup.rhomboids'],
    equipment: 'Dumbbell',
    movementPattern: 'Horizontal Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Chest-supported dumbbell row with elbows flared out at 70 to 80 degrees, isolating posterior deltoids without lat takeover.',
    setupInstructions: ['Lie chest-down on an incline bench set to 30 degrees holding dumbbells with palms facing feet.'],
    executionSteps: ['Row dumbbells up with elbows flared wide in line with shoulders.', 'Hold peak contraction for 1 second feeling rear deltoid squeeze.', 'Lower smoothly to full extension.'],
    coachingCues: ['Flared elbows are key to hitting the rear delts.', 'Lead with outer elbows.'],
    commonMistakes: ['Tucking elbows into ribs which shifts load to lats.'],
    defaultTrainerNote: 'Essential for balanced 3D shoulder shape and upper back posture.',
    tags: ['Shoulders', 'Rear Delts', 'Dumbbell', 'Row'],
  },

  // BICEPS & TRICEPS
  {
    id: 'ex_drag_curl',
    name: 'Barbell Drag Curl',
    category: 'Biceps',
    subcategory: 'Biceps Long Head',
    primaryMuscles: ['MuscleGroup.biceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Barbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Biceps curl where the bar is dragged straight up the torso by pulling elbows back, eliminating front delt assistance and maximizing biceps peak contraction.',
    setupInstructions: ['Stand upright holding barbell with shoulder-width underhand grip.'],
    executionSteps: ['Drag barbell straight up along line of your shirt/torso by driving elbows straight back.', 'Curl upward as high as possible while keeping bar skimming body.', 'Squeeze biceps peak intensely, then lower along same path.'],
    coachingCues: ['Pull elbows backward as bar rises.', 'Never let bar drift forward away from torso.'],
    commonMistakes: ['Swinging bar forward.', 'Leaning back.'],
    defaultTrainerNote: 'Pure biceps isolation that takes the front delts completely out of the equation.',
    tags: ['Biceps', 'Drag Curl', 'Barbell', 'Arms'],
  },
  {
    id: 'ex_zottman_curl',
    name: 'Zottman Curl',
    category: 'Biceps',
    subcategory: 'Forearms / Brachialis',
    primaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.forearms'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Hybrid arm curl performing the concentric phase with palms up (supinated) and the eccentric phase with palms down (pronated) to overload brachioradialis.',
    setupInstructions: ['Stand holding dumbbells at sides with palms facing forward.'],
    executionSteps: ['Curl dumbbells up supinated to shoulder level.', 'At peak contraction, rotate wrists 180 degrees so palms face downward.', 'Lower dumbbells slowly over 3 seconds in the pronated position.', 'Rotate palms forward at the bottom.'],
    coachingCues: ['Supinate on the way up, pronate on the way down.', 'Resist the descent.'],
    commonMistakes: ['Rushing the eccentric lowering phase.'],
    defaultTrainerNote: 'Best 2-in-1 exercise for complete biceps and forearm hypertrophy.',
    tags: ['Biceps', 'Forearms', 'Dumbbell', 'Zottman'],
  },
  {
    id: 'ex_high_cable_curl',
    name: 'High Cable Biceps Curl',
    category: 'Biceps',
    subcategory: 'Biceps Short Head',
    primaryMuscles: ['MuscleGroup.biceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Double biceps pose curl performed between high cable pulleys, isolating the short inner head under sustained tension.',
    setupInstructions: ['Stand centered in dual cable crossover station with pulleys set above head height holding D-handles.'],
    executionSteps: ['Curl handles toward ears while keeping upper arms strictly parallel to floor.', 'Squeeze peak biceps contraction for 1 second.', 'Extend arms under control back toward pulleys.'],
    coachingCues: ['Keep upper arms locked parallel to floor.', 'Squeeze as if posing on stage.'],
    commonMistakes: ['Dropping elbows toward torso.'],
    defaultTrainerNote: 'Elite peak contraction exercise. Great for mind-muscle connection.',
    tags: ['Biceps', 'Cable', 'Isolation', 'Arms'],
  },
  {
    id: 'ex_reverse_pushdown',
    name: 'Reverse-Grip Triceps Pushdown',
    category: 'Triceps',
    subcategory: 'Medial Head',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Triceps extension with an underhand (supinated) grip, focusing mechanical tension on the medial head of the triceps.',
    setupInstructions: ['Attach straight bar or EZ-bar to high cable pulley.', 'Grip with underhand (palms up) grip at shoulder width.'],
    executionSteps: ['Pin elbows to sides.', 'Push bar downward until arms are fully locked out.', 'Return bar slowly to upper chest level.'],
    coachingCues: ['Keep elbows tucked.', 'Squeeze triceps hard at bottom.'],
    commonMistakes: ['Letting wrists bend backward excessively.'],
    defaultTrainerNote: 'Builds medial head triceps thickness and forearm grip stability.',
    tags: ['Triceps', 'Reverse Grip', 'Cable'],
  },
  {
    id: 'ex_jm_press',
    name: 'JM Press',
    category: 'Triceps',
    subcategory: 'Lateral / Long Head',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.midChest', 'MuscleGroup.frontDelts'],
    equipment: 'Barbell',
    movementPattern: 'Compound Push',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Powerlifting hybrid of close-grip bench press and skull crusher, enabling massive overload on the triceps tendon and lockout power.',
    setupInstructions: ['Lie on flat bench holding barbell with shoulder-width overhand grip directly over clavicles.'],
    executionSteps: ['Lower bar directly toward the throat/upper chest while allowing elbows to travel down and forward.', 'Pause 1 inch above neck/clavicle.', 'Drive bar back up through triceps extension to lockout.'],
    coachingCues: ['Lower toward the neck, not sternum.', 'Keep wrists firm and locked.'],
    commonMistakes: ['Turning it into a standard close grip press.'],
    defaultTrainerNote: 'The gold standard for bench press lockout triceps power.',
    tags: ['Triceps', 'Barbell', 'Strength', 'Powerlifting'],
  },
  {
    id: 'ex_bench_dip',
    name: 'Bench Dip',
    category: 'Triceps',
    subcategory: 'Triceps',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.midChest'],
    equipment: 'Bench',
    movementPattern: 'Vertical Push',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Triceps bodyweight dip performed with hands braced on a bench behind the body and legs extended forward.',
    setupInstructions: ['Place hands shoulder-width apart on edge of bench, fingers forward.', 'Extend legs in front with heels on floor.'],
    executionSteps: ['Lower hips toward floor by bending elbows to 90 degrees.', 'Press through palms to return to full arm extension.'],
    coachingCues: ['Keep back skimming close to bench.', 'Do not sink past 90 degrees.'],
    commonMistakes: ['Shrugging shoulders into ears.'],
    defaultTrainerNote: 'Beginner-friendly triceps builder that can be weighted as strength increases.',
    tags: ['Triceps', 'Bench', 'Bodyweight'],
  },
  {
    id: 'ex_tate_press',
    name: 'Tate Press',
    category: 'Triceps',
    subcategory: 'Lateral Head',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.frontDelts'],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Elbow-out dumbbell triceps extension on a flat bench specifically targeting the lateral head of the triceps.',
    setupInstructions: ['Lie flat on bench holding dumbbells above chest with elbows flared outward and bells touching.'],
    executionSteps: ['Bend elbows inward and downward to touch dumbbells lightly to chest.', 'Extend elbows outward and upward back to starting position.'],
    coachingCues: ['Keep elbows flared out wide.', 'Press with triceps.'],
    commonMistakes: ['Turning it into a dumbbell bench press.'],
    defaultTrainerNote: 'Outstanding for triceps lateral head sweep.',
    tags: ['Triceps', 'Dumbbell', 'Tate Press'],
  },
  {
    id: 'ex_rope_overhead_extension',
    name: 'Rope Overhead Cable Extension',
    category: 'Triceps',
    subcategory: 'Long Head',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Overhead triceps extension with rope attachment placing the long head of the triceps in full stretch under continuous cable tension.',
    setupInstructions: ['Attach rope to high or low pulley, turn facing away, bring rope overhead with elbows bent.'],
    executionSteps: ['Extend elbows overhead, spreading rope ends apart at full lockout.', 'Lower slowly behind head until feeling deep triceps stretch.'],
    coachingCues: ['Spread rope apart at the top.', 'Keep elbows pointed forward.'],
    commonMistakes: ['Flaring elbows wide.'],
    defaultTrainerNote: 'Maximum long head triceps stretch. Keep ribcage down.',
    tags: ['Triceps', 'Cable', 'Overhead', 'Long Head'],
  },
  {
    id: 'ex_cable_kickback',
    name: 'Cable Triceps Kickback',
    category: 'Triceps',
    subcategory: 'Lateral Head',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral triceps extension using a cable pulley to deliver peak contraction at the shortened end-range without drop in tension.',
    setupInstructions: ['Set cable pulley at knee height, remove handle and grip ball end.', 'Hinge forward with upper arm parallel to floor.'],
    executionSteps: ['Extend elbow backward until arm is completely straight.', 'Hold peak contraction for 1 second.', 'Lower forearm to 90 degrees.'],
    coachingCues: ['Lock upper arm horizontal.', 'Squeeze triceps at full lockout.'],
    commonMistakes: ['Swinging upper arm like a pendulum.'],
    defaultTrainerNote: 'Fixes the dead zone of dumbbell kickbacks.',
    tags: ['Triceps', 'Cable', 'Kickback'],
  },

  // QUADRICEPS & LEGS
  {
    id: 'ex_belt_squat',
    name: 'Belt Squat',
    category: 'Quadriceps',
    subcategory: 'Quads',
    primaryMuscles: ['MuscleGroup.quads'],
    secondaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.hamstrings'],
    equipment: 'Machine',
    movementPattern: 'Squat',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Squat machine loading hips directly via weight belt, loading quads and glutes with zero axial compression on the spine.',
    setupInstructions: ['Strap dip belt around hips and hook to belt squat lever/cable.', 'Stand with shoulder-width stance on elevated platform.'],
    executionSteps: ['Squat down until thighs reach parallel with floor.', 'Drive through full foot to stand upright.'],
    coachingCues: ['Keep torso upright.', 'Drive through mid-foot and heels.'],
    commonMistakes: ['Rounding lower back at bottom.'],
    defaultTrainerNote: 'Elite leg development tool especially when recovering from lower back fatigue.',
    tags: ['Quads', 'Belt Squat', 'Machine', 'Legs'],
  },
  {
    id: 'ex_safety_bar_squat',
    name: 'Safety Bar Squat',
    category: 'Quadriceps',
    subcategory: 'Quads',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.lowerBack', 'MuscleGroup.coreAbs'],
    equipment: 'Barbell',
    movementPattern: 'Squat',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Squat using a cambered safety squat bar with front handles, encouraging an upright torso and removing shoulder mobility limitations.',
    setupInstructions: ['Step under padded safety bar, resting yolk across shoulders.', 'Grip front handles lightly.'],
    executionSteps: ['Descend into squat keeping torso upright against camber pull.', 'Reach parallel depth and drive upward through heels.'],
    coachingCues: ['Keep chest proud against the camber.', 'Do not pull down on the handles.'],
    commonMistakes: ['Pulling handles down to cheat the weight.'],
    defaultTrainerNote: 'Builds extraordinary quad strength and upper back endurance.',
    tags: ['Quads', 'Safety Bar', 'Squat', 'Legs'],
  },
  {
    id: 'ex_zercher_squat',
    name: 'Zercher Squat',
    category: 'Quadriceps',
    subcategory: 'Quads',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.traps'],
    equipment: 'Barbell',
    movementPattern: 'Squat',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Squat holding barbell in the crook of the elbows, recruiting immense anterior core, upper back, and quadriceps drive.',
    setupInstructions: ['Rack barbell at elbow height.', 'Cradle barbell in crooks of bent elbows with hands clasped together.'],
    executionSteps: ['Squat deeply between knees until elbows travel between thighs.', 'Drive through floor to full standing lockout.'],
    coachingCues: ['Stay upright, brace core intensely.', 'Squeeze fists together.'],
    commonMistakes: ['Caving chest forward under weight.'],
    defaultTrainerNote: 'Old-school brute strength exercise for bulletproof posture.',
    tags: ['Quads', 'Core', 'Zercher', 'Barbell'],
  },
  {
    id: 'ex_box_squat',
    name: 'Box Squat',
    category: 'Quadriceps',
    subcategory: 'Quads',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.lowerBack'],
    equipment: 'Barbell',
    movementPattern: 'Squat',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Squat sitting back onto a sturdy box to break the eccentric-concentric chain and develop explosive rate of force development.',
    setupInstructions: ['Place box at parallel height behind squat rack.', 'Unrack barbell with shoulder-width stance.'],
    executionSteps: ['Hinge hips and sit back onto box with control.', 'Pause 1 second without relaxing core or rocking.', 'Explode upward by driving heels through floor.'],
    coachingCues: ['Sit back, do not drop down.', 'Stay tight on the box.'],
    commonMistakes: ['Rocking forward or bouncing off the box.'],
    defaultTrainerNote: 'Reinforces proper hip hinge mechanics and squat depth.',
    tags: ['Quads', 'Box Squat', 'Barbell', 'Strength'],
  },
  {
    id: 'ex_pause_squat',
    name: 'Pause Squat',
    category: 'Quadriceps',
    subcategory: 'Quads',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.coreAbs'],
    equipment: 'Barbell',
    movementPattern: 'Squat',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Barbell squat holding a full 2-second pause in the hole to eliminate stretch reflex and build raw starting strength.',
    setupInstructions: ['Setup in standard back squat position.'],
    executionSteps: ['Descend below parallel under control.', 'Hold motionless in the hole for 2 full seconds while maintaining full intra-abdominal brace.', 'Drive upward explosively to lockout.'],
    coachingCues: ['Own the bottom position.', 'Do not relax at the pause.'],
    commonMistakes: ['Bouncing slightly during the pause.'],
    defaultTrainerNote: 'The ultimate cure for sticking points in the squat.',
    tags: ['Quads', 'Pause Squat', 'Barbell'],
  },
  {
    id: 'ex_horizontal_leg_press',
    name: 'Horizontal Leg Press',
    category: 'Quadriceps',
    subcategory: 'Quads',
    primaryMuscles: ['MuscleGroup.quads'],
    secondaryMuscles: ['MuscleGroup.glutes'],
    equipment: 'Machine',
    movementPattern: 'Squat',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Seated horizontal sled or selectorized leg press allowing joint-friendly quad overload with upright back support.',
    setupInstructions: ['Sit with back flat against backrest and feet hip-width on footplate.'],
    executionSteps: ['Release safety stop, lower footplate by flexing knees to 90 degrees.', 'Press through midfoot to extend knees without hard hyperextension.'],
    coachingCues: ['Keep lower back glued to pad.', 'Do not lock knees violently.'],
    commonMistakes: ['Lifting hips off the seat at deep knee flexion.'],
    defaultTrainerNote: 'Safe quad hypertrophy builder for all experience levels.',
    tags: ['Quads', 'Leg Press', 'Machine'],
  },
  {
    id: 'ex_single_leg_press',
    name: 'Single-Leg Press',
    category: 'Quadriceps',
    subcategory: 'Quads',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.hamstrings'],
    equipment: 'Machine',
    movementPattern: 'Unilateral Squat',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral leg press highlighting quadriceps and glute imbalances while minimizing pelvic torsion.',
    setupInstructions: ['Position one foot centered on leg press footplate, other foot resting safely on floor platform.'],
    executionSteps: ['Lower weight sled smoothly until working knee reaches 90-degree flexion.', 'Drive through heel and midfoot to return to start.'],
    coachingCues: ['Track working knee over second toe.', 'Maintain square pelvis on backrest.'],
    commonMistakes: ['Letting working knee collapse inward.'],
    defaultTrainerNote: 'Essential for athletic symmetry and unilateral strength.',
    tags: ['Quads', 'Unilateral', 'Leg Press'],
  },

  // HAMSTRINGS & POSTERIOR CHAIN
  {
    id: 'ex_sumo_deadlift',
    name: 'Sumo Deadlift',
    category: 'Hamstrings',
    subcategory: 'Glutes / Hips',
    primaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.quads'],
    secondaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.lowerBack', 'MuscleGroup.traps'],
    equipment: 'Barbell',
    movementPattern: 'Hip Hinge',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Wide-stance deadlift with hands gripping inside legs, shortening moment arm and emphasizing glute, hip adductor, and quad recruitment.',
    setupInstructions: ['Take wide stance with toes pointed outward toward plates.', 'Grip bar inside shins with straight arms.'],
    executionSteps: ['Pull chest tall, wedge hips close to bar.', 'Drive knees out and push floor away with feet.', 'Lock out hips and knees simultaneously.'],
    coachingCues: ['Spread the floor with your feet.', 'Wedge hips in before initiating pull.'],
    commonMistakes: ['Letting knees cave inward.'],
    defaultTrainerNote: 'Exceptional for powerlifting and developing hip power.',
    tags: ['Deadlift', 'Sumo', 'Glutes', 'Strength'],
  },
  {
    id: 'ex_trap_bar_deadlift',
    name: 'Trap-Bar Deadlift (Hex Bar)',
    category: 'Hamstrings',
    subcategory: 'Posterior Chain',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.lowerBack', 'MuscleGroup.traps'],
    equipment: 'Trap Bar',
    movementPattern: 'Hip Hinge',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Deadlift inside a hexagonal bar with neutral handles, centering load directly along body axis to minimize lumbar shear stress.',
    setupInstructions: ['Step inside hex bar, feet hip-width apart.', 'Grip neutral handles, brace core, and flatten spine.'],
    executionSteps: ['Drive through heels, extending hips and knees evenly.', 'Lock out hips tall at the top.', 'Hinge back down with control.'],
    coachingCues: ['Push ground away.', 'Chest up tall.'],
    commonMistakes: ['Rounding back upon lift-off.'],
    defaultTrainerNote: 'Safest, most efficient heavy hinge pattern for athletic performance.',
    tags: ['Deadlift', 'Trap Bar', 'Strength', 'Legs'],
  },
  {
    id: 'ex_single_leg_rdl',
    name: 'Single-Leg Romanian Deadlift',
    category: 'Hamstrings',
    subcategory: 'Hamstrings',
    primaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.calves', 'MuscleGroup.coreAbs'],
    equipment: 'Dumbbell',
    movementPattern: 'Hip Hinge',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral hip hinge balancing on one foot while reaching opposite leg straight back, building dynamic balance and hamstring stretch strength.',
    setupInstructions: ['Hold dumbbell in hand opposite to standing leg, balance on working foot.'],
    executionSteps: ['Hinge forward at hip, extending back leg straight behind as a counter-balance.', 'Lower dumbbell along shin until hamstring is fully stretched.', 'Squeeze glute and hamstring to pull torso upright.'],
    coachingCues: ['Keep hips square to floor.', 'Reach heel to back wall.'],
    commonMistakes: ['Opening hips outward toward ceiling.'],
    defaultTrainerNote: 'The gold standard unilateral hamstring and ankle stability test.',
    tags: ['Hamstrings', 'Unilateral', 'RDL', 'Balance'],
  },
  {
    id: 'ex_glute_ham_raise',
    name: 'Glute-Ham Raise (GHR)',
    category: 'Hamstrings',
    subcategory: 'Hamstrings',
    primaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.calves', 'MuscleGroup.lowerBack'],
    equipment: 'Machine',
    movementPattern: 'Isolation',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Posterior chain machine exercise flexing the knee while extending the hip, building bulletproof hamstring strength against sprinting tears.',
    setupInstructions: ['Secure feet in GHR footplate with thighs supported on curved thigh pad.', 'Start in horizontal alignment.'],
    executionSteps: ['Lower torso forward by extending knees until body is horizontal.', 'Pull with hamstrings to flex knees and return body upright.'],
    coachingCues: ['Maintain straight line through hips.', 'Do not bend at waist.'],
    commonMistakes: ['Breaking at the hips on the way up.'],
    defaultTrainerNote: 'The #1 movement for hamstring injury prevention and athletic speed.',
    tags: ['Hamstrings', 'Glutes', 'GHR', 'Posterior Chain'],
  },
  {
    id: 'ex_standing_leg_curl',
    name: 'Standing Leg Curl',
    category: 'Hamstrings',
    subcategory: 'Hamstrings',
    primaryMuscles: ['MuscleGroup.hamstrings'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Machine',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral standing hamstring curl machine isolating knee flexion one leg at a time.',
    setupInstructions: ['Adjust machine pad against lower calf just above Achilles tendon.', 'Support torso against front pad.'],
    executionSteps: ['Curl working heel up toward glute.', 'Hold peak contraction for 1 second.', 'Lower smoothly over 2 to 3 seconds.'],
    coachingCues: ['Do not arch lower back.', 'Squeeze hamstring at peak height.'],
    commonMistakes: ['Swinging torso backward.'],
    defaultTrainerNote: 'Isolates each hamstring cleanly without spinal involvement.',
    tags: ['Hamstrings', 'Leg Curl', 'Machine'],
  },
  {
    id: 'ex_stability_ball_leg_curl',
    name: 'Stability Ball Hamstring Curl',
    category: 'Hamstrings',
    subcategory: 'Hamstrings',
    primaryMuscles: ['MuscleGroup.hamstrings'],
    secondaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.coreAbs'],
    equipment: 'Other',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Floor bridge on a Swiss ball curling heels toward glutes while maintaining an elevated hip bridge.',
    setupInstructions: ['Lie supine with heels resting on top of stability ball, arms flat on floor for balance.'],
    executionSteps: ['Bridge hips upward into a straight line.', 'Pull heels toward glutes rolling ball inward.', 'Extend legs back out without letting hips drop to floor.'],
    coachingCues: ['Keep hips high throughout.', 'Squeeze hamstrings as ball approaches glutes.'],
    commonMistakes: ['Dropping hips to floor during curl.'],
    defaultTrainerNote: 'Great home or gym bodyweight hamstring burner.',
    tags: ['Hamstrings', 'Stability Ball', 'Core'],
  },

  // GLUTES
  {
    id: 'ex_dumbbell_hip_thrust',
    name: 'Dumbbell Hip Thrust',
    category: 'Glutes',
    subcategory: 'Glutes',
    primaryMuscles: ['MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.hamstrings'],
    equipment: 'Dumbbell',
    movementPattern: 'Hip Hinge',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Hip thrust with upper back against a bench and a heavy dumbbell resting across hips for glute hypertrophy.',
    setupInstructions: ['Rest upper shoulder blades across a sturdy bench.', 'Place dumbbell across hip crease with knees bent at 90 degrees.'],
    executionSteps: ['Lower hips toward floor by hinging at pelvis.', 'Drive through heels to extend hips until thighs and torso form a straight table.', 'Hold peak glute contraction 1 full second at top.'],
    coachingCues: ['Tuck chin to chest.', 'Squeeze glutes at top without hyperextending lumbar spine.'],
    commonMistakes: ['Hyperextending lower back at top.'],
    defaultTrainerNote: 'More accessible and faster to set up than the barbell version.',
    tags: ['Glutes', 'Hip Thrust', 'Dumbbell'],
  },
  {
    id: 'ex_machine_hip_thrust',
    name: 'Machine Hip Thrust',
    category: 'Glutes',
    subcategory: 'Glutes',
    primaryMuscles: ['MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.hamstrings'],
    equipment: 'Machine',
    movementPattern: 'Hip Hinge',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Dedicated selectorized or plate-loaded hip thrust machine with a padded belt or bar locking hips into optimal trajectory.',
    setupInstructions: ['Fasten padded seatbelt tightly over hip crease, set feet shoulder-width on platform.'],
    executionSteps: ['Drive hips upward against resistance pad until fully locked out.', 'Pause for 2 seconds at top.', 'Lower hips smoothly to bottom stretch.'],
    coachingCues: ['Drive through heels.', 'Focus pure mind-muscle connection on gluteus maximus.'],
    commonMistakes: ['Rushing the repetition speed.'],
    defaultTrainerNote: 'Zero setup friction and maximum glute isolation.',
    tags: ['Glutes', 'Machine', 'Hip Thrust'],
  },
  {
    id: 'ex_single_leg_glute_bridge',
    name: 'Single-Leg Glute Bridge',
    category: 'Glutes',
    subcategory: 'Glutes',
    primaryMuscles: ['MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Hip Hinge',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral floor glute bridge isolating gluteal activation and correcting hip extension asymmetries.',
    setupInstructions: ['Lie supine with one knee bent and foot flat on floor, opposite leg lifted toward ceiling.'],
    executionSteps: ['Drive through working heel to elevate hips until thigh aligns with torso.', 'Squeeze glute hard at top for 2 seconds.', 'Lower under control.'],
    coachingCues: ['Keep hips level.', 'Do not arch lower back.'],
    commonMistakes: ['Pushing through toes instead of heel.'],
    defaultTrainerNote: 'Great activation drill prior to heavy squats and deadlifts.',
    tags: ['Glutes', 'Unilateral', 'Activation', 'Bodyweight'],
  },
  {
    id: 'ex_banded_hip_abduction',
    name: 'Banded Hip Abduction (Monster Walk)',
    category: 'Glutes',
    subcategory: 'Glute Medius',
    primaryMuscles: ['MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.quads'],
    equipment: 'Resistance Band',
    movementPattern: 'Abduction',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Loop resistance band above knees or ankles and walk laterally or diagonally to activate the gluteus medius and improve knee tracking.',
    setupInstructions: ['Place mini resistance band around thighs above knees, assume athletic quarter-squat.'],
    executionSteps: ['Take deliberate lateral steps pushing knees outward against the band resistance.', 'Maintain constant band tension without letting knees cave inward.'],
    coachingCues: ['Keep toes pointed forward.', 'Do not let knees cave.'],
    commonMistakes: ['Dragging feet or standing too upright.'],
    defaultTrainerNote: 'Essential warm-up movement to fire the glute medius before squatting.',
    tags: ['Glutes', 'Band', 'Warm-up', 'Abduction'],
  },
  {
    id: 'ex_curtsy_lunge',
    name: 'Curtsy Lunge',
    category: 'Glutes',
    subcategory: 'Glute Medius',
    primaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.quads'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Dumbbell',
    movementPattern: 'Lunge',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Lunge stepping back and across the midline to dynamically stretch and recruit the gluteus medius and adductors.',
    setupInstructions: ['Stand upright holding dumbbells at sides or bodyweight.'],
    executionSteps: ['Step rear leg back and across behind front leg in a curtsy motion.', 'Lower hips until front thigh is parallel to floor.', 'Push through front heel to return to standing.'],
    coachingCues: ['Keep front knee tracked over foot.', 'Chest upright.'],
    commonMistakes: ['Stepping too far sideways twisting the front knee.'],
    defaultTrainerNote: 'Shapes the outer glutes and builds rotational hip control.',
    tags: ['Glutes', 'Lunge', 'Curtsy', 'Dumbbell'],
  },
  {
    id: 'ex_sumo_squat_dumbbell',
    name: 'Dumbbell Sumo Squat',
    category: 'Glutes',
    subcategory: 'Glutes / Adductors',
    primaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.quads'],
    secondaryMuscles: ['MuscleGroup.hamstrings'],
    equipment: 'Dumbbell',
    movementPattern: 'Squat',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Wide-stance squat holding a heavy dumbbell vertically between legs, emphasizing gluteus maximus stretch and inner thigh adductor recruitment.',
    setupInstructions: ['Take a wide stance with toes pointed outward at 45 degrees, holding dumbbell vertically by the head.'],
    executionSteps: ['Descend hips straight down between legs while tracking knees wide over toes.', 'Reach parallel depth, pause, and drive through heels to standing.'],
    coachingCues: ['Knees push wide.', 'Torso stays tall and upright.'],
    commonMistakes: ['Leaning too far forward.'],
    defaultTrainerNote: 'Incredible glute and adductor builder with minimal spinal load.',
    tags: ['Glutes', 'Sumo', 'Squat', 'Dumbbell'],
  },

  // CALVES
  {
    id: 'ex_tibialis_raise',
    name: 'Tibialis Anterior Raise',
    category: 'Calves',
    subcategory: 'Shin / Tibialis',
    primaryMuscles: ['MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Bodyweight',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Prehab',
    description: 'Dorsiflexion exercise strengthening the tibialis anterior on the front of the shin to prevent shin splints and absorb knee landing shock.',
    setupInstructions: ['Stand with back against a wall, feet placed 1 to 2 feet in front.'],
    executionSteps: ['Pull toes and forefoot up toward shins as high as possible while balancing on heels.', 'Hold for 1 second at peak contraction.', 'Lower toes smoothly back to floor.'],
    coachingCues: ['Pull toes to the ceiling.', 'Feel the burn on the front of the shin.'],
    commonMistakes: ['Bending knees during the movement.'],
    defaultTrainerNote: 'Essential for runners, basketball players, and knee bulletproofing.',
    tags: ['Calves', 'Tibialis', 'Prehab', 'Knee Health'],
  },
  {
    id: 'ex_single_leg_calf_raise',
    name: 'Single-Leg Calf Raise',
    category: 'Calves',
    subcategory: 'Gastrocnemius',
    primaryMuscles: ['MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Bodyweight',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral calf raise performed off an elevated step to correct left/right ankle imbalances and maximize deep gastrocnemius stretch.',
    setupInstructions: ['Stand on edge of step on ball of one foot holding a support lightly for balance.'],
    executionSteps: ['Lower heel down into deep calf stretch.', 'Press through big toe ball to maximum height.', 'Pause at peak contraction.'],
    coachingCues: ['2 second stretch at the bottom.', 'Drive through the ball of the foot.'],
    commonMistakes: ['Bouncing rapidly.'],
    defaultTrainerNote: 'Builds calf symmetry and Achilles tendon resilience.',
    tags: ['Calves', 'Unilateral', 'Bodyweight'],
  },
  {
    id: 'ex_donkey_calf_raise',
    name: 'Donkey Calf Raise',
    category: 'Calves',
    subcategory: 'Gastrocnemius',
    primaryMuscles: ['MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Machine',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Hinged calf raise with hips bent at 90 degrees, pre-stretching the hamstrings and placing the gastrocnemius under maximum mechanical tension.',
    setupInstructions: ['Step onto calf block, hinge hips forward at 90 degrees with pad or weight secured over sacrum/hips.'],
    executionSteps: ['Lower heels deeply into maximum dorsiflexion.', 'Drive onto balls of feet into full plantarflexion, holding peak 1 second.'],
    coachingCues: ['Full stretch, full contraction.', 'Keep legs straight.'],
    commonMistakes: ['Bending knees to assist the lift.'],
    defaultTrainerNote: 'Arnold Schwarzenegger favorite for legendary calf thickness.',
    tags: ['Calves', 'Donkey Calf', 'Machine'],
  },
  {
    id: 'ex_smith_calf_raise',
    name: 'Smith Machine Standing Calf Raise',
    category: 'Calves',
    subcategory: 'Gastrocnemius',
    primaryMuscles: ['MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Smith Machine',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Heavy calf raise performed on a step block inside the Smith machine, allowing immense overload with zero balance distraction.',
    setupInstructions: ['Place calf block under Smith bar, rest bar across upper traps with balls of feet on block.'],
    executionSteps: ['Drop heels down below block into a deep stretch.', 'Explode onto toes, hold peak squeeze for 1 second, then lower slowly for 3 seconds.'],
    coachingCues: ['Do not bounce off the stretch.', 'Squeeze calves like flexing for a photo.'],
    commonMistakes: ['Rushing reps with short range of motion.'],
    defaultTrainerNote: 'Ideal for heavy progressive overload on the gastrocnemius.',
    tags: ['Calves', 'Smith Machine', 'Heavy'],
  },
  {
    id: 'ex_leg_press_calf_raise',
    name: 'Leg Press Calf Press',
    category: 'Calves',
    subcategory: 'Gastrocnemius',
    primaryMuscles: ['MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Machine',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Calf press performed on the 45-degree leg press with balls of feet on the lower edge of the footplate.',
    setupInstructions: ['Sit on leg press with legs almost straight (soft knees), balls of feet on bottom edge of platform, heels free.'],
    executionSteps: ['Let weight push platform down into deep ankle dorsiflexion.', 'Press platform away using calves into full plantarflexion.'],
    coachingCues: ['Keep knees soft, do not lock out.', 'Focus purely on ankle hinge.'],
    commonMistakes: ['Bending and pressing with knees.'],
    defaultTrainerNote: 'High loading capacity without any axial spinal compression.',
    tags: ['Calves', 'Leg Press', 'Machine'],
  },

  // ABS / CORE
  {
    id: 'ex_ab_machine_crunch',
    name: 'Machine Abdominal Crunch',
    category: 'Core',
    subcategory: 'Upper Abs',
    primaryMuscles: ['MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.coreAbs'],
    equipment: 'Machine',
    movementPattern: 'Spinal Flexion',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Seated selectorized crunch machine enabling progressive overload for rectus abdominis hypertrophy.',
    setupInstructions: ['Adjust seat so chest pad aligns with upper sternum.', 'Place feet behind ankle rollers.'],
    executionSteps: ['Curl ribcage down toward pelvis by contracting abdominals.', 'Exhale completely at peak crunch.', 'Return slowly to starting stretch.'],
    coachingCues: ['Think ribs to hips.', 'Do not push with your legs.'],
    commonMistakes: ['Using momentum or pushing with hip flexors.'],
    defaultTrainerNote: 'Best machine for safely loading the rectus abdominis.',
    tags: ['Core', 'Abs', 'Machine', 'Crunch'],
  },
  {
    id: 'ex_bicycle_crunch',
    name: 'Bicycle Crunch',
    category: 'Core',
    subcategory: 'Obliques',
    primaryMuscles: ['MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Rotation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Alternating rotation and flexion bringing opposite elbow to knee, recruiting high rectus abdominis and obliques activation.',
    setupInstructions: ['Lie supine with lower back pressed into floor, hands behind ears.'],
    executionSteps: ['Bring left knee to right elbow while extending left leg straight.', 'Switch smoothly to opposite side in a bicycling rhythm.'],
    coachingCues: ['Rotate through torso, not neck.', 'Keep lower back glued down.'],
    commonMistakes: ['Pulling on the back of the neck.'],
    defaultTrainerNote: 'High electromyographic activation for all abdominal sections.',
    tags: ['Core', 'Abs', 'Obliques', 'Bodyweight'],
  },
  {
    id: 'ex_captains_chair_knee_raise',
    name: "Captain's Chair Knee Raise",
    category: 'Core',
    subcategory: 'Lower Abs',
    primaryMuscles: ['MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.coreAbs'],
    equipment: 'Machine',
    movementPattern: 'Spinal Flexion',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Forearm-supported vertical knee raise curling the pelvis toward the chest without grip fatigue.',
    setupInstructions: ['Step into Captains Chair, support forearms on pads, grip handles, back flat against pad.'],
    executionSteps: ['Raise knees smoothly toward chest, curling pelvis upward at the top.', 'Hold for 1 second, then lower under control.'],
    coachingCues: ['Curl pelvis up toward chin.', 'Do not swing legs.'],
    commonMistakes: ['Swinging legs with momentum.'],
    defaultTrainerNote: 'Excellent for targeting lower abdominal fibers.',
    tags: ['Core', 'Abs', 'Lower Abs'],
  },
  {
    id: 'ex_rkc_plank',
    name: 'RKC Hardstyle Plank',
    category: 'Core',
    subcategory: 'Anti-Extension',
    primaryMuscles: ['MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.lats'],
    equipment: 'Bodyweight',
    movementPattern: 'Isometric',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'High-intensity isometric plank generating 100% maximal tension by actively pulling elbows toward toes and clenching glutes.',
    setupInstructions: ['Assume forearm plank with fists clenched tightly and feet together.'],
    executionSteps: ['Contract glutes, quads, and abs 100%.', 'Actively pull elbows down toward toes and pull toes up toward elbows without moving.', 'Hold maximum tension for 10 to 20 seconds.'],
    coachingCues: ['Create a full-body earthquake of tension.', 'Breathe behind the shield.'],
    commonMistakes: ['Relaxing into a passive hold.'],
    defaultTrainerNote: '10 seconds of RKC plank creates more core stiffness than 2 minutes of passive planking.',
    tags: ['Core', 'Plank', 'Hardstyle', 'Isometric'],
  },
  {
    id: 'ex_hollow_body_hold',
    name: 'Hollow Body Hold',
    category: 'Core',
    subcategory: 'Anti-Extension',
    primaryMuscles: ['MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.quads'],
    equipment: 'Bodyweight',
    movementPattern: 'Isometric',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Fundamental gymnastics shape pressing lower back into the floor while arms and legs are held extended in a crescent banana posture.',
    setupInstructions: ['Lie flat on back, press lumbar spine completely flush against the floor.'],
    executionSteps: ['Extend arms overhead by ears and lift legs 4 to 6 inches off floor.', 'Keep lower back glued to floor while holding rigid hollow body.'],
    coachingCues: ['No daylight under the lower back.', 'Point toes, squeeze knees.'],
    commonMistakes: ['Arching lower back off floor.'],
    defaultTrainerNote: 'The foundation of gymnastics core stability and calisthenics control.',
    tags: ['Core', 'Hollow Body', 'Calisthenics'],
  },
  {
    id: 'ex_v_up',
    name: 'V-Up',
    category: 'Core',
    subcategory: 'Rectus Abdominis',
    primaryMuscles: ['MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Spinal Flexion',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Simultaneous upper torso and leg raise touching fingers to toes at peak height while balancing on glutes.',
    setupInstructions: ['Lie supine with arms stretched overhead and legs straight together.'],
    executionSteps: ['Simultaneously lift legs and torso off floor, meeting hands to toes in a V-formation.', 'Lower back down under control without letting heels touch floor.'],
    coachingCues: ['Touch toes at the top.', 'Smooth controlled descent.'],
    commonMistakes: ['Bending knees excessively.'],
    defaultTrainerNote: 'Demands tremendous core compression and coordination.',
    tags: ['Core', 'Abs', 'V-Up', 'Bodyweight'],
  },
  {
    id: 'ex_cable_woodchop',
    name: 'Cable Woodchopper',
    category: 'Core',
    subcategory: 'Obliques / Rotation',
    primaryMuscles: ['MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.shoulders'],
    equipment: 'Cable',
    movementPattern: 'Rotation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Diagonal rotational cable pull from high to low or low to high recruiting the internal and external obliques.',
    setupInstructions: ['Set cable pulley at shoulder or high level, stand sideways gripping handle with both hands.'],
    executionSteps: ['Rotate torso diagonally across body while pivoting rear foot.', 'Control return back to starting position without letting cable yank body.'],
    coachingCues: ['Rotate with hips and torso, not just arms.', 'Pivot the back foot.'],
    commonMistakes: ['Bending arms and using shoulder strength.'],
    defaultTrainerNote: 'Functional rotational power drill for athletes.',
    tags: ['Core', 'Obliques', 'Cable', 'Rotational'],
  },
  {
    id: 'ex_mountain_climber',
    name: 'Mountain Climber',
    category: 'Core',
    subcategory: 'Cardio / Core',
    primaryMuscles: ['MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.shoulders', 'MuscleGroup.calves'],
    equipment: 'Bodyweight',
    movementPattern: 'Conditioning',
    difficulty: 'Beginner',
    exerciseType: 'Conditioning',
    description: 'Dynamic plank driving alternating knees to chest at rapid pace to build core endurance and cardiovascular conditioning.',
    setupInstructions: ['Assume high plank position with shoulders stacked over wrists.'],
    executionSteps: ['Drive one knee rapidly up toward chest, tap toe or hover, then switch legs in a running cadence.'],
    coachingCues: ['Keep hips level with shoulders.', 'Pace breathing with foot speed.'],
    commonMistakes: ['Bouncing hips up in the air.'],
    defaultTrainerNote: 'Fantastic conditioning and core endurance drill.',
    tags: ['Core', 'Conditioning', 'Cardio', 'Bodyweight'],
  },

  // FUNCTIONAL & CALISTHENICS
  {
    id: 'ex_kettlebell_clean',
    name: 'Kettlebell Clean',
    category: 'Functional',
    subcategory: 'Hinge / Clean',
    primaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.hamstrings'],
    secondaryMuscles: ['MuscleGroup.traps', 'MuscleGroup.forearms', 'MuscleGroup.coreAbs'],
    equipment: 'Kettlebell',
    movementPattern: 'Hip Hinge',
    difficulty: 'Intermediate',
    exerciseType: 'Power',
    description: 'Explosive hip extension lifting kettlebell from between legs into the front rack position without banging the forearm.',
    setupInstructions: ['Stand behind kettlebell with feet slightly wider than hips.'],
    executionSteps: ['Hinge hips, hike bell between legs, and snap hips forward explosively.', 'Keep bell close to body like zipping a jacket.', 'Catch bell smoothly in rack position against chest and forearm.'],
    coachingCues: ['Snap hips forward.', 'Tame the arc; keep bell close.'],
    commonMistakes: ['Letting bell swing far out and slam into forearm.'],
    defaultTrainerNote: 'Foundation for kettlebell presses, squats, and Olympic clean progressions.',
    tags: ['Functional', 'Kettlebell', 'Clean', 'Power'],
  },
  {
    id: 'ex_kettlebell_snatch',
    name: 'Kettlebell Snatch',
    category: 'Functional',
    subcategory: 'Snatch',
    primaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.hamstrings', 'MuscleGroup.shoulders'],
    secondaryMuscles: ['MuscleGroup.traps', 'MuscleGroup.coreAbs'],
    equipment: 'Kettlebell',
    movementPattern: 'Hip Hinge',
    difficulty: 'Advanced',
    exerciseType: 'Power',
    description: 'Continuous ballistic swing launching kettlebell from between legs directly to an overhead lockout in one seamless motion.',
    setupInstructions: ['Hike kettlebell backward between legs in athletic hinge.'],
    executionSteps: ['Drive hips forward explosively.', 'Guide bell upward vertically, punch hand through handle at the top into lockout.'],
    coachingCues: ['Punch upward into the bell at top.', 'Absorb landing smoothly on eccentric.'],
    commonMistakes: ['Allowing bell to flop over wrist.'],
    defaultTrainerNote: 'Supreme cardiovascular, power, and posterior chain conditioner.',
    tags: ['Functional', 'Kettlebell', 'Snatch', 'Conditioning'],
  },
  {
    id: 'ex_handstand_pushup',
    name: 'Handstand Push-Up',
    category: 'Functional',
    subcategory: 'Inverted Press',
    primaryMuscles: ['MuscleGroup.shoulders', 'MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.upperChest', 'MuscleGroup.traps', 'MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Vertical Push',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Elite calisthenics vertical pressing exercise pushing entire bodyweight from inverted position against a wall or freestanding.',
    setupInstructions: ['Kick up into handstand against a smooth wall with hands 6 inches out.'],
    executionSteps: ['Lower crown of head forward to touch floor forming a tripod with hands.', 'Press through palms to return to full arm lockout.'],
    coachingCues: ['Elbows at 45 degrees.', 'Maintain tight hollow body.'],
    commonMistakes: ['Flaring elbows out to 90 degrees.'],
    defaultTrainerNote: 'Pinnacle of calisthenics shoulder pressing power.',
    tags: ['Calisthenics', 'Handstand', 'Shoulders', 'Advanced'],
  },
  {
    id: 'ex_pike_pushup',
    name: 'Pike Push-Up',
    category: 'Functional',
    subcategory: 'Vertical Push',
    primaryMuscles: ['MuscleGroup.shoulders', 'MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.upperChest', 'MuscleGroup.traps'],
    equipment: 'Bodyweight',
    movementPattern: 'Vertical Push',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Push-up performed with hips piked high in inverted V-shape, shifting bodyweight onto shoulders as a lead-up to handstands.',
    setupInstructions: ['Start in downward dog position with hips high and hands shoulder-width.'],
    executionSteps: ['Lower head forward toward floor between hands.', 'Press through shoulders and triceps back to pike lockout.'],
    coachingCues: ['Look slightly forward, head touches ahead of hands.', 'Keep hips stacked high.'],
    commonMistakes: ['Flaring elbows out sideways.'],
    defaultTrainerNote: 'Best regression for building toward full handstand push-ups.',
    tags: ['Calisthenics', 'Pike', 'Shoulders', 'Push-Up'],
  },
  {
    id: 'ex_muscle_up',
    name: 'Bar Muscle-Up',
    category: 'Functional',
    subcategory: 'Calisthenics Compound',
    primaryMuscles: ['MuscleGroup.lats', 'MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.midChest', 'MuscleGroup.biceps', 'MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Compound',
    difficulty: 'Advanced',
    exerciseType: 'Power',
    description: 'Explosive vertical pull transitioning over the pull-up bar directly into a straight-bar dip lockout.',
    setupInstructions: ['Grip pull-up bar with false grip or standard overhand grip.'],
    executionSteps: ['Perform explosive pull-up aiming sternum to bar.', 'Transition chest over bar by rolling wrists forward.', 'Press to full straight-bar dip lockout.'],
    coachingCues: ['Pull high and fast.', 'Throw head and shoulders over the bar.'],
    commonMistakes: ['Kicking legs unevenly (chicken winging).'],
    defaultTrainerNote: 'Master strict high pull-ups and straight bar dips first.',
    tags: ['Calisthenics', 'Muscle-Up', 'Pull-Up', 'Advanced'],
  },
  {
    id: 'ex_l_sit',
    name: 'L-Sit Hold',
    category: 'Core',
    subcategory: 'Compression',
    primaryMuscles: ['MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.triceps'],
    equipment: 'Bodyweight',
    movementPattern: 'Isometric',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Isometric gymnastics hold supporting body on parallel bars or floor with legs extended horizontally at 90 degrees.',
    setupInstructions: ['Place hands on parallettes or floor, depress shoulders to push floor away.'],
    executionSteps: ['Lift feet and extend legs completely straight out in front.', 'Hold position for desired seconds while breathing steadily.'],
    coachingCues: ['Push shoulders down away from ears.', 'Lock knees and point toes.'],
    commonMistakes: ['Bending knees prematurely.'],
    defaultTrainerNote: 'Unrivaled hip flexor and abdominal compression strength.',
    tags: ['Core', 'L-Sit', 'Calisthenics', 'Isometric'],
  },
  {
    id: 'ex_front_rack_carry',
    name: 'Kettlebell Front Rack Carry',
    category: 'Functional',
    subcategory: 'Loaded Carry',
    primaryMuscles: ['MuscleGroup.coreAbs', 'MuscleGroup.traps'],
    secondaryMuscles: ['MuscleGroup.shoulders', 'MuscleGroup.glutes'],
    equipment: 'Kettlebell',
    movementPattern: 'Loaded Carry',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Walking while carrying two kettlebells in the front rack position against the chest, testing postural and core endurance.',
    setupInstructions: ['Clean two kettlebells into front rack position, elbows pinned close.'],
    executionSteps: ['Walk forward in deliberate heel-to-toe strides with tall posture.', 'Breathe calmly without allowing elbows to drop.'],
    coachingCues: ['Stand tall, brace abs.', 'Keep elbows tucked tight.'],
    commonMistakes: ['Leaning backward to balance bells.'],
    defaultTrainerNote: 'Exceptional loaded carry for thoracic extension and abdominal stiffness.',
    tags: ['Functional', 'Carry', 'Kettlebell', 'Core'],
  },
  {
    id: 'ex_overhead_carry',
    name: 'Overhead Dumbbell/Kettlebell Carry',
    category: 'Functional',
    subcategory: 'Loaded Carry',
    primaryMuscles: ['MuscleGroup.shoulders', 'MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.traps', 'MuscleGroup.triceps'],
    equipment: 'Dumbbell',
    movementPattern: 'Loaded Carry',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Walking with weight locked out overhead, challenging shoulder stability, serratus anterior, and anti-extension core control.',
    setupInstructions: ['Press weight overhead, locking elbow completely by ear.'],
    executionSteps: ['Walk forward smoothly while maintaining active upward shoulder shrug and neutral spine.'],
    coachingCues: ['Bicep by the ear.', 'Ribs pulled down, no arched back.'],
    commonMistakes: ['Allowing elbow to bend under fatigue.'],
    defaultTrainerNote: 'Supreme test of overhead stability and whole-body integration.',
    tags: ['Functional', 'Overhead', 'Carry', 'Shoulders'],
  },

  // BOXING & CONDITIONING
  {
    id: 'ex_shadow_boxing',
    name: 'Shadow Boxing',
    category: 'Boxing',
    subcategory: 'Footwork / Striking',
    primaryMuscles: ['MuscleGroup.fullBody'],
    secondaryMuscles: ['MuscleGroup.shoulders', 'MuscleGroup.coreAbs', 'MuscleGroup.calves'],
    equipment: 'Bodyweight',
    movementPattern: 'Conditioning',
    difficulty: 'Beginner',
    exerciseType: 'Conditioning',
    description: 'Rhythmic boxing combinations, head movement, and footwork in free space building rotational conditioning and punching mechanics.',
    setupInstructions: ['Assume boxing stance with lead foot forward, hands protecting chin, elbows tucked.'],
    executionSteps: ['Throw continuous punches (jab, cross, hooks, uppercuts) while shifting weight and slipping punches.', 'Work for 2 to 3-minute timed rounds with constant bounce.'],
    coachingCues: ['Stay light on toes.', 'Rotate hips and pivot rear foot on punches.'],
    commonMistakes: ['Flat-footed stance or dropping guard.'],
    defaultTrainerNote: 'Essential boxing warm-up and aerobic conditioning drill.',
    tags: ['Boxing', 'Conditioning', 'Cardio', 'Agility'],
  },
  {
    id: 'ex_speed_bag',
    name: 'Speed Bag Drills',
    category: 'Boxing',
    subcategory: 'Hand-Eye Coordination',
    primaryMuscles: ['MuscleGroup.shoulders'],
    secondaryMuscles: ['MuscleGroup.forearms', 'MuscleGroup.triceps'],
    equipment: 'Other',
    movementPattern: 'Conditioning',
    difficulty: 'Intermediate',
    exerciseType: 'Conditioning',
    description: 'Rhythmic striking of the speed bag to develop shoulder muscular endurance, hand speed, and peripheral visual tracking.',
    setupInstructions: ['Stand facing speed bag with belly button aligned to bag bottom.'],
    executionSteps: ['Strike bag with small circular motions of fists in a 3-rebound rhythm.', 'Keep hands at eye level and alternate strikes.'],
    coachingCues: ['Small circles with fists.', 'Listen for the 3-beat rhythm.'],
    commonMistakes: ['Hitting too hard rather than rhythmically.'],
    defaultTrainerNote: 'Great deltoid endurance builder for fighters.',
    tags: ['Boxing', 'Speed Bag', 'Endurance', 'Shoulders'],
  },
  {
    id: 'ex_jump_rope',
    name: 'Jump Rope / Skipping',
    category: 'Conditioning',
    subcategory: 'Cardio',
    primaryMuscles: ['MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.forearms', 'MuscleGroup.shoulders', 'MuscleGroup.coreAbs'],
    equipment: 'Other',
    movementPattern: 'Cardio',
    difficulty: 'Beginner',
    exerciseType: 'Cardio',
    description: 'Classic boxing conditioning drill developing foot speed, ankle elasticity, hand-eye coordination, and aerobic capacity.',
    setupInstructions: ['Hold handles loosely at hip height, elbows tucked close to body.'],
    executionSteps: ['Rotate rope with wrists, jumping 1 to 2 inches off floor on balls of feet.', 'Maintain steady, relaxed breathing.'],
    coachingCues: ['Turn rope with wrists, not whole arms.', 'Land softly on balls of feet.'],
    commonMistakes: ['Jumping excessively high.'],
    defaultTrainerNote: 'Fundamental warm-up and conditioning staple for Alpha X Gym.',
    tags: ['Cardio', 'Jump Rope', 'Boxing', 'Conditioning'],
  },
  {
    id: 'ex_shuttle_runs',
    name: 'Shuttle Runs (Suicides)',
    category: 'Conditioning',
    subcategory: 'Agility',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.glutes'],
    equipment: 'Bodyweight',
    movementPattern: 'Agility',
    difficulty: 'Intermediate',
    exerciseType: 'Cardio',
    description: 'Rapid sprint-and-deceleration intervals between markers developing change-of-direction agility and anaerobic power.',
    setupInstructions: ['Set cones at 5, 10, and 15 meters.'],
    executionSteps: ['Sprint to first cone, touch line with hand, sprint back to start.', 'Immediately sprint to second cone and return, repeating through third cone.'],
    coachingCues: ['Drop hips to decelerate.', 'Explode off outside foot on turns.'],
    commonMistakes: ['Rounding corners instead of sharp deceleration.'],
    defaultTrainerNote: 'Elite anaerobic threshold and sprint conditioning drill.',
    tags: ['Conditioning', 'Agility', 'Sprint', 'Cardio'],
  },

  // MOBILITY, WARM-UP & COOL-DOWN
  {
    id: 'ex_worlds_greatest_stretch',
    name: "World's Greatest Stretch",
    category: 'Mobility',
    subcategory: 'Full Body Mobility',
    primaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.hamstrings'],
    secondaryMuscles: ['MuscleGroup.lowerBack', 'MuscleGroup.upperChest'],
    equipment: 'Bodyweight',
    movementPattern: 'Mobility',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Comprehensive dynamic mobility movement opening thoracic spine, hips, groin, and hamstrings in a single flow.',
    setupInstructions: ['Step forward into a deep lunge with both hands on floor inside front foot.'],
    executionSteps: ['Drop inside elbow toward floor for deep hip stretch.', 'Rotate torso and reach inside arm straight up to ceiling, tracking hand with eyes.', 'Place hands down and rock hips back to stretch front hamstring.', 'Step forward and repeat on other side.'],
    coachingCues: ['Follow hand with eyes on thoracic rotation.', 'Breathe into the hip opener.'],
    commonMistakes: ['Rushing through positions without pausing.'],
    defaultTrainerNote: 'The gold standard full-body warm-up movement before heavy lifting.',
    tags: ['Mobility', 'Warm-up', 'Hips', 'Thoracic'],
  },
  {
    id: 'ex_90_90_hip_rotation',
    name: '90/90 Hip Mobility Rotation',
    category: 'Mobility',
    subcategory: 'Hip Mobility',
    primaryMuscles: ['MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.quads'],
    equipment: 'Bodyweight',
    movementPattern: 'Mobility',
    difficulty: 'Beginner',
    exerciseType: 'Mobility',
    description: 'Seated hip flow mobilizing internal and external hip rotation simultaneously to eliminate squat and hinge restrictions.',
    setupInstructions: ['Sit on floor with front leg bent at 90 degrees in front and back leg bent at 90 degrees behind.'],
    executionSteps: ['Sit tall, lean gently over front knee for external rotation stretch.', 'Rotate knees smoothly through center to opposite side without hands if possible.'],
    coachingCues: ['Keep spine tall.', 'Rotate smoothly without lifting off floor.'],
    commonMistakes: ['Slouching lower back.'],
    defaultTrainerNote: 'Immediate improvement in squat depth and hip health.',
    tags: ['Mobility', 'Hip Mobility', '90-90', 'Flexibility'],
  },
  {
    id: 'ex_cat_cow',
    name: 'Cat-Cow Spinal Flow',
    category: 'Mobility',
    subcategory: 'Spine Mobility',
    primaryMuscles: ['MuscleGroup.lowerBack'],
    secondaryMuscles: ['MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Mobility',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Gentle spinal flexion and extension on all fours, warming up the intervertebral discs and paraspinal muscles.',
    setupInstructions: ['Kneel on all fours with hands under shoulders and knees under hips.'],
    executionSteps: ['Inhale, drop belly toward floor, lift chest and gaze (Cow position).', 'Exhale, arch spine upward toward ceiling, tuck chin and tailbone (Cat position).', 'Flow smoothly between both positions with your breath.'],
    coachingCues: ['Move segment by segment through spine.', 'Synchronize breath with movement.'],
    commonMistakes: ['Forcing neck too far into hyperextension.'],
    defaultTrainerNote: 'Essential spinal decompressor before and after heavy training.',
    tags: ['Mobility', 'Spine', 'Warm-up', 'Yoga'],
  },
  {
    id: 'ex_shoulder_cars',
    name: 'Shoulder CARs (Controlled Articular Rotations)',
    category: 'Mobility',
    subcategory: 'Shoulder Mobility',
    primaryMuscles: ['MuscleGroup.shoulders'],
    secondaryMuscles: ['MuscleGroup.traps', 'MuscleGroup.upperChest'],
    equipment: 'Bodyweight',
    movementPattern: 'Mobility',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Slow, full-circle joint rotations taking the glenohumeral joint through its absolute maximum active range of motion.',
    setupInstructions: ['Stand tall with feet hip-width, brace core to prevent torso rotation.'],
    executionSteps: ['Sweep arm up across chest into full overhead extension.', 'Rotate thumb inward into internal rotation while carving a big circle backward.', 'Reverse circle precisely back to start.'],
    coachingCues: ['Move only the shoulder joint; freeze the rest of body.', 'Draw the biggest circle possible in the air.'],
    commonMistakes: ['Arching back or twisting torso to cheat the circle.'],
    defaultTrainerNote: 'Restores and maintains shoulder capsule longevity.',
    tags: ['Mobility', 'CARs', 'Shoulders', 'Warm-up'],
  },
  {
    id: 'ex_thoracic_rotations',
    name: 'Side-Lying Thoracic Rotation (Open Books)',
    category: 'Mobility',
    subcategory: 'Thoracic Spine',
    primaryMuscles: ['MuscleGroup.rhomboids', 'MuscleGroup.upperChest'],
    secondaryMuscles: ['MuscleGroup.lowerBack'],
    equipment: 'Bodyweight',
    movementPattern: 'Mobility',
    difficulty: 'Beginner',
    exerciseType: 'Mobility',
    description: 'Lying on side with knees pinned, opening the top arm in an arc across to open the mid-back and chest.',
    setupInstructions: ['Lie on side with knees bent at 90 degrees stacked over each other, arms extended straight in front.'],
    executionSteps: ['Lift top arm and rotate back toward opposite floor, tracking hand with eyes.', 'Exhale as chest opens flat to ceiling, keeping knees glued together.', 'Hold 2 seconds and return.'],
    coachingCues: ['Do not let top knee slide off bottom knee.', 'Exhale into the open stretch.'],
    commonMistakes: ['Lifting knees off floor.'],
    defaultTrainerNote: 'Essential for desk workers and overhead lifters.',
    tags: ['Mobility', 'Thoracic', 'Warm-up'],
  },
  {
    id: 'ex_inchworm_walkout',
    name: 'Inchworm Walkout with Push-Up',
    category: 'Warm-up',
    subcategory: 'Dynamic Warm-up',
    primaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.shoulders', 'MuscleGroup.midChest'],
    equipment: 'Bodyweight',
    movementPattern: 'Warm-up',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Dynamic hamstring stretch walking hands out from forward bend into a high plank push-up and walking back.',
    setupInstructions: ['Stand tall with feet hip-width.'],
    executionSteps: ['Hinge forward touching floor, keeping legs as straight as comfortable.', 'Walk hands forward into high plank, perform 1 push-up.', 'Walk hands back to feet and stand upright.'],
    coachingCues: ['Keep legs straight to feel hamstring stretch.', 'Walk hands out under control.'],
    commonMistakes: ['Sagging hips during walkout.'],
    defaultTrainerNote: 'Dynamic full-body warm-up linking hamstrings, core, and shoulders.',
    tags: ['Warm-up', 'Dynamic', 'Hamstrings', 'Mobility'],
  },
  {
    id: 'ex_pigeon_pose',
    name: 'Pigeon Pose Stretch',
    category: 'Flexibility',
    subcategory: 'Hip Flexibility',
    primaryMuscles: ['MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.lowerBack'],
    equipment: 'Bodyweight',
    movementPattern: 'Flexibility',
    difficulty: 'Beginner',
    exerciseType: 'Cool-down',
    description: 'Deep static stretch for the piriformis, gluteus medius, and hip capsule, relieving sciatic tension and lower back tightness.',
    setupInstructions: ['From plank, bring right knee forward behind right wrist, shin angled across mat.', 'Extend left leg straight back with top of foot on floor.'],
    executionSteps: ['Square hips to floor.', 'Walk hands forward and fold torso over front leg.', 'Hold for 30 to 60 seconds, taking deep diaphragmatic breaths.'],
    coachingCues: ['Keep hips square.', 'Sink heavier on each exhalation.'],
    commonMistakes: ['Collapsing onto one hip.'],
    defaultTrainerNote: 'Crucial post-leg workout static cool-down stretch.',
    tags: ['Flexibility', 'Cool-down', 'Glutes', 'Hips'],
  },
  {
    id: 'ex_cobra_stretch',
    name: 'Cobra / Sphinx Stretch',
    category: 'Flexibility',
    subcategory: 'Spine Extension',
    primaryMuscles: ['MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.lowerBack'],
    equipment: 'Bodyweight',
    movementPattern: 'Flexibility',
    difficulty: 'Beginner',
    exerciseType: 'Cool-down',
    description: 'Prone abdominal stretch gently extending the lumbar and thoracic spine to counteract prolonged sitting flexion.',
    setupInstructions: ['Lie face down on floor with hands under shoulders, legs extended back.'],
    executionSteps: ['Press palms into floor, gently straightening arms to lift chest while keeping hips pinned to floor.', 'Look forward and take 3 deep belly breaths.'],
    coachingCues: ['Drop shoulders away from ears.', 'Keep pelvis pressed to floor.'],
    commonMistakes: ['Crunching the lower back aggressively.'],
    defaultTrainerNote: 'Excellent cool-down decompressor after deadlifts and abdominal workouts.',
    tags: ['Flexibility', 'Cool-down', 'Spine', 'Yoga'],
  },
  {
    id: 'ex_childs_pose',
    name: "Child's Pose",
    category: 'Cool-down',
    subcategory: 'Spine / Lats Stretch',
    primaryMuscles: ['MuscleGroup.lowerBack', 'MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.glutes'],
    equipment: 'Bodyweight',
    movementPattern: 'Cool-down',
    difficulty: 'Beginner',
    exerciseType: 'Cool-down',
    description: 'Restorative kneeling fold extending arms forward while sinking hips to heels, decompressing the spine and calming the nervous system.',
    setupInstructions: ['Kneel with knees wide, big toes touching, sit back on heels.'],
    executionSteps: ['Walk hands forward and rest forehead on floor, extending arms long.', 'Breathe deeply into ribcage and lower back for 1 to 2 minutes.'],
    coachingCues: ['Sink hips back to heels.', 'Lengthen spine with every breath.'],
    commonMistakes: ['Lifting hips off heels.'],
    defaultTrainerNote: 'Perfect final cool-down posture to transition from training to recovery.',
    tags: ['Cool-down', 'Restorative', 'Spine', 'Lats'],
  },
];

console.log(`Loaded ${ALL_NEW_EXERCISES.length} detailed exercise expansions.`);
