import * as fs from 'fs';
import * as path from 'path';

interface NewExerciseDef {
  id: string;
  name: string;
  category: string;
  primaryMuscles: string[]; // e.g. ['MuscleGroup.upperChest']
  secondaryMuscles: string[];
  equipment: string;
  movementPattern: string;
  difficulty: string; // 'Beginner' | 'Intermediate' | 'Advanced'
  exerciseType: string;
  description: string;
  setupInstructions: string[];
  executionSteps: string[];
  coachingCues: string[];
  commonMistakes: string[];
  defaultTrainerNote: string;
  tags: string[];
}

const NEW_EXERCISES: NewExerciseDef[] = [
  // ==========================================
  // CHEST
  // ==========================================
  {
    id: 'ex_wide_pushup',
    name: 'Wide-Grip Push-Up',
    category: 'Chest',
    primaryMuscles: ['MuscleGroup.midChest'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.triceps', 'MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Horizontal Push',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Push-up variation with hand placement wider than shoulder-width to place greater horizontal adduction stretch and load across the pectoralis major.',
    setupInstructions: ['Assume high plank position with hands positioned 6 to 8 inches outside shoulder width.', 'Turn fingers slightly outward to protect the wrist joints.', 'Brace core and squeeze glutes to establish a rigid plank from head to heels.'],
    executionSteps: ['Lower chest toward floor by flexing elbows outward at a 45 to 60-degree angle to the torso.', 'Descend until chest is roughly an inch off the floor.', 'Press through the palms to return to full lockout while maintaining body alignment.'],
    coachingCues: ['Flare elbows no more than 60 degrees.', 'Do not allow hips to sag.', 'Feel the horizontal chest squeeze at lockout.'],
    commonMistakes: ['Flaring elbows out at 90 degrees risking shoulder impingement.', 'Hyperextending lumbar spine.', 'Shortening range of motion.'],
    defaultTrainerNote: 'Great chest finisher. Focus on a controlled 3-second eccentric stretch.',
    tags: ['Chest', 'Push-Up', 'Bodyweight', 'Pectorals'],
  },
  {
    id: 'ex_deficit_pushup',
    name: 'Deficit Push-Up',
    category: 'Chest',
    primaryMuscles: ['MuscleGroup.midChest', 'MuscleGroup.lowerChest'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.triceps'],
    equipment: 'Bodyweight',
    movementPattern: 'Horizontal Push',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Elevating hands on bumper plates, blocks, or parallettes to allow the chest to descend below hand level, producing maximum passive stretch under load.',
    setupInstructions: ['Place two sturdy blocks or bumper plates slightly wider than shoulder width.', 'Place hands firmly on elevated surfaces in plank posture.', 'Keep spine neutral and glutes clenched.'],
    executionSteps: ['Lower body with control, allowing chest to sink below the elevation of the hands.', 'Pause for 1 second in the deep stretch position without resting.', 'Drive powerfully back up to standard lockout.'],
    coachingCues: ['Sink into the stretch under control.', 'Retract scapulae deeply at the bottom.', 'Drive through palms.'],
    commonMistakes: ['Dropping head rather than lowering chest.', 'Bouncing out of the stretched position.', 'Sagging hips.'],
    defaultTrainerNote: 'Unlocks deeper chest hypertrophy. Keep shoulders packed down away from ears.',
    tags: ['Chest', 'Deficit', 'Bodyweight', 'Hypertrophy'],
  },
  {
    id: 'ex_ring_pushup',
    name: 'Ring Push-Up',
    category: 'Chest',
    primaryMuscles: ['MuscleGroup.midChest'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.triceps', 'MuscleGroup.coreAbs'],
    equipment: 'TRX',
    movementPattern: 'Horizontal Push',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Gymnastic ring push-up requiring immense shoulder and rotator cuff stabilization while allowing full convergence of hands at the top for peak contraction.',
    setupInstructions: ['Hang gymnastic rings 3 to 6 inches above floor level.', 'Grip rings firmly and step back into a plank position.', 'Turn rings slightly outward (supinated) at top for stabilization.'],
    executionSteps: ['Lower chest between the rings while maintaining steady forearm control.', 'Reach bottom position with hands near armpits.', 'Press upward and turn rings slightly outward at peak lockout while squeezing pectorals.'],
    coachingCues: ['Control ring wobble by squeezing ring handles tightly.', 'Converge hands together at the top.', 'Keep core rock solid.'],
    commonMistakes: ['Letting rings flare outwards unsafely.', 'Sagging lower back.', 'Rushing repetitions.'],
    defaultTrainerNote: 'Elite stabilizer recruitment. Keep ring straps perpendicular to floor.',
    tags: ['Calisthenics', 'Rings', 'Chest', 'Core'],
  },
  {
    id: 'ex_weighted_pushup',
    name: 'Weighted Push-Up',
    category: 'Chest',
    primaryMuscles: ['MuscleGroup.midChest'],
    secondaryMuscles: ['MuscleGroup.triceps', 'MuscleGroup.frontDelts'],
    equipment: 'Other',
    movementPattern: 'Horizontal Push',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Standard push-up overloaded using weight plates on the upper back or a weighted vest to progress horizontal pressing strength beyond bodyweight.',
    setupInstructions: ['Place weight vest on or have training partner center a weight plate directly over mid/upper back.', 'Assume rigid push-up posture with hands slightly outside shoulders.'],
    executionSteps: ['Lower chest toward floor under strict control over 2 to 3 seconds.', 'Touch chest lightly to ground without unloading tension.', 'Drive through floor to return to full arm extension.'],
    coachingCues: ['Maintain hollow body tension.', 'Keep plate steady on upper thoracic spine.'],
    commonMistakes: ['Plate sliding onto lumbar spine.', 'Shortening depth due to load.'],
    defaultTrainerNote: 'Bench press alternative with superior scapular freedom.',
    tags: ['Chest', 'Weighted', 'Strength', 'Push-Up'],
  },
  {
    id: 'ex_smith_flat_bench',
    name: 'Smith Machine Flat Bench Press',
    category: 'Chest',
    primaryMuscles: ['MuscleGroup.midChest'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.triceps'],
    equipment: 'Smith Machine',
    movementPattern: 'Horizontal Push',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Fixed-track horizontal press enabling strict pectoral isolation with zero requirement to balance the bar, allowing safe training close to failure.',
    setupInstructions: ['Position flat bench centered directly underneath the Smith bar.', 'Lie with mid-sternum aligned with the bar path.', 'Set safety pins 1 inch below chest level.'],
    executionSteps: ['Rotate wrists to unrack the bar.', 'Lower bar smoothly to touch mid-chest lightly.', 'Press bar vertically upward until arms are extended without locking elbows hard.'],
    coachingCues: ['Drive heels into floor.', 'Pull shoulder blades into bench.', 'Focus mind-muscle connection on mid chest.'],
    commonMistakes: ['Bouncing the bar off the ribcage.', 'Setting bench off-center from the track.'],
    defaultTrainerNote: 'Ideal for hypertrophy and drop-sets without needing a human spotter.',
    tags: ['Chest', 'Smith Machine', 'Hypertrophy'],
  },
  {
    id: 'ex_landmine_press_standing',
    name: 'Standing Landmine Press',
    category: 'Chest',
    primaryMuscles: ['MuscleGroup.upperChest', 'MuscleGroup.frontDelts'],
    secondaryMuscles: ['MuscleGroup.triceps', 'MuscleGroup.coreAbs'],
    equipment: 'Barbell',
    movementPattern: 'Incline Push',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Angled pressing movement that follows an arc, providing upper chest and anterior deltoid stimulation that is exceptionally joint-friendly for the shoulder.',
    setupInstructions: ['Insert one end of barbell into a landmine pivot or corner.', 'Stand with feet staggered or hip-width apart holding the sleeve end at upper chest level.'],
    executionSteps: ['Press the barbell up and forward along its natural diagonal arc.', 'Reach full extension while reaching forward slightly through the serratus.', 'Lower under control back to chest level.'],
    coachingCues: ['Press up and out at roughly 45 degrees.', 'Keep core braced to avoid leaning backward.'],
    commonMistakes: ['Hyperextending lumbar spine.', 'Dropping bar too quickly.'],
    defaultTrainerNote: 'Outstanding for athletes with shoulder impingement from traditional overhead pressing.',
    tags: ['Chest', 'Shoulders', 'Landmine', 'Functional'],
  },

  // ==========================================
  // BACK
  // ==========================================
  {
    id: 'ex_neutral_lat_pulldown',
    name: 'Neutral-Grip Lat Pulldown',
    category: 'Back',
    primaryMuscles: ['MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.rhomboids'],
    equipment: 'Cable',
    movementPattern: 'Vertical Pull',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Lat pulldown using a parallel/neutral grip attachment, placing shoulders in optimal plane for latissimus dorsi mechanical advantage and reduced wrist strain.',
    setupInstructions: ['Attach V-bar or neutral grip attachment to high pulley.', 'Adjust thigh pad so legs are locked firmly in place.', 'Grip handles with palms facing each other.'],
    executionSteps: ['Lean back slightly (10 to 15 degrees) with chest lifted.', 'Drive elbows down and back toward your hip pockets.', 'Pull until attachment reaches upper chest, squeezing lats.', 'Extend arms smoothly back to full overhead stretch.'],
    coachingCues: ['Lead with the elbows, not hands.', 'Chest high, lats spread wide at top.'],
    commonMistakes: ['Excessive swinging of torso.', 'Pulling too low down onto belly.'],
    defaultTrainerNote: 'Fantastic for lat width. Pause 1 second at full contraction.',
    tags: ['Back', 'Lats', 'Cable', 'Neutral Grip'],
  },
  {
    id: 'ex_single_arm_cable_row',
    name: 'Single-Arm Cable Row',
    category: 'Back',
    primaryMuscles: ['MuscleGroup.lats', 'MuscleGroup.rhomboids'],
    secondaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.coreAbs'],
    equipment: 'Cable',
    movementPattern: 'Horizontal Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral cable row allowing full rotational freedom of the wrist and maximum range of motion to stretch and contract the lats individually.',
    setupInstructions: ['Set cable pulley at mid-torso height with a single D-handle.', 'Step back into athletic stance or sit with feet braced.'],
    executionSteps: ['Allow arm to extend forward to feel a full lat stretch around ribcage.', 'Drive elbow backward close to your side while rotating palm from neutral to supinated.', 'Squeeze lat fully at the back, avoiding torso over-rotation.'],
    coachingCues: ['Drive elbow past ribcage.', 'Keep torso steady with minimal twisting.'],
    commonMistakes: ['Rotating torso excessively to heave the weight.', 'Shrugging shoulder up to ear.'],
    defaultTrainerNote: 'Fixes left/right strength imbalances and enhances mind-muscle connection.',
    tags: ['Back', 'Unilateral', 'Lats', 'Cable'],
  },
  {
    id: 'ex_seal_row',
    name: 'Seal Row',
    category: 'Back',
    primaryMuscles: ['MuscleGroup.rhomboids', 'MuscleGroup.traps', 'MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.rearDelts'],
    equipment: 'Barbell',
    movementPattern: 'Horizontal Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Prone row performed lying flat on an elevated bench, completely eliminating lower back momentum and isolating the mid-back musculature.',
    setupInstructions: ['Lie face down on an elevated horizontal bench with barbell underneath.', 'Grip bar with double overhand grip slightly wider than shoulders.'],
    executionSteps: ['Pull barbell vertically up until it contacts the underside of the bench.', 'Retract shoulder blades and hold peak contraction for 1 second.', 'Lower bar under strict control until arms are fully elongated.'],
    coachingCues: ['Keep chest pinned to bench throughout.', 'Squeeze mid-back as if pinching a pencil.'],
    commonMistakes: ['Lifting chest off bench.', 'Jerking the neck upward.'],
    defaultTrainerNote: 'Pure upper back hypertrophy with zero lumbar spinal strain.',
    tags: ['Back', 'Upper Back', 'Barbell', 'Seal Row'],
  },
  {
    id: 'ex_rack_pull',
    name: 'Rack Pull',
    category: 'Back',
    primaryMuscles: ['MuscleGroup.traps', 'MuscleGroup.lowerBack'],
    secondaryMuscles: ['MuscleGroup.lats', 'MuscleGroup.glutes', 'MuscleGroup.forearms'],
    equipment: 'Barbell',
    movementPattern: 'Hip Hinge',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Partial deadlift initiated with barbell elevated on power rack pins just below knee height, overloading the upper back, traps, and hip lockout.',
    setupInstructions: ['Set rack safety pins so barbell rests just below kneecaps.', 'Step up to bar with hip-width stance, grip bar overhand or hook grip.'],
    executionSteps: ['Hinge at hips, brace core, pull slack out of bar.', 'Drive hips forward and extend spine to pull bar to full erect lockout.', 'Squeeze glutes and upper back, then lower with control to rack pins.'],
    coachingCues: ['Pack lats tight against ribs.', 'Drive hips into the bar at lockout.'],
    commonMistakes: ['Hyperextending lumbar spine at top.', 'Bouncing violently off the pins.'],
    defaultTrainerNote: 'Builds dense upper back and trap thickness with huge overload capability.',
    tags: ['Back', 'Traps', 'Deadlift', 'Strength'],
  },
  {
    id: 'ex_dumbbell_pullover',
    name: 'Dumbbell Pullover',
    category: 'Back',
    primaryMuscles: ['MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.upperChest', 'MuscleGroup.triceps'],
    equipment: 'Dumbbell',
    movementPattern: 'Vertical Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Classic exercise performed lying across or along a flat bench, stretching the lats and serratus anterior through a long overhead arc.',
    setupInstructions: ['Lie perpendicular across a flat bench with upper back supported.', 'Hold dumbbell cupped between both palms directly over chest.'],
    executionSteps: ['Keeping a slight bend in elbows, lower dumbbell in an arc back behind your head.', 'Descend until feeling a deep stretch across the lats and ribcage.', 'Contract lats to pull dumbbell back over chest.'],
    coachingCues: ['Keep hips slightly dipped to anchor the stretch.', 'Maintain consistent elbow angle.'],
    commonMistakes: ['Bending elbows into a triceps extension.', 'Excessive arching of lower back.'],
    defaultTrainerNote: 'Incredible lat stretch and ribcage expansion movement.',
    tags: ['Back', 'Lats', 'Dumbbell', 'Pullover'],
  },
  {
    id: 'ex_barbell_pullover',
    name: 'Barbell Pullover',
    category: 'Back',
    primaryMuscles: ['MuscleGroup.lats'],
    secondaryMuscles: ['MuscleGroup.upperChest', 'MuscleGroup.triceps'],
    equipment: 'Barbell',
    movementPattern: 'Vertical Pull',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Long-arc lat pullovers utilizing an EZ or straight barbell to provide strict bilateral tension through full overhead extension.',
    setupInstructions: ['Lie supine along a flat bench holding barbell with shoulder-width overhand grip above chest.'],
    executionSteps: ['Lower barbell backward behind head in a controlled arc, feeling deep lat stretch.', 'Reverse movement by engaging lats to bring barbell back upright.'],
    coachingCues: ['Keep elbows slightly bent and fixed in position.', 'Inhale on the stretch, exhale on the pull.'],
    commonMistakes: ['Dropping bar too low past shoulder mobility limit.'],
    defaultTrainerNote: 'Use moderate weight and focus on maximum stretch tension.',
    tags: ['Back', 'Lats', 'Barbell', 'Pullover'],
  },

  // ==========================================
  // SHOULDERS
  // ==========================================
  {
    id: 'ex_smith_shoulder_press',
    name: 'Smith Machine Shoulder Press',
    category: 'Shoulders',
    primaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.sideDelts'],
    secondaryMuscles: ['MuscleGroup.triceps', 'MuscleGroup.traps'],
    equipment: 'Smith Machine',
    movementPattern: 'Vertical Push',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Seated overhead press within the guided path of the Smith machine, maximizing deltoid overload without balance requirements.',
    setupInstructions: ['Set upright bench (75–80 degrees) centered under Smith bar.', 'Sit with back flat against pad, grip bar slightly wider than shoulders.'],
    executionSteps: ['Unrack bar, lower smoothly to chin/upper collarbone level.', 'Press bar vertically overhead until elbows are nearly extended.'],
    coachingCues: ['Keep wrists stacked over elbows.', 'Avoid fully locking out elbows to keep deltoid tension constant.'],
    commonMistakes: ['Arching lower back off the pad.', 'Pressing with elbows flared too far back.'],
    defaultTrainerNote: 'Excellent for safe shoulder hypertrophy and high-rep finisher sets.',
    tags: ['Shoulders', 'Delts', 'Smith Machine', 'Press'],
  },
  {
    id: 'ex_machine_lateral_raise',
    name: 'Machine Lateral Raise',
    category: 'Shoulders',
    primaryMuscles: ['MuscleGroup.sideDelts'],
    secondaryMuscles: ['MuscleGroup.traps'],
    equipment: 'Machine',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Seated shoulder abduction machine providing constant resistance curve throughout the range of motion for lateral deltoid growth.',
    setupInstructions: ['Adjust seat height so shoulder joints align with machine pivot axes.', 'Place outer elbows against padded lever arms.'],
    executionSteps: ['Drive elbows up and outward until upper arms are parallel to the floor.', 'Pause for 1 second at top.', 'Lower under control for 2 to 3 seconds.'],
    coachingCues: ['Lead with elbows, keep hands relaxed.', 'Keep shoulders down away from ears.'],
    commonMistakes: ['Shrugging traps to raise arms.', 'Setting seat too low or high.'],
    defaultTrainerNote: 'Superior continuous tension compared to standard dumbbells at the bottom.',
    tags: ['Shoulders', 'Side Delts', 'Machine', 'Isolation'],
  },
  {
    id: 'ex_cable_front_raise',
    name: 'Cable Front Raise',
    category: 'Shoulders',
    primaryMuscles: ['MuscleGroup.frontDelts'],
    secondaryMuscles: ['MuscleGroup.upperChest'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Low-pulley anterior deltoid raise ensuring continuous tension from starting stretch to top horizontal contraction.',
    setupInstructions: ['Set low pulley with straight bar or single handle.', 'Stand facing away with cable passing between legs.'],
    executionSteps: ['Raise arms forward in an arc until parallel with floor.', 'Hold peak contraction briefly.', 'Lower smoothly to thighs.'],
    coachingCues: ['Keep torso rigid without swinging.', 'Knuckles facing ceiling.'],
    commonMistakes: ['Using momentum from hips.'],
    defaultTrainerNote: 'Great for anterior deltoid isolation.',
    tags: ['Shoulders', 'Front Delts', 'Cable'],
  },
  {
    id: 'ex_dumbbell_y_raise',
    name: 'Dumbbell Y-Raise',
    category: 'Shoulders',
    primaryMuscles: ['MuscleGroup.sideDelts', 'MuscleGroup.traps'],
    secondaryMuscles: ['MuscleGroup.rearDelts'],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Raise dumbbells in a 30-degree forward angled Y-shape along the scapular plane, optimally targeting side delts and lower traps.',
    setupInstructions: ['Lie chest-down on 30–45 degree incline bench holding light dumbbells with thumbs pointing up.'],
    executionSteps: ['Raise dumbbells outward and upward at roughly 45-degree angle in a Y-formation.', 'Squeeze lower traps and lateral delts at top.', 'Lower with strict control.'],
    coachingCues: ['Thumbs pointing toward ceiling.', 'Think reaching long into the corners.'],
    commonMistakes: ['Using excessively heavy weights.', 'Bending arms into a row.'],
    defaultTrainerNote: 'Essential for shoulder health and 3D deltoid development.',
    tags: ['Shoulders', 'Y-Raise', 'Scapular', 'Dumbbell'],
  },
  {
    id: 'ex_cuban_press',
    name: 'Cuban Press',
    category: 'Shoulders',
    primaryMuscles: ['MuscleGroup.rearDelts', 'MuscleGroup.shoulders'],
    secondaryMuscles: ['MuscleGroup.traps', 'MuscleGroup.triceps'],
    equipment: 'Dumbbell',
    movementPattern: 'Rotational Push',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Combined upright row, external shoulder rotation, and overhead press building bulletproof rotator cuff and shoulder girdle resilience.',
    setupInstructions: ['Stand upright holding light dumbbells at thighs.'],
    executionSteps: ['Perform upright row until upper arms are parallel to floor.', 'Rotate forearms upward 90 degrees while keeping elbows pinned in place.', 'Press dumbbells overhead to full extension.', 'Reverse the sequence precisely back to start.'],
    coachingCues: ['Keep weights light.', 'Smooth rotation without elbow dropping.'],
    commonMistakes: ['Lifting heavy and jerking during external rotation.'],
    defaultTrainerNote: 'Unmatched prehab exercise for overhead athletes and lifters.',
    tags: ['Shoulders', 'Rotator Cuff', 'Cuban Press', 'Prehab'],
  },
  {
    id: 'ex_external_rotation_cable',
    name: 'Cable Shoulder External Rotation',
    category: 'Shoulders',
    primaryMuscles: ['MuscleGroup.rearDelts'],
    secondaryMuscles: ['MuscleGroup.traps'],
    equipment: 'Cable',
    movementPattern: 'Rotation',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Isolating infraspinatus and teres minor to balance internal rotators and stabilize the humeral head.',
    setupInstructions: ['Set cable pulley at elbow height.', 'Stand sideways to pulley holding handle with outer hand, elbow pinned at 90 degrees with a towel roll under armpit.'],
    executionSteps: ['Rotate forearm outward away from body while keeping elbow glued to your side.', 'Squeeze rotator cuff at full outward rotation.', 'Slowly return to start.'],
    coachingCues: ['Do not let elbow drift away from ribs.', 'Controlled 2-second eccentric.'],
    commonMistakes: ['Twisting torso instead of rotating shoulder.'],
    defaultTrainerNote: 'Crucial rotator cuff prehab for heavy benchers.',
    tags: ['Shoulders', 'Rotator Cuff', 'Prehab', 'Mobility'],
  },
  {
    id: 'ex_internal_rotation_cable',
    name: 'Cable Shoulder Internal Rotation',
    category: 'Shoulders',
    primaryMuscles: ['MuscleGroup.frontDelts'],
    secondaryMuscles: ['MuscleGroup.midChest'],
    equipment: 'Cable',
    movementPattern: 'Rotation',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Isolating the subscapularis muscle to maintain balanced rotator cuff tension and shoulder joint integrity.',
    setupInstructions: ['Set cable pulley at elbow height.', 'Stand sideways with inner arm holding handle, elbow bent 90 degrees.'],
    executionSteps: ['Rotate forearm inward across abdomen while keeping elbow pinned to side.', 'Hold 1 second then return under control.'],
    coachingCues: ['Keep wrist straight and elbow tucked.'],
    commonMistakes: ['Jerking weight across with body lean.'],
    defaultTrainerNote: 'Complements external rotations for complete shoulder stability.',
    tags: ['Shoulders', 'Rotator Cuff', 'Prehab'],
  },

  // ==========================================
  // BICEPS & TRICEPS
  // ==========================================
  {
    id: 'ex_drag_curl',
    name: 'Barbell Drag Curl',
    category: 'Biceps',
    primaryMuscles: ['MuscleGroup.biceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Barbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Biceps curl where the bar is dragged straight up the torso by pulling elbows back, eliminating front delt assistance and maximizing biceps peak contraction.',
    setupInstructions: ['Stand upright holding barbell with shoulder-width underhand grip.'],
    executionSteps: ['Drag barbell straight up along line of your shirt/torso by driving elbows straight back.', 'Curl upward as high as possible while keeping bar skimming body.', 'Squeeze biceps peak intensely, then lower along same path.'],
    coachingCues: ['Pull elbows backward as bar rises.', 'Never let bar drift forward away from torso.'],
    commonMistakes: ['Swinging bar forward.', 'Leaning back.'],
    defaultTrainerNote: 'Pure biceps isolation that takes the front delts completely out of the equation.',
    tags: ['Biceps', 'Drag Curl', 'Barbell', 'Arms'],
  },
  {
    id: 'ex_zottman_curl',
    name: 'Zottman Curl',
    category: 'Biceps',
    primaryMuscles: ['MuscleGroup.biceps', 'MuscleGroup.forearms'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Hybrid arm curl performing the concentric phase with palms up (supinated) and the eccentric phase with palms down (pronated) to overload brachioradialis.',
    setupInstructions: ['Stand holding dumbbells at sides with palms facing forward.'],
    executionSteps: ['Curl dumbbells up supinated to shoulder level.', 'At peak contraction, rotate wrists 180 degrees so palms face downward.', 'Lower dumbbells slowly over 3 seconds in the pronated position.', 'Rotate palms forward at the bottom.'],
    coachingCues: ['Supinate on the way up, pronate on the way down.', 'Resist the descent.'],
    commonMistakes: ['Rushing the eccentric lowering phase.'],
    defaultTrainerNote: 'Best 2-in-1 exercise for complete biceps and forearm hypertrophy.',
    tags: ['Biceps', 'Forearms', 'Dumbbell', 'Zottman'],
  },
  {
    id: 'ex_high_cable_curl',
    name: 'High Cable Biceps Curl',
    category: 'Biceps',
    primaryMuscles: ['MuscleGroup.biceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Double biceps pose curl performed between high cable pulleys, isolating the short inner head under sustained tension.',
    setupInstructions: ['Stand centered in dual cable crossover station with pulleys set above head height holding D-handles.'],
    executionSteps: ['Curl handles toward ears while keeping upper arms strictly parallel to floor.', 'Squeeze peak biceps contraction for 1 second.', 'Extend arms under control back toward pulleys.'],
    coachingCues: ['Keep upper arms locked parallel to floor.', 'Squeeze as if posing on stage.'],
    commonMistakes: ['Dropping elbows toward torso.'],
    defaultTrainerNote: 'Elite peak contraction exercise. Great for mind-muscle connection.',
    tags: ['Biceps', 'Cable', 'Isolation', 'Arms'],
  },
  {
    id: 'ex_reverse_pushdown',
    name: 'Reverse-Grip Triceps Pushdown',
    category: 'Triceps',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.forearms'],
    equipment: 'Cable',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Triceps extension with an underhand (supinated) grip, focusing mechanical tension on the medial head of the triceps.',
    setupInstructions: ['Attach straight bar or EZ-bar to high cable pulley.', 'Grip with underhand (palms up) grip at shoulder width.'],
    executionSteps: ['Pin elbows to sides.', 'Push bar downward until arms are fully locked out.', 'Return bar slowly to upper chest level.'],
    coachingCues: ['Keep elbows tucked.', 'Squeeze triceps hard at bottom.'],
    commonMistakes: ['Letting wrists bend backward excessively.'],
    defaultTrainerNote: 'Builds medial head triceps thickness and forearm grip stability.',
    tags: ['Triceps', 'Reverse Grip', 'Cable'],
  },
  {
    id: 'ex_jm_press',
    name: 'JM Press',
    category: 'Triceps',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.midChest', 'MuscleGroup.frontDelts'],
    equipment: 'Barbell',
    movementPattern: 'Compound Push',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Powerlifting hybrid of close-grip bench press and skull crusher, enabling massive overload on the triceps tendon and lockout power.',
    setupInstructions: ['Lie on flat bench holding barbell with shoulder-width overhand grip directly over clavicles.'],
    executionSteps: ['Lower bar directly toward the throat/upper chest while allowing elbows to travel down and forward.', 'Pause 1 inch above neck/clavicle.', 'Drive bar back up through triceps extension to lockout.'],
    coachingCues: ['Lower toward the neck, not sternum.', 'Keep wrists firm and locked.'],
    commonMistakes: ['Turning it into a standard close grip press.'],
    defaultTrainerNote: 'The gold standard for bench press lockout triceps power.',
    tags: ['Triceps', 'Barbell', 'Strength', 'Powerlifting'],
  },
  {
    id: 'ex_bench_dip',
    name: 'Bench Dip',
    category: 'Triceps',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.frontDelts', 'MuscleGroup.midChest'],
    equipment: 'Bench',
    movementPattern: 'Vertical Push',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Triceps bodyweight dip performed with hands braced on a bench behind the body and legs extended forward.',
    setupInstructions: ['Place hands shoulder-width apart on edge of bench, fingers forward.', 'Extend legs in front with heels on floor.'],
    executionSteps: ['Lower hips toward floor by bending elbows to 90 degrees.', 'Press through palms to return to full arm extension.'],
    coachingCues: ['Keep back skimming close to bench.', 'Do not sink past 90 degrees.'],
    commonMistakes: ['Shrugging shoulders into ears.'],
    defaultTrainerNote: 'Beginner-friendly triceps builder that can be weighted as strength increases.',
    tags: ['Triceps', 'Bench', 'Bodyweight'],
  },
  {
    id: 'ex_tate_press',
    name: 'Tate Press',
    category: 'Triceps',
    primaryMuscles: ['MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.frontDelts'],
    equipment: 'Dumbbell',
    movementPattern: 'Isolation',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Elbow-out dumbbell triceps extension on a flat bench specifically targeting the lateral head of the triceps.',
    setupInstructions: ['Lie flat on bench holding dumbbells above chest with elbows flared outward and bells touching.'],
    executionSteps: ['Bend elbows inward and downward to touch dumbbells lightly to chest.', 'Extend elbows outward and upward back to starting position.'],
    coachingCues: ['Keep elbows flared out wide.', 'Press with triceps.'],
    commonMistakes: ['Turning it into a dumbbell bench press.'],
    defaultTrainerNote: 'Outstanding for triceps lateral head sweep.',
    tags: ['Triceps', 'Dumbbell', 'Tate Press'],
  },

  // ==========================================
  // QUADRICEPS & LOWER BODY
  // ==========================================
  {
    id: 'ex_belt_squat',
    name: 'Belt Squat',
    category: 'Quadriceps',
    primaryMuscles: ['MuscleGroup.quads'],
    secondaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.hamstrings'],
    equipment: 'Machine',
    movementPattern: 'Squat',
    difficulty: 'Intermediate',
    exerciseType: 'Hypertrophy',
    description: 'Squat machine loading hips directly via weight belt, loading quads and glutes with zero axial compression on the spine.',
    setupInstructions: ['Strap dip belt around hips and hook to belt squat lever/cable.', 'Stand with shoulder-width stance on elevated platform.'],
    executionSteps: ['Squat down until thighs reach parallel with floor.', 'Drive through full foot to stand upright.'],
    coachingCues: ['Keep torso upright.', 'Drive through mid-foot and heels.'],
    commonMistakes: ['Rounding lower back at bottom.'],
    defaultTrainerNote: 'Elite leg development tool especially when recovering from lower back fatigue.',
    tags: ['Quads', 'Belt Squat', 'Machine', 'Legs'],
  },
  {
    id: 'ex_safety_bar_squat',
    name: 'Safety Bar Squat',
    category: 'Quadriceps',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.lowerBack', 'MuscleGroup.coreAbs'],
    equipment: 'Barbell',
    movementPattern: 'Squat',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Squat using a cambered safety squat bar with front handles, encouraging an upright torso and removing shoulder mobility limitations.',
    setupInstructions: ['Step under padded safety bar, resting yolk across shoulders.', 'Grip front handles lightly.'],
    executionSteps: ['Descend into squat keeping torso upright against camber pull.', 'Reach parallel depth and drive upward through heels.'],
    coachingCues: ['Keep chest proud against the camber.', 'Do not pull down on the handles.'],
    commonMistakes: ['Pulling handles down to cheat the weight.'],
    defaultTrainerNote: 'Builds extraordinary quad strength and upper back endurance.',
    tags: ['Quads', 'Safety Bar', 'Squat', 'Legs'],
  },
  {
    id: 'ex_zercher_squat',
    name: 'Zercher Squat',
    category: 'Quadriceps',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.traps'],
    equipment: 'Barbell',
    movementPattern: 'Squat',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Squat holding barbell in the crook of the elbows, recruiting immense anterior core, upper back, and quadriceps drive.',
    setupInstructions: ['Rack barbell at elbow height.', 'Cradle barbell in crooks of bent elbows with hands clasped together.'],
    executionSteps: ['Squat deeply between knees until elbows travel between thighs.', 'Drive through floor to full standing lockout.'],
    coachingCues: ['Stay upright, brace core intensely.', 'Squeeze fists together.'],
    commonMistakes: ['Caving chest forward under weight.'],
    defaultTrainerNote: 'Old-school brute strength exercise for bulletproof posture.',
    tags: ['Quads', 'Core', 'Zercher', 'Barbell'],
  },
  {
    id: 'ex_sumo_deadlift',
    name: 'Sumo Deadlift',
    category: 'Hamstrings',
    primaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.quads'],
    secondaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.lowerBack', 'MuscleGroup.traps'],
    equipment: 'Barbell',
    movementPattern: 'Hip Hinge',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Wide-stance deadlift with hands gripping inside legs, shortening moment arm and emphasizing glute, hip adductor, and quad recruitment.',
    setupInstructions: ['Take wide stance with toes pointed outward toward plates.', 'Grip bar inside shins with straight arms.'],
    executionSteps: ['Pull chest tall, wedge hips close to bar.', 'Drive knees out and push floor away with feet.', 'Lock out hips and knees simultaneously.'],
    coachingCues: ['Spread the floor with your feet.', 'Wedge hips in before initiating pull.'],
    commonMistakes: ['Letting knees cave inward.'],
    defaultTrainerNote: 'Exceptional for powerlifting and developing hip power.',
    tags: ['Deadlift', 'Sumo', 'Glutes', 'Strength'],
  },
  {
    id: 'ex_trap_bar_deadlift',
    name: 'Trap-Bar Deadlift (Hex Bar)',
    category: 'Hamstrings',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.lowerBack', 'MuscleGroup.traps'],
    equipment: 'Trap Bar',
    movementPattern: 'Hip Hinge',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Deadlift inside a hexagonal bar with neutral handles, centering load directly along body axis to minimize lumbar shear stress.',
    setupInstructions: ['Step inside hex bar, feet hip-width apart.', 'Grip neutral handles, brace core, and flatten spine.'],
    executionSteps: ['Drive through heels, extending hips and knees evenly.', 'Lock out hips tall at the top.', 'Hinge back down with control.'],
    coachingCues: ['Push ground away.', 'Chest up tall.'],
    commonMistakes: ['Rounding back upon lift-off.'],
    defaultTrainerNote: 'Safest, most efficient heavy hinge pattern for athletic performance.',
    tags: ['Deadlift', 'Trap Bar', 'Strength', 'Legs'],
  },
  {
    id: 'ex_glute_ham_raise',
    name: 'Glute-Ham Raise (GHR)',
    category: 'Hamstrings',
    primaryMuscles: ['MuscleGroup.hamstrings', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.calves', 'MuscleGroup.lowerBack'],
    equipment: 'Machine',
    movementPattern: 'Isolation',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Posterior chain machine exercise flexing the knee while extending the hip, building bulletproof hamstring strength against sprinting tears.',
    setupInstructions: ['Secure feet in GHR footplate with thighs supported on curved thigh pad.', 'Start in horizontal alignment.'],
    executionSteps: ['Lower torso forward by extending knees until body is horizontal.', 'Pull with hamstrings to flex knees and return body upright.'],
    coachingCues: ['Maintain straight line through hips.', 'Do not bend at waist.'],
    commonMistakes: ['Breaking at the hips on the way up.'],
    defaultTrainerNote: 'The #1 movement for hamstring injury prevention and athletic speed.',
    tags: ['Hamstrings', 'Glutes', 'GHR', 'Posterior Chain'],
  },

  // ==========================================
  // CALVES, GLUTES, ABS
  // ==========================================
  {
    id: 'ex_tibialis_raise',
    name: 'Tibialis Anterior Raise',
    category: 'Calves',
    primaryMuscles: ['MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Bodyweight',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Prehab',
    description: 'Dorsiflexion exercise strengthening the tibialis anterior on the front of the shin to prevent shin splints and absorb knee landing shock.',
    setupInstructions: ['Stand with back against a wall, feet placed 1 to 2 feet in front.'],
    executionSteps: ['Pull toes and forefoot up toward shins as high as possible while balancing on heels.', 'Hold for 1 second at peak contraction.', 'Lower toes smoothly back to floor.'],
    coachingCues: ['Pull toes to the ceiling.', 'Feel the burn on the front of the shin.'],
    commonMistakes: ['Bending knees during the movement.'],
    defaultTrainerNote: 'Essential for runners, basketball players, and knee bulletproofing.',
    tags: ['Calves', 'Tibialis', 'Prehab', 'Knee Health'],
  },
  {
    id: 'ex_single_leg_calf_raise',
    name: 'Single-Leg Calf Raise',
    category: 'Calves',
    primaryMuscles: ['MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.calves'],
    equipment: 'Bodyweight',
    movementPattern: 'Isolation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Unilateral calf raise performed off an elevated step to correct left/right ankle imbalances and maximize deep gastrocnemius stretch.',
    setupInstructions: ['Stand on edge of step on ball of one foot holding a support lightly for balance.'],
    executionSteps: ['Lower heel down into deep calf stretch.', 'Press through big toe ball to maximum height.', 'Pause at peak contraction.'],
    coachingCues: ['2 second stretch at the bottom.', 'Drive through the ball of the foot.'],
    commonMistakes: ['Bouncing rapidly.'],
    defaultTrainerNote: 'Builds calf symmetry and Achilles tendon resilience.',
    tags: ['Calves', 'Unilateral', 'Bodyweight'],
  },
  {
    id: 'ex_ab_machine_crunch',
    name: 'Machine Abdominal Crunch',
    category: 'Core',
    primaryMuscles: ['MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.coreAbs'],
    equipment: 'Machine',
    movementPattern: 'Spinal Flexion',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Seated selectorized crunch machine enabling progressive overload for rectus abdominis hypertrophy.',
    setupInstructions: ['Adjust seat so chest pad aligns with upper sternum.', 'Place feet behind ankle rollers.'],
    executionSteps: ['Curl ribcage down toward pelvis by contracting abdominals.', 'Exhale completely at peak crunch.', 'Return slowly to starting stretch.'],
    coachingCues: ['Think ribs to hips.', 'Do not push with your legs.'],
    commonMistakes: ['Using momentum or pushing with hip flexors.'],
    defaultTrainerNote: 'Best machine for safely loading the rectus abdominis.',
    tags: ['Core', 'Abs', 'Machine', 'Crunch'],
  },
  {
    id: 'ex_bicycle_crunch',
    name: 'Bicycle Crunch',
    category: 'Core',
    primaryMuscles: ['MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Rotation',
    difficulty: 'Beginner',
    exerciseType: 'Hypertrophy',
    description: 'Alternating rotation and flexion bringing opposite elbow to knee, recruiting high rectus abdominis and obliques activation.',
    setupInstructions: ['Lie supine with lower back pressed into floor, hands behind ears.'],
    executionSteps: ['Bring left knee to right elbow while extending left leg straight.', 'Switch smoothly to opposite side in a bicycling rhythm.'],
    coachingCues: ['Rotate through torso, not neck.', 'Keep lower back glued down.'],
    commonMistakes: ['Pulling on the back of the neck.'],
    defaultTrainerNote: 'High electromyographic activation for all abdominal sections.',
    tags: ['Core', 'Abs', 'Obliques', 'Bodyweight'],
  },

  // ==========================================
  // FUNCTIONAL & CALISTHENICS
  // ==========================================
  {
    id: 'ex_kettlebell_clean',
    name: 'Kettlebell Clean',
    category: 'Functional',
    primaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.hamstrings'],
    secondaryMuscles: ['MuscleGroup.traps', 'MuscleGroup.forearms', 'MuscleGroup.coreAbs'],
    equipment: 'Kettlebell',
    movementPattern: 'Hip Hinge',
    difficulty: 'Intermediate',
    exerciseType: 'Power',
    description: 'Explosive hip extension lifting kettlebell from between legs into the front rack position without banging the forearm.',
    setupInstructions: ['Stand behind kettlebell with feet slightly wider than hips.'],
    executionSteps: ['Hinge hips, hike bell between legs, and snap hips forward explosively.', 'Keep bell close to body like zipping a jacket.', 'Catch bell smoothly in rack position against chest and forearm.'],
    coachingCues: ['Snap hips forward.', 'Tame the arc; keep bell close.'],
    commonMistakes: ['Letting bell swing far out and slam into forearm.'],
    defaultTrainerNote: 'Foundation for kettlebell presses, squats, and Olympic clean progressions.',
    tags: ['Functional', 'Kettlebell', 'Clean', 'Power'],
  },
  {
    id: 'ex_kettlebell_snatch',
    name: 'Kettlebell Snatch',
    category: 'Functional',
    primaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.hamstrings', 'MuscleGroup.shoulders'],
    secondaryMuscles: ['MuscleGroup.traps', 'MuscleGroup.coreAbs'],
    equipment: 'Kettlebell',
    movementPattern: 'Hip Hinge',
    difficulty: 'Advanced',
    exerciseType: 'Power',
    description: 'Continuous ballistic swing launching kettlebell from between legs directly to an overhead lockout in one seamless motion.',
    setupInstructions: ['Hike kettlebell backward between legs in athletic hinge.'],
    executionSteps: ['Drive hips forward explosively.', 'Guide bell upward vertically, punch hand through handle at the top into lockout.'],
    coachingCues: ['Punch upward into the bell at top.', 'Absorb landing smoothly on eccentric.'],
    commonMistakes: ['Allowing bell to flop over wrist.'],
    defaultTrainerNote: 'Supreme cardiovascular, power, and posterior chain conditioner.',
    tags: ['Functional', 'Kettlebell', 'Snatch', 'Conditioning'],
  },
  {
    id: 'ex_handstand_pushup',
    name: 'Handstand Push-Up',
    category: 'Functional',
    primaryMuscles: ['MuscleGroup.shoulders', 'MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.upperChest', 'MuscleGroup.traps', 'MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Vertical Push',
    difficulty: 'Advanced',
    exerciseType: 'Strength',
    description: 'Elite calisthenics vertical pressing exercise pushing entire bodyweight from inverted position against a wall or freestanding.',
    setupInstructions: ['Kick up into handstand against a smooth wall with hands 6 inches out.'],
    executionSteps: ['Lower crown of head forward to touch floor forming a tripod with hands.', 'Press through palms to return to full arm lockout.'],
    coachingCues: ['Elbows at 45 degrees.', 'Maintain tight hollow body.'],
    commonMistakes: ['Flaring elbows out to 90 degrees.'],
    defaultTrainerNote: 'Pinnacle of calisthenics shoulder pressing power.',
    tags: ['Calisthenics', 'Handstand', 'Shoulders', 'Advanced'],
  },
  {
    id: 'ex_muscle_up',
    name: 'Bar Muscle-Up',
    category: 'Functional',
    primaryMuscles: ['MuscleGroup.lats', 'MuscleGroup.triceps'],
    secondaryMuscles: ['MuscleGroup.midChest', 'MuscleGroup.biceps', 'MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Compound',
    difficulty: 'Advanced',
    exerciseType: 'Power',
    description: 'Explosive vertical pull transitioning over the pull-up bar directly into a straight-bar dip lockout.',
    setupInstructions: ['Grip pull-up bar with false grip or standard overhand grip.'],
    executionSteps: ['Perform explosive pull-up aiming sternum to bar.', 'Transition chest over bar by rolling wrists forward.', 'Press to full straight-bar dip lockout.'],
    coachingCues: ['Pull high and fast.', 'Throw head and shoulders over the bar.'],
    commonMistakes: ['Kicking legs unevenly (chicken winging).'],
    defaultTrainerNote: 'Master strict high pull-ups and straight bar dips first.',
    tags: ['Calisthenics', 'Muscle-Up', 'Pull-Up', 'Advanced'],
  },
  {
    id: 'ex_l_sit',
    name: 'L-Sit Hold',
    category: 'Core',
    primaryMuscles: ['MuscleGroup.coreAbs'],
    secondaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.triceps'],
    equipment: 'Bodyweight',
    movementPattern: 'Isometric',
    difficulty: 'Intermediate',
    exerciseType: 'Strength',
    description: 'Isometric gymnastics hold supporting body on parallel bars or floor with legs extended horizontally at 90 degrees.',
    setupInstructions: ['Place hands on parallettes or floor, depress shoulders to push floor away.'],
    executionSteps: ['Lift feet and extend legs completely straight out in front.', 'Hold position for desired seconds while breathing steadily.'],
    coachingCues: ['Push shoulders down away from ears.', 'Lock knees and point toes.'],
    commonMistakes: ['Bending knees prematurely.'],
    defaultTrainerNote: 'Unrivaled hip flexor and abdominal compression strength.',
    tags: ['Core', 'L-Sit', 'Calisthenics', 'Isometric'],
  },

  // ==========================================
  // BOXING & CONDITIONING
  // ==========================================
  {
    id: 'ex_shadow_boxing',
    name: 'Shadow Boxing',
    category: 'Boxing',
    primaryMuscles: ['MuscleGroup.fullBody'],
    secondaryMuscles: ['MuscleGroup.shoulders', 'MuscleGroup.coreAbs', 'MuscleGroup.calves'],
    equipment: 'Bodyweight',
    movementPattern: 'Conditioning',
    difficulty: 'Beginner',
    exerciseType: 'Conditioning',
    description: 'Rhythmic boxing combinations, head movement, and footwork in free space building rotational conditioning and punching mechanics.',
    setupInstructions: ['Assume boxing stance with lead foot forward, hands protecting chin, elbows tucked.'],
    executionSteps: ['Throw continuous punches (jab, cross, hooks, uppercuts) while shifting weight and slipping punches.', 'Work for 2 to 3-minute timed rounds with constant bounce.'],
    coachingCues: ['Stay light on toes.', 'Rotate hips and pivot rear foot on punches.'],
    commonMistakes: ['Flat-footed stance or dropping guard.'],
    defaultTrainerNote: 'Essential boxing warm-up and aerobic conditioning drill.',
    tags: ['Boxing', 'Conditioning', 'Cardio', 'Agility'],
  },
  {
    id: 'ex_box_jump_plyo',
    name: 'Plyometric Box Jump',
    category: 'Conditioning',
    primaryMuscles: ['MuscleGroup.quads', 'MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.calves', 'MuscleGroup.hamstrings'],
    equipment: 'Other',
    movementPattern: 'Jump',
    difficulty: 'Intermediate',
    exerciseType: 'Power',
    description: 'Explosive two-foot takeoff onto a plyometric box focusing on maximum hip extension and quiet, soft landing mechanics.',
    setupInstructions: ['Stand facing plyometric box at arm length with feet hip-width apart.'],
    executionSteps: ['Swing arms back and hinge hips into quarter squat.', 'Explode upward extending hips, knees, and ankles.', 'Land softly in athletic crouch on top of box.', 'Step down one foot at a time.'],
    coachingCues: ['Land like a ninja: quiet and controlled.', 'Step down, do not jump backward off box.'],
    commonMistakes: ['Landing stiff-legged.'],
    defaultTrainerNote: 'Develops explosive lower-body power and rate of force development.',
    tags: ['Plyometrics', 'Box Jump', 'Power', 'Conditioning'],
  },
  {
    id: 'ex_jump_rope',
    name: 'Jump Rope / Skipping',
    category: 'Conditioning',
    primaryMuscles: ['MuscleGroup.calves'],
    secondaryMuscles: ['MuscleGroup.forearms', 'MuscleGroup.shoulders', 'MuscleGroup.coreAbs'],
    equipment: 'Other',
    movementPattern: 'Cardio',
    difficulty: 'Beginner',
    exerciseType: 'Cardio',
    description: 'Classic boxing conditioning drill developing foot speed, ankle elasticity, hand-eye coordination, and aerobic capacity.',
    setupInstructions: ['Hold handles loosely at hip height, elbows tucked close to body.'],
    executionSteps: ['Rotate rope with wrists, jumping 1 to 2 inches off floor on balls of feet.', 'Maintain steady, relaxed breathing.'],
    coachingCues: ['Turn rope with wrists, not whole arms.', 'Land softly on balls of feet.'],
    commonMistakes: ['Jumping excessively high.'],
    defaultTrainerNote: 'Fundamental warm-up and conditioning staple for Alpha X Gym.',
    tags: ['Cardio', 'Jump Rope', 'Boxing', 'Conditioning'],
  },

  // ==========================================
  // MOBILITY, WARM-UP & COOL-DOWN
  // ==========================================
  {
    id: 'ex_worlds_greatest_stretch',
    name: "World's Greatest Stretch",
    category: 'Mobility',
    primaryMuscles: ['MuscleGroup.glutes', 'MuscleGroup.hamstrings'],
    secondaryMuscles: ['MuscleGroup.lowerBack', 'MuscleGroup.upperChest'],
    equipment: 'Bodyweight',
    movementPattern: 'Mobility',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Comprehensive dynamic mobility movement opening thoracic spine, hips, groin, and hamstrings in a single flow.',
    setupInstructions: ['Step forward into a deep lunge with both hands on floor inside front foot.'],
    executionSteps: ['Drop inside elbow toward floor for deep hip stretch.', 'Rotate torso and reach inside arm straight up to ceiling, tracking hand with eyes.', 'Place hands down and rock hips back to stretch front hamstring.', 'Step forward and repeat on other side.'],
    coachingCues: ['Follow hand with eyes on thoracic rotation.', 'Breathe into the hip opener.'],
    commonMistakes: ['Rushing through positions without pausing.'],
    defaultTrainerNote: 'The gold standard full-body warm-up movement before heavy lifting.',
    tags: ['Mobility', 'Warm-up', 'Hips', 'Thoracic'],
  },
  {
    id: 'ex_90_90_hip_rotation',
    name: '90/90 Hip Mobility Rotation',
    category: 'Mobility',
    primaryMuscles: ['MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.quads'],
    equipment: 'Bodyweight',
    movementPattern: 'Mobility',
    difficulty: 'Beginner',
    exerciseType: 'Mobility',
    description: 'Seated hip flow mobilizing internal and external hip rotation simultaneously to eliminate squat and hinge restrictions.',
    setupInstructions: ['Sit on floor with front leg bent at 90 degrees in front and back leg bent at 90 degrees behind.'],
    executionSteps: ['Sit tall, lean gently over front knee for external rotation stretch.', 'Rotate knees smoothly through center to opposite side without hands if possible.'],
    coachingCues: ['Keep spine tall.', 'Rotate smoothly without lifting off floor.'],
    commonMistakes: ['Slouching lower back.'],
    defaultTrainerNote: 'Immediate improvement in squat depth and hip health.',
    tags: ['Mobility', 'Hip Mobility', '90-90', 'Flexibility'],
  },
  {
    id: 'ex_cat_cow',
    name: 'Cat-Cow Spinal Flow',
    category: 'Mobility',
    primaryMuscles: ['MuscleGroup.lowerBack'],
    secondaryMuscles: ['MuscleGroup.coreAbs'],
    equipment: 'Bodyweight',
    movementPattern: 'Mobility',
    difficulty: 'Beginner',
    exerciseType: 'Warm-up',
    description: 'Gentle spinal flexion and extension on all fours, warming up the intervertebral discs and paraspinal muscles.',
    setupInstructions: ['Kneel on all fours with hands under shoulders and knees under hips.'],
    executionSteps: ['Inhale, drop belly toward floor, lift chest and gaze (Cow position).', 'Exhale, arch spine upward toward ceiling, tuck chin and tailbone (Cat position).', 'Flow smoothly between both positions with your breath.'],
    coachingCues: ['Move segment by segment through spine.', 'Synchronize breath with movement.'],
    commonMistakes: ['Forcing neck too far into hyperextension.'],
    defaultTrainerNote: 'Essential spinal decompressor before and after heavy training.',
    tags: ['Mobility', 'Spine', 'Warm-up', 'Yoga'],
  },
  {
    id: 'ex_pigeon_pose',
    name: 'Pigeon Pose Stretch',
    category: 'Flexibility',
    primaryMuscles: ['MuscleGroup.glutes'],
    secondaryMuscles: ['MuscleGroup.lowerBack'],
    equipment: 'Bodyweight',
    movementPattern: 'Flexibility',
    difficulty: 'Beginner',
    exerciseType: 'Cool-down',
    description: 'Deep static stretch for the piriformis, gluteus medius, and hip capsule, relieving sciatic tension and lower back tightness.',
    setupInstructions: ['From plank, bring right knee forward behind right wrist, shin angled across mat.', 'Extend left leg straight back with top of foot on floor.'],
    executionSteps: ['Square hips to floor.', 'Walk hands forward and fold torso over front leg.', 'Hold for 30 to 60 seconds, taking deep diaphragmatic breaths.'],
    coachingCues: ['Keep hips square.', 'Sink heavier on each exhalation.'],
    commonMistakes: ['Collapsing onto one hip.'],
    defaultTrainerNote: 'Crucial post-leg workout static cool-down stretch.',
    tags: ['Flexibility', 'Cool-down', 'Glutes', 'Hips'],
  },
];

console.log(`Prepared ${NEW_EXERCISES.length} high-quality new exercises to expand the library.`);
