/**
 * Alpha X AI — Curated Seed Knowledge Documents
 * Phase 3 — Fitness Knowledge / RAG Layer
 *
 * NOTE: These documents serve as a curated, testable seed knowledge set for the
 * Alpha X RAG architecture. They are NOT the exhaustive Alpha X gym database.
 * No fabricated scientific papers, fake DOIs, or fabricated authors are used.
 */

import { KnowledgeDocument } from './knowledge.types';

export const SEED_KNOWLEDGE_DOCUMENTS: KnowledgeDocument[] = [
  // ==========================================================================
  // TRAINING DOMAIN (13 Documents)
  // ==========================================================================
  {
    id: 'doc_trn_001',
    title: 'Progressive Overload Principles & Implementation',
    topic: 'TRAINING',
    subtopic: 'Progression Schemes',
    content:
      'Progressive overload is the gradual increase of stress placed upon the musculoskeletal system during resistance training. While commonly implemented by increasing external load (weight), overload can also be achieved by increasing repetitions at a given load, increasing set volume, improving movement quality and range of motion, controlling eccentric tempo, or decreasing inter-set rest intervals while preserving performance. For beginners, linear progression focused on movement standardization and technical proficiency yields superior neural and hypertrophic adaptations.',
    source: 'American College of Sports Medicine (ACSM) Position Stand: Progression Models in Resistance Training for Healthy Adults',
    sourceType: 'SECONDARY_EVIDENCE',
    publicationYear: 2009,
    evidenceLevel: 'STRONG',
    tags: ['progressive overload', 'progression', 'load', 'reps', 'beginner', 'technique', 'volume'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 2,
  },
  {
    id: 'doc_trn_002',
    title: 'Hypertrophy Stimulus & Weekly Volume Thresholds',
    topic: 'TRAINING',
    subtopic: 'Hypertrophy Fundamentals',
    content:
      'Muscle hypertrophy is driven primarily by mechanical tension applied to muscle fibers across sufficiently demanding contractions. Scientific consensus identifies a dose-response relationship between weekly direct working sets per muscle group and hypertrophy up to an individual ceiling. A foundational recommendation is 10 to 20 hard working sets per muscle group per week for intermediate to advanced trainees, distributed across multiple sessions (e.g., 2–3 times per week). Beyond 8–10 sets in a single session, per-set hypertrophic efficiency diminishes due to cumulative local fatigue ("junk volume").',
    source: 'Schoenfeld, Ogborn, & Krieger (2017). Dose-response relationship between weekly resistance training volume and increases in muscle mass: A systematic review and meta-analysis. Journal of Sports Sciences.',
    sourceType: 'PRIMARY_EVIDENCE',
    authors: ['Schoenfeld BJ', 'Ogborn D', 'Krieger JW'],
    publicationYear: 2017,
    evidenceLevel: 'STRONG',
    tags: ['hypertrophy', 'volume', 'weekly sets', 'stimulus', 'mechanical tension', 'junk volume'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 2,
  },
  {
    id: 'doc_trn_003',
    title: 'Strength Specificity & High-Load Adaptation',
    topic: 'TRAINING',
    subtopic: 'Strength Fundamentals',
    content:
      'Maximal strength adaptation follows the SAID principle (Specific Adaptations to Imposed Demands). Producing maximal force requires neural adaptations including motor unit recruitment, rate coding, inter-muscular coordination, and motor pattern efficiency. Heavy loads (≥80–85% of 1RM, typically 1–5 reps) produce superior strength gains compared to lighter loads, primarily through enhanced central nervous system adaptations and neuromuscular efficiency, even when hypertrophy between conditions is matched.',
    source: 'Suchomel, Nimphius, & Stone (2016). The Importance of Muscular Strength in Athletic Performance. Sports Medicine.',
    sourceType: 'SECONDARY_EVIDENCE',
    authors: ['Suchomel TJ', 'Nimphius S', 'Stone MH'],
    publicationYear: 2016,
    evidenceLevel: 'MODERATE',
    tags: ['strength', '1rm', 'specificity', 'neural adaptation', 'motor units', 'intensity'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 3,
  },
  {
    id: 'doc_trn_004',
    title: 'Training Volume Allocation & Diminishing Returns',
    topic: 'TRAINING',
    subtopic: 'Volume Management',
    content:
      'Training volume must be adjusted based on an individual trainee’s recovery capacity, training age, and nutritional status. The dose-response curve exhibits an inverted-U shape: insufficient volume fails to maximize stimulus, while excessive volume causes systemic overreaching, connective tissue strain, and performance decrements. Coaches should prioritize the Minimum Effective Dose (MED) before escalating to Maximum Recoverable Volume (MRV).',
    source: 'Baz-Valle et al. (2022). A Systematic Review of The Effects of Different Resistance Training Volumes on Muscle Hypertrophy. Journal of Human Kinetics.',
    sourceType: 'PRIMARY_EVIDENCE',
    authors: ['Baz-Valle E', 'Fontes-Villalba M', 'Santos-Concejero J'],
    publicationYear: 2022,
    evidenceLevel: 'MODERATE',
    tags: ['volume', 'mrv', 'med', 'diminishing returns', 'fatigue', 'recovery'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 2,
  },
  {
    id: 'doc_trn_005',
    title: 'Training Frequency & Muscle Protein Synthesis Dynamics',
    topic: 'TRAINING',
    subtopic: 'Frequency Programming',
    content:
      'Resistance training elevates muscle protein synthesis (MPS) for approximately 24 to 48 hours following a bout in trained individuals. Training each muscle group twice weekly typically yields superior hypertrophy compared to once-weekly training when total volume is equated, primarily by enabling higher movement quality per set and distributing volume without excessive intra-session fatigue.',
    source: 'Schoenfeld, Ogborn, & Krieger (2016). Effects of Resistance Training Frequency on Measures of Muscle Hypertrophy: A Systematic Review and Meta-Analysis. Sports Medicine.',
    sourceType: 'PRIMARY_EVIDENCE',
    authors: ['Schoenfeld BJ', 'Ogborn D', 'Krieger JW'],
    publicationYear: 2016,
    evidenceLevel: 'STRONG',
    tags: ['frequency', 'muscle protein synthesis', 'mps', 'split', 'hypertrophy'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 2,
  },
  {
    id: 'doc_trn_006',
    title: 'Training Intensity: Load vs Effort Differentiation',
    topic: 'TRAINING',
    subtopic: 'Intensity Concepts',
    content:
      'In exercise science, "intensity" has two distinct meanings: 1) Intensity of Load (% of 1 Repetition Maximum), which defines the mechanical resistance relative to peak capacity; and 2) Intensity of Effort (proximity to concentric failure, measured via RIR or RPE). Hypertrophy can occur across a broad spectrum of loading zones (6 to 30+ repetitions) provided sets are performed with high intensity of effort (0–3 RIR). Strength adaptations, however, are highly sensitive to intensity of load (typically ≥80% 1RM).',
    source: 'Alpha X Curated General Knowledge — Exercise Science Fundamentals',
    sourceType: 'GENERAL_KNOWLEDGE',
    evidenceLevel: 'GENERAL',
    tags: ['intensity', '1rm', 'effort', 'load', 'reps', 'strength', 'hypertrophy'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 4,
  },
  {
    id: 'doc_trn_007',
    title: 'Proximity to Failure & Hypertrophic Threshold',
    topic: 'TRAINING',
    subtopic: 'Proximity to Failure',
    content:
      'Maximal high-threshold motor unit recruitment is achieved when sets are taken reasonably close to concentric failure. Research shows that training between 0 and 3 Reps in Reserve (RIR) produces comparable muscle hypertrophy to training to absolute momentary muscular failure, while generating significantly less neuromuscular fatigue and permitting greater total training volume and recovery over microcycles.',
    source: 'Refalo et al. (2023). Similar Muscle Hypertrophy Following Eight Weeks of Resistance Training to Failure vs with Repetitions-in-Reserve. Scandinavian Journal of Medicine & Science in Sports.',
    sourceType: 'PRIMARY_EVIDENCE',
    authors: ['Refalo MC', 'Helms ER', 'Trevorrow T', 'Fyfe JJ'],
    publicationYear: 2023,
    evidenceLevel: 'STRONG',
    tags: ['proximity to failure', 'failure', 'rir', 'motor units', 'hypertrophy', 'fatigue'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 2,
  },
  {
    id: 'doc_trn_008',
    title: 'Reps in Reserve (RIR) Protocol & Definition',
    topic: 'TRAINING',
    subtopic: 'Subjective Effort Metrics',
    content:
      'Reps in Reserve (RIR) quantifies how many additional repetitions a lifter could perform with acceptable form before concentric muscular failure occurs. For example: RIR 0 represents absolute technical failure (zero additional reps possible); RIR 1 indicates 1 rep remaining; RIR 2 indicates 2 reps remaining. RIR enables precise autoregulation of training intensity across differing daily readiness states.',
    source: 'Helms et al. (2016). Application of the Repetitions in Reserve-Based Rating of Perceived Exertion Scale for Resistance Training. Strength and Conditioning Journal.',
    sourceType: 'SECONDARY_EVIDENCE',
    authors: ['Helms ER', 'Cronin J', 'Storey A', 'Zourdos MC'],
    publicationYear: 2016,
    evidenceLevel: 'MODERATE',
    tags: ['rir', 'reps in reserve', 'autoregulation', 'effort', 'fatigue', 'programming'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 3,
  },
  {
    id: 'doc_trn_009',
    title: 'Rating of Perceived Exertion (RPE) Scale in Resistance Training',
    topic: 'TRAINING',
    subtopic: 'Subjective Effort Metrics',
    content:
      'The resistance training RPE scale operates on a 1 to 10 continuum directly correlated with RIR: RPE 10 corresponds to maximum effort (0 RIR, no further reps possible); RPE 9 corresponds to 1 RIR; RPE 8 corresponds to 2 RIR; RPE 7 corresponds to 3 RIR. While originally derived from Borg’s cardiovascular scale, the resistance-training-specific RPE scale standardizes intensity prescription based on proximity to concentric muscular failure.',
    source: 'Zourdos et al. (2016). Novel Resistance Training-Specific Rating of Perceived Exertion Scale Measuring Repetitions in Reserve. Journal of Strength and Conditioning Research.',
    sourceType: 'SECONDARY_EVIDENCE',
    authors: ['Zourdos MC', 'Klemp A', 'Dolan C', 'Quiles JM'],
    publicationYear: 2016,
    evidenceLevel: 'MODERATE',
    tags: ['rpe', 'rating of perceived exertion', 'rir', 'scale', 'effort', 'resistance training'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 3,
  },
  {
    id: 'doc_trn_010',
    title: 'Exercise Selection & Biomechanical Stability',
    topic: 'TRAINING',
    subtopic: 'Biomechanics',
    content:
      'Exercise selection for hypertrophy should prioritize external stability, consistent resistance profile matching the muscle’s length-tension curve, and pain-free execution through active range of motion. Stable exercises (e.g., chest-supported rows, hack squats, machine presses) reduce the requirement for internal stabilization and balance, allowing greater motor unit recruitment and closer proximity to failure of the target muscle with lower systemic fatigue.',
    source: 'Alpha X Curated General Knowledge — Biomechanics & Program Design',
    sourceType: 'GENERAL_KNOWLEDGE',
    evidenceLevel: 'GENERAL',
    tags: ['exercise selection', 'biomechanics', 'stability', 'hypertrophy', 'machines', 'free weights'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 4,
  },
  {
    id: 'doc_trn_011',
    title: 'Range of Motion & Stretch-Mediated Hypertrophy',
    topic: 'TRAINING',
    subtopic: 'Range of Motion',
    content:
      'Training through a full range of motion (ROM) generally produces superior muscle hypertrophy compared to partial range of motion. Recent investigations emphasize that the lengthened (stretched) position of the muscle under load contributes uniquely to stretch-mediated hypertrophy and sarcomere genesis in series. Trainees should control the eccentric phase and prioritize loaded tension in the lengthened position.',
    source: 'Wolf et al. (2023). Partial vs Full Range of Motion Resistance Training: A Systematic Review and Meta-Analysis. Sports Medicine.',
    sourceType: 'PRIMARY_EVIDENCE',
    authors: ['Wolf M', 'Androulakis-Korakakis P', 'Fisher JP', 'Gentil P'],
    publicationYear: 2023,
    evidenceLevel: 'MODERATE',
    tags: ['range of motion', 'rom', 'stretch-mediated hypertrophy', 'eccentric', 'lengthened position'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 2,
  },
  {
    id: 'doc_trn_012',
    title: 'Inter-Set Rest Intervals for Hypertrophy & Strength',
    topic: 'TRAINING',
    subtopic: 'Rest Intervals',
    content:
      'Rest interval length directly impacts set performance and total volume load. Studies demonstrate that longer rest intervals (2 to 3+ minutes for multi-joint compound lifts, 1 to 2 minutes for single-joint isolation exercises) allow greater resynthesis of phosphocreatine and clearance of central/peripheral fatigue, resulting in higher mechanical tension and superior long-term hypertrophy and strength compared to very short (<60 second) rest intervals.',
    source: 'Grgic et al. (2017). The Effects of Rest Interval Duration on Muscle Hypertrophy: A Systematic Review. European Journal of Sport Science.',
    sourceType: 'PRIMARY_EVIDENCE',
    authors: ['Grgic J', 'Schoenfeld BJ', 'Skrepnik M', 'Davies TB'],
    publicationYear: 2017,
    evidenceLevel: 'STRONG',
    tags: ['rest intervals', 'rest', 'recovery between sets', 'hypertrophy', 'strength', 'compound'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 2,
  },
  {
    id: 'doc_trn_013',
    title: 'Periodization & Deload Implementation',
    topic: 'TRAINING',
    subtopic: 'Periodization',
    content:
      'Periodization is the systematic planning of athletic training to optimize performance and prevent overtraining. In hypertrophy and strength contexts, mesocycles of 4 to 8 weeks are typically concluded with a planned deload week (reducing volume by 40–50% and/or intensity by 20–30%) to dissipate cumulative systemic fatigue, allow joint/connective tissue remodeling, and resensitize muscle tissue to training stimuli.',
    source: 'Essentials of Strength Training and Conditioning (4th Ed.), National Strength and Conditioning Association (NSCA)',
    sourceType: 'SECONDARY_EVIDENCE',
    publicationYear: 2016,
    evidenceLevel: 'EXPERT_CONSENSUS',
    tags: ['periodization', 'deload', 'mesocycle', 'fatigue management', 'recovery', 'volume reduction'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 3,
  },

  // ==========================================================================
  // NUTRITION DOMAIN (6 Documents)
  // ==========================================================================
  {
    id: 'doc_nut_001',
    title: 'Energy Balance & Caloric Prescription for Body Composition',
    topic: 'NUTRITION',
    subtopic: 'Energy Balance',
    content:
      'The first law of thermodynamics governs body weight alteration: sustained energy intake exceeding total daily energy expenditure (TDEE) results in mass gain, whereas a caloric deficit results in mass loss. For fat loss with maximal lean mass preservation, a moderate deficit of 15% to 25% below maintenance (approximately 300–600 kcal/day) is optimal for most athletes. Excessively aggressive deficits (>30%) increase muscle protein breakdown and reduce training performance.',
    source: 'Hall et al. (2012). Energy balance and its components: implications for body weight regulation. American Journal of Clinical Nutrition.',
    sourceType: 'PRIMARY_EVIDENCE',
    authors: ['Hall KD', 'Heymsfield SB', 'Kemnitz JW', 'Klein S'],
    publicationYear: 2012,
    evidenceLevel: 'STRONG',
    tags: ['energy balance', 'calories', 'caloric deficit', 'tdee', 'fat loss', 'body composition'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 2,
  },
  {
    id: 'doc_nut_002',
    title: 'Dietary Protein Requirements for Resistance Trained Athletes',
    topic: 'NUTRITION',
    subtopic: 'Macronutrients: Protein',
    content:
      'Extensive meta-analytic evidence indicates that dietary protein intakes between 1.6 g/kg and 2.2 g/kg (approximately 0.73–1.0 g/lb) of total body mass per day maximize muscle protein synthesis and optimize muscle hypertrophy and retention during resistance training. In hypocaloric conditions (fat loss deficits), protein intakes towards the higher end or up to 2.3–3.1 g/kg of fat-free mass may assist with satiety, thermogenesis, and lean tissue preservation.',
    source: 'Morton et al. (2018). A systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength in healthy adults. British Journal of Sports Medicine.',
    sourceType: 'PRIMARY_EVIDENCE',
    authors: ['Morton RW', 'Murphy KT', 'McKellar SR', 'Phillips SM'],
    publicationYear: 2018,
    evidenceLevel: 'STRONG',
    tags: ['protein', 'muscle growth', 'hypertrophy', 'macronutrients', 'protein intake', 'amino acids'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 2,
  },
  {
    id: 'doc_nut_003',
    title: 'Carbohydrates & Glycolytic Resistance Training Demands',
    topic: 'NUTRITION',
    subtopic: 'Macronutrients: Carbohydrates',
    content:
      'Anaerobic resistance training relies predominantly on intramuscular glycogen for ATP regeneration during high-intensity contractions. Adequate carbohydrate intake (3–7 g/kg/day depending on training volume and phase) preserves training volume performance, optimizes glycogen replenishment between sessions, and attenuates exercise-induced cortisol elevation. Carbohydrate timing around workouts supports performance, but total daily intake remains the paramount variable.',
    source: 'Burke et al. (2011). Carbohydrates for training and competition. Journal of Sports Sciences.',
    sourceType: 'SECONDARY_EVIDENCE',
    authors: ['Burke LM', 'Hawley JA', 'Wong SH', 'Jeukendrup AE'],
    publicationYear: 2011,
    evidenceLevel: 'EXPERT_CONSENSUS',
    tags: ['carbohydrates', 'glycogen', 'energy', 'training performance', 'macronutrients'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 3,
  },
  {
    id: 'doc_nut_004',
    title: 'Essential Dietary Fat & Endocrine Health',
    topic: 'NUTRITION',
    subtopic: 'Macronutrients: Fat',
    content:
      'Dietary lipids are vital for endocrine regulation (steroid hormone synthesis including testosterone), fat-soluble vitamin absorption (A, D, E, K), and cellular membrane integrity. Prolonged fat restriction below 15–20% of total caloric intake or below 0.5–0.7 g/kg/day can impair reproductive and anabolic hormone production. Lifters should maintain fat intake within 20% to 35% of total daily energy.',
    source: 'Alpha X Curated General Knowledge — Sports Nutrition Fundamentals',
    sourceType: 'GENERAL_KNOWLEDGE',
    evidenceLevel: 'GENERAL',
    tags: ['fat', 'dietary fat', 'hormones', 'testosterone', 'essential fatty acids', 'macronutrients'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 4,
  },
  {
    id: 'doc_nut_005',
    title: 'Dietary Fiber & Gastrointestinal Satiety Guidelines',
    topic: 'NUTRITION',
    subtopic: 'Micronutrition & Fiber',
    content:
      'Dietary fiber enhances gastric distension, delays stomach emptying, modulates postprandial glucose absorption, and fosters a healthy gut microbiome. A practical target for athletes is 10 to 14 grams of fiber per 1,000 kcal consumed (typically 25–40g daily). Adequate fiber during hypocaloric phases supports adherence through enhanced satiety, while excessive fiber (>60g) close to workouts may induce gastrointestinal distress.',
    source: 'Alpha X Curated General Knowledge — Nutrition Adherence & Fiber',
    sourceType: 'GENERAL_KNOWLEDGE',
    evidenceLevel: 'GENERAL',
    tags: ['fiber', 'satiety', 'diet adherence', 'gut health', 'digestion', 'fat loss'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 4,
  },
  {
    id: 'doc_nut_006',
    title: 'Body Recomposition Mechanisms & Feasibility',
    topic: 'NUTRITION',
    subtopic: 'Body Recomposition',
    content:
      'Body recomposition—simultaneous skeletal muscle hypertrophy and adipose tissue reduction—is physiologically feasible, particularly in untrained individuals, trainees returning after a layoff, individuals with higher baseline body fat, and athletes adopting rigorous progressive overload combined with high protein intake (≥2.0 g/kg). It requires maintaining a small caloric deficit (or maintenance) paired with high mechanical tension.',
    source: 'Barakat et al. (2020). Body Recomposition: Can Trained Individuals Build Muscle and Lose Fat at the Same Time? Strength and Conditioning Journal.',
    sourceType: 'PRIMARY_EVIDENCE',
    authors: ['Barakat C', 'Pearson J', 'Escalante G', 'Campbell B'],
    publicationYear: 2020,
    evidenceLevel: 'MODERATE',
    tags: ['body recomposition', 'recomp', 'fat loss', 'muscle gain', 'protein', 'caloric maintenance'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 2,
  },

  // ==========================================================================
  // RECOVERY DOMAIN (3 Documents)
  // ==========================================================================
  {
    id: 'doc_rec_001',
    title: 'Sleep Architecture & Neuromuscular Recovery',
    topic: 'RECOVERY',
    subtopic: 'Sleep Dynamics',
    content:
      'Sleep is the primary restorative state for human physiology. Slow-wave sleep (N3) facilitates human growth hormone (HGH) secretion and cellular repair, while REM sleep supports cognitive recovery and motor skill consolidation. Chronic sleep restriction (<7 hours per night) reduces insulin sensitivity, elevates muscle catabolism markers, dampens testosterone, and increases injury rates in athletic populations. Target duration is 7 to 9 hours nightly.',
    source: 'Watson (2017). Sleep and Athletic Performance. Current Sports Medicine Reports.',
    sourceType: 'SECONDARY_EVIDENCE',
    authors: ['Watson AM'],
    publicationYear: 2017,
    evidenceLevel: 'STRONG',
    tags: ['sleep', 'recovery', 'growth hormone', 'fatigue', 'central nervous system', 'rest'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 3,
  },
  {
    id: 'doc_rec_002',
    title: 'Systemic vs Local Neuromuscular Fatigue Mechanisms',
    topic: 'RECOVERY',
    subtopic: 'Fatigue Management',
    content:
      'Fatigue manifests at peripheral sites (calcium ion flux, glycogen depletion, metabolite accumulation in muscle fibers) and centrally in the nervous system (voluntary activation failure of alpha motor neurons). Central fatigue accumulates disproportionately when sets are taken to absolute failure or when high axial loads are applied repeatedly. Understanding this allows coaches to structure workout splits that rotate axial spinal loading and manage fatigue.',
    source: 'Enoka & Duchateau (2016). Translating fatigue to human performance. Medicine and Science in Sports and Exercise.',
    sourceType: 'SECONDARY_EVIDENCE',
    authors: ['Enoka RM', 'Duchateau J'],
    publicationYear: 2016,
    evidenceLevel: 'MODERATE',
    tags: ['fatigue', 'central fatigue', 'peripheral fatigue', 'recovery', 'nervous system', 'load'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 3,
  },
  {
    id: 'doc_rec_003',
    title: 'Recovery Load Monitoring & Deload Indicators',
    topic: 'RECOVERY',
    subtopic: 'Readiness & Deloads',
    content:
      'Objective and subjective markers signal when cumulative training load exceeds adaptive capacity: 1) Unexplained drop in rep performance across compound movements; 2) Persistent joint irritability or tendon tenderness; 3) Disrupted sleep quality despite high fatigue; 4) Depressed motivation to train; 5) Elevated resting heart rate. Identifying these markers early prevents non-functional overreaching.',
    source: 'Alpha X Curated General Knowledge — Athlete Readiness & Monitoring',
    sourceType: 'GENERAL_KNOWLEDGE',
    evidenceLevel: 'GENERAL',
    tags: ['recovery', 'monitoring', 'readiness', 'deload', 'overreaching', 'overtraining', 'biofeedback'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 4,
  },

  // ==========================================================================
  // SUPPLEMENTS DOMAIN (3 Documents)
  // ==========================================================================
  {
    id: 'doc_sup_001',
    title: 'Creatine Monohydrate: Mechanisms, Dosing, & Safety',
    topic: 'SUPPLEMENTS',
    subtopic: 'Creatine',
    content:
      'Creatine monohydrate is the most extensively researched and verified ergogenic nutritional aid. Intramuscular phosphocreatine stores buffer rapid ATP regeneration during high-intensity anaerobic work. Supplementation typically increases muscle creatine stores by 20–40%, leading to enhanced maximal strength, power output, work capacity, and lean body mass. Standard daily maintenance dosing is 3 to 5 grams per day; a loading phase of 20g/day for 5–7 days speeds saturation but is not mandatory. It has a stellar safety record in healthy individuals.',
    source: 'International Society of Sports Nutrition (ISSN) Position Stand: Safety and efficacy of creatine supplementation in exercise, sport, and medicine. Journal of the International Society of Sports Nutrition.',
    sourceType: 'PRIMARY_EVIDENCE',
    authors: ['Kreider RB', 'Kalman DS', 'Antonio J', 'Ziegenfuss TN'],
    publicationYear: 2017,
    evidenceLevel: 'STRONG',
    tags: ['creatine', 'creatine monohydrate', 'atp', 'phosphocreatine', 'strength', 'supplements', 'dosing'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 2,
  },
  {
    id: 'doc_sup_002',
    title: 'Protein Powder Supplementation & Leucine Threshold',
    topic: 'SUPPLEMENTS',
    subtopic: 'Protein Supplements',
    content:
      'Protein powders (whey, casein, soy, pea-rice blends) provide a convenient, bioavailable source of essential amino acids. Whey protein is rich in branched-chain amino acids, particularly leucine (typically 2.5–3g per 25g serving), which serves as the primary biochemical trigger activating the mTORC1 signaling pathway for muscle protein synthesis. While whole foods should form the nutritional base, protein supplements provide practical convenience for meeting daily protein targets.',
    source: 'International Society of Sports Nutrition (ISSN) Position Stand: Protein and Exercise. Journal of the International Society of Sports Nutrition.',
    sourceType: 'SECONDARY_EVIDENCE',
    authors: ['Jäger R', 'Kerksick CM', 'Campbell BI', 'Cribb PJ'],
    publicationYear: 2017,
    evidenceLevel: 'STRONG',
    tags: ['protein powder', 'whey', 'leucine', 'mtor', 'supplements', 'muscle protein synthesis'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 3,
  },
  {
    id: 'doc_sup_003',
    title: 'Caffeine Ergogenic Profile & Pre-Workout Dosing',
    topic: 'SUPPLEMENTS',
    subtopic: 'Caffeine',
    content:
      'Caffeine acts as a central nervous system stimulant through competitive antagonism of adenosine A1 and A2A receptors, reducing perception of effort (RPE), delaying fatigue, and enhancing neuromuscular motor unit recruitment. Ergogenic benefits for strength, power, and muscular endurance occur at doses of 3 to 6 mg per kilogram of body mass consumed approximately 30 to 60 minutes prior to exercise. Higher doses (>9 mg/kg) do not confer additional benefits and elevate risk of tremors, anxiety, and tachycardia.',
    source: 'International Society of Sports Nutrition (ISSN) Position Stand: Caffeine and Exercise Performance. Journal of the International Society of Sports Nutrition.',
    sourceType: 'PRIMARY_EVIDENCE',
    authors: ['Guest NS', 'VanDusseldorp TA', 'Nelson MT', 'Grgic J'],
    publicationYear: 2021,
    evidenceLevel: 'STRONG',
    tags: ['caffeine', 'pre-workout', 'ergogenic', 'adenosine', 'rpe', 'supplements', 'energy'],
    createdAt: '2026-10-02T00:00:00.000Z',
    updatedAt: '2026-10-02T00:00:00.000Z',
    version: '1.0',
    priority: 2,
  },
];
